### ISSUE TITLE
Replace all the hardcoded strings with @string resource

### ISSUE THREAD

**Issue by luckyman000786** [openMF/mobile-wallet#10]
**Expected Behavior:**
 All strings should be added in strings.xml file which are hardcoded in other xml files.
**Observed Behavior:**
Only Some Strings are defined in strings.xml file while others are not.
**Possible Fix:**
Remaining Strings can be declared in strings.xml file of the app.
Can I go ahead on this ? @edcable @therajanmaurya

**Comment by naman14** [comment]
@luckyman000786 Yeah, you can work on this and extract the string resources. Just so you know, you can use Alt+L shortcut to automatically extract string resources, (hover over the hardcoded string in layouts and then Alt+L)
