### ISSUE TITLE
Redesign: Use TextInputLayout instead of EditText in MobileVerification Activity

### ISSUE THREAD

**Issue by haran2248** [openMF/mobile-wallet#1015]
**Summary:**

In activity_mobile_verification , EditText is used for Mobile Number and OTP instead of TextInputLayout .

Instead of a simple EditText with hints,It should be changed to TextInputLayout and TextInputEditText for mobile number and OTP .

**Comment by darktheme74** [comment]
@luckyman20 can I work on this issue?

**Comment by luckyman20** [comment]
@devansh-299 @shiv07tiwari Is this issue still persisting?

@darktheme74 Sorry, I am not aware if this issue still persists so @devansh-299 @shiv07tiwari would help you.

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 @shiv07tiwari Is this issue still persisting?
> 
> @darktheme74 Sorry, I am not aware if this issue still persists so @devansh-299 @shiv07tiwari would help you.

@darktheme74 @luckyman20 #1018 already solves this issue but hasn't been merged yet.
