### ISSUE TITLE
feat: Add search option in the country above

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#1033]
**Summary:**
The country in the register screen does not have an option to search for countries and the user has to scroll all the way down to find their country. 
**Steps to reproduce:**
1. Go to register screen
2. Click on the drop down in the utmost top of the page

**Expected behavior:**
A search option to find the respective countries easily

**Screenshots:**
<img src="https://user-images.githubusercontent.com/37215508/92091701-bb624380-edee-11ea-8ae7-8bc4700b62ab.jpg" width=300 height=600/>

**Would you like to work on the issue?**
Yes

**Comment by Bhavnaharitsa** [comment]
@devansh-299 @shiv07tiwari @luckyman20 Thoughts?

**Comment by devansh-299** [comment]
@Bhavnaharitsa since the country names are already sorted alphabetically, I personally don't think that having a search option will improve the experience by a significant margin.

**Comment by refactor-droidyy** [comment]
@devansh-299 you are right .... But instead we can add one thing let's say I know the country code and entered the same and now the flag image should refect the same for cross check... What are you thoughts? I just see this somewhere in an application...

**Comment by devansh-299** [comment]
@Bhavnaharitsa @refactor-droidyy I just checked. In fact, we do have a searching option for countries, it's not significant before you tap on that. Maybe you can modify the issue to address this problem and make it similar to what we have for country codes for mobile numbers.

Also, @refactor-droidyy the searching option we already have has the functionality that you described.

**Comment by refactor-droidyy** [comment]
@devansh-299 👍

**Comment by devansh-299** [comment]
@Bhavnaharitsa do you want to work on the updated issue?

**Comment by haran2248** [comment]
Can i work on this?I didnt exactly understand what is supposed to be done?Can you guide me?

**Comment by luckyman20** [comment]
@haran2248 I don't think there is anything to be done here as @devansh-299 mentioned that the country list is already sorted alphabetically.
