### ISSUE TITLE
Master and Development link in Readme.md

### ISSUE THREAD

**Issue by aksharma53** [openMF/mobile-wallet#1034]
**Summary:**

The master and development using same [**buildpassing**](https://travis-ci.com/openMF/mobile-wallet) link so we can combine them to one.

**Steps to reproduce:**

Just look into Readme.md file and access master and development through buildpassing.

**Expected behavior:**

They should be combine to access or should have different link.

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

Not specific.

**Screenshots:**

![readme](https://user-images.githubusercontent.com/50196057/93666768-769d0480-fa9e-11ea-89df-b9902513c0a8.PNG)

**Comment by devansh-299** [comment]
@Alphasaurs Both the badges are using different links. The link: https://travis-ci.com/openMF/mobile-wallet is used to specify the project while the branch build status badges are being queried by ...?branch=**master**  for `master` branch and ...?branch=**dev** for `dev` branch

**Comment by devansh-299** [comment]
@Alphasaurs I am closing this issue, as according to me the problem reported is irrelevant. If I missed something then please mention.
