### ISSUE TITLE
Remove redundant and unused Namespace declarations in XML files

### ISSUE THREAD

**Issue by ReCodee** [openMF/mobile-wallet#1035]
Summary:
There are some unused and redundant namespace declarations in XML files like `activity_link_bank_account.xml`, `activity_login.xml`, and 6 others and they are showing warnings in the android studio. My intention is to remove these declarations to keep the code clean (dev branch).

**Comment by ReCodee** [comment]
@luckyman20 can I work on this issue?

**Comment by devansh-299** [comment]
@ReCodee sure go-ahead
