### ISSUE TITLE
  Not checking for valid VPA string in SendFragment

### ISSUE THREAD

**Issue by Me-Abhishek-patel** [openMF/mobile-wallet#1037]
**Summary:**

In SendFragment there is no logic for VPA String pre validation . When user clicks on submit button, the app should pre validate the VPA String before sending it to SearchClient or before searching it in FineractRepository. Should be checked if the input is a valid VPA (and follows proper VPA formating) or it is just a random string. Using **Regular Expressions** to pre validate will save unnecessary API/Repository burden, It will make validation faster, and will be good for user experience.

**Steps to reproduce:**

1. Go to Payments from Home
2. Type Amount (less than TOTAL BALANCE)
3. Type any RANDOM stirng which can not be a valid VPA ID (eg. adkdjckjc, cjbdcjkancjd)
4. Click on SUBMIT button

**Expected behavior:**

Should first pre validate the VPA string with regular expressions and if it is found to be a valid vpa then only be searched in repository.
The same is done in Google pay app also to insntantly validate VPA as shown in the below screenrecording.

![gpayss](https://user-images.githubusercontent.com/62820147/96967993-ebe07700-152d-11eb-8f9a-654a5dde50ea.gif)
_(screenRecording from gpay app)_

**Observed behavior:**

Directly uses any random input String to be searched in repository without prevalidation.

**Device and Android version:**

Honor 7x  
Android 9 Pie 
StockRom

**ScreenRecording:**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/62820147/96968850-36162800-152f-11eb-927b-7121f728beb5.gif)

**Comment by Me-Abhishek-patel** [comment]
@luckyman20 @devansh-299 Can I work on this issue?

**Comment by devansh-299** [comment]
@Me-Abhishek-patel seems valid! Please go ahead
