### ISSUE TITLE
Add CI/CD GitHub Actions and remove other build checks

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/mobile-wallet#1043]
**Summary:**

The project currently has Codeship, CircleCI, Travis We need to remove these and use Github actions.
Following are the requirements:-

* Generate the apk for every pull request and every commit on the dev and master branch.
* Build checks for every commit on any other branch.

**Comment by s-ayush2903** [comment]
@shiv07tiwari SIr, I would like to work on this issue.

**Comment by shiv07tiwari** [comment]
@s-ayush2903 I see you have already added a PR, I will review it soon. 
An important suggestion, For any issue, always wait to get approval from any of the maintainers before creating the PR. :-)

**Comment by s-ayush2903** [comment]
Sorry for the inconvenience. I'll take care of it now onwards
