### ISSUE TITLE
Migration of Dagger to Hilt

### ISSUE THREAD

**Issue by pknotfound** [openMF/mobile-wallet#1046]
**Summary:**

The current version of the application uses Dagger for dependency injection. Google has released Hilt to simplify Dagger-related infrastructure for Android. Using Hilt eases the setup for dependency injection, and also provides easy way for bindings in various build types.

Hilt would also help reduce most of the boilerplate code generated by Dagger.

**Comment by pknotfound** [comment]
@devansh-299 @edcable 
Can I take up this issue?

**Comment by justdvnsh** [comment]
@Priyansh-Kedia I am a new contributor to this project. It would be great if you'd let me take up this issue.

**Comment by ReCodee** [comment]
@justdvnsh Relevance of this issue is not yet confirmed, you can look for other open issues or make your own :)
