### ISSUE TITLE
docs: Update CI badges in Readme

### ISSUE THREAD

**Issue by s-ayush2903** [openMF/mobile-wallet#1050]
**Summary:**
People willing make their initial contributions to project are welcome to fix this issue. Currently, readme file displays old CI badges from latest merge commit from travis CI, but as now we've completely migrated to [GitHub-Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions) it'll be better if we update the badges there and use GH-Actions ci badges.

**Steps to reproduce:**
Have a look in badges section of [readme](https://github.com/openMF/mobile-wallet#mobile-wallet)

**Expected behavior:**
Should display GH-Actions badges

**Observed behavior:**
Old travis ci badges

What did you see instead?  Describe your issue in detail here.
|Outdated Badges[CI]|
|--|
|![travisBadges](https://user-images.githubusercontent.com/56556919/98973708-16748d00-253a-11eb-8085-02ae6113556f.png)|
**Device and Android version:**
NA

**Screenshot:**
Attached above

PS: The GH-Actions badges for concerned workflow can be generated from [mobile-wallet actions](https://github.com/openMF/mobile-wallet/actions).

**Comment by vedpatwardhan** [comment]
I want to work on this issue, please guide me on what exactly is to be done as this is the first time I'm contributing.

**Comment by s-ayush2903** [comment]
Hi @VedPatwardhan thanks for your interest. All you need to do in this issue is to update the url from where it is fetching the build status, currently it uses latest travis build status' URL, but few days back we've migrated to GitHub Actions so those Travis status badges are no longer of use, since we are on GH-Actions, therefore we'll be fetching latest build status' on GH-Actions, you should go to the link given in the desc. and generate badge markdwon(md) and then replace travis build URLs in readme with the ones you generated. 
You should be able to see an option like the given one for badge md generation:
|Status Badge Generation Option|
|--|
|![statusBagge](https://user-images.githubusercontent.com/56556919/99141736-44f68300-2674-11eb-9428-8120c1cb3272.png)|

You should use branch filter for the workflows and set it to first `dev` and then `master` branch. We had recent merges on `dev` then you should be able to get its md, but we haven't triggered any workflow on `master`, so for that you should feel free to ask maintainers when you once open a PR regarding the concerned issue.
Feel free to ask if you further have any queries.

**Comment by vedpatwardhan** [comment]
I have generated the markdown for the dev branch, what should I do next, as I'm not able to do the same for the master branch? 
Thank you for guiding me uptil now.

**Comment by s-ayush2903** [comment]
Good, create a PullRequest now and then wait for a review, the reviewer will be able to help you then what to do with the `master` branch.

**Comment by s-ayush2903** [comment]
Good, create a PullRequest now and then wait for a review, the reviewer will be able to help you then what to do with the `master` branch workflow badge.

**Comment by vedpatwardhan** [comment]
Okay.
Thanks a lot for your help.
