### ISSUE TITLE
Add Instructions to get the latest apk after github actions in README

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/mobile-wallet#1055]
After migrating to Github actions, we can get the latest apk files from artifacts. We need to add instructions for the same in the README file.

**Comment by Sparsh1212** [comment]
@shiv07tiwari I would love to work on this issue. Please assign this to me.

**Comment by devansh-299** [comment]
Sure go ahead

**Comment by Sparsh1212** [comment]
@devansh-299 I have to write the instructions to download the zip folder from the artifacts via the **Github actions GUI.** If i am thinking in the wrong direction then please do correct me.

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 I have to write the instructions to download the zip folder from the artifacts via the **Github actions GUI.** If i am thinking in the wrong direction then please do correct me.

Yes!
