### ISSUE TITLE
Debug hardcoded XML layout . and fix the position of various  Attributes.

### ISSUE THREAD

**Issue by Aman09072000** [openMF/mobile-wallet#1057]
**Summary:**

Summarize your issue here.

**Steps to reproduce:**

How can we reproduce again the issue?

**Expected behavior:**

What did you expect the app to do?

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by Aman09072000** [comment]
@devansh-299 @shiv07tiwari  can I work on this issue?

**Comment by devansh-299** [comment]
@Aman09072000 please follow the issue template describing the issue in detail

**Comment by Aman09072000** [comment]
**Summary:**

when we go to the payment option the distribution between VPA and mobile number tag is not equal it seems bad as it is hardcoded and the same when we go to the history part there the text of price is very small and it is stick with a corner so it becomes difficult to find it or we say that we focus more on that and the same issue I faced when I go to finance activity the text size and other design-related property of city name are not proper there. as I found it is also hardcoded.

**Steps to reproduce:**

1- goto to the payment option
2- get the equally distributed layout
3- goto the history and finance part of the app. its price and city are properly placed and visible.

**Expected behavior:**

the visual appearance of or app gets improved and the user will easily see all important details like history price and city in finance.

**Device and Android version:**

 Samsung Galaxy S3 Android 4.1 Ice Cream Sandwich

**Screenshots**
<img width="245" alt="Annotation 2020-11-23 091706" src="https://user-images.githubusercontent.com/64133045/99928295-76570900-2d6e-11eb-8bfe-f2c051f5bded.png">

<img width="245" alt="Annotation 2020-11-22 174748" src="https://user-images.githubusercontent.com/64133045/99928312-81aa3480-2d6e-11eb-964b-b34ad0f1c67c.png">

<img width="245" alt="Annotation 2020-11-23 091638" src="https://user-images.githubusercontent.com/64133045/99928319-866ee880-2d6e-11eb-9942-fa3251f31fc6.png">

**Comment by Aman09072000** [comment]
<img width="245" alt="Annotation 2020-11-23 093250" src="https://user-images.githubusercontent.com/64133045/99928390-e6658f00-2d6e-11eb-97d5-5791f38565e2.png">

**Comment by Aman09072000** [comment]
@devansh-299 @shiv07tiwari  can i work on it

**Comment by ReCodee** [comment]
@Aman09072000  I guess your fork repo/branch is not up to date with the latest merged commits, as there have been some UI  changes in the latest commits.

**Comment by Aman09072000** [comment]
@ReCodee i check there is also same problem buddy. 
by the way thanks for suggestion:) bro

**Comment by ReCodee** [comment]
@Aman09072000 Can you please update the screenshots as per the latest app UI, as it would help confirm relevancy of the issue.

**Comment by Aman09072000** [comment]
yaa buddy sure,
here is the updated screenshots.

<img width="245" alt="223" src="https://user-images.githubusercontent.com/64133045/100130593-e8cc0400-2ea8-11eb-9cd0-053e1e8ab272.png">

<img width="245" alt="Annotation 2020-11-24 225741" src="https://user-images.githubusercontent.com/64133045/100130496-c76b1800-2ea8-11eb-8591-ac1f60d9a7a3.png">
<img width="245" alt="223" src="https://user-images.githubusercontent.com/64133045/100130499-c89c4500-2ea8-11eb-8123-d1e3a35cc974.png">


<img width="245" alt="Annotation 2020-11-24 225715" src="https://user-images.githubusercontent.com/64133045/100130443-b9b59280-2ea8-11eb-95e6-0b3331075920.png">

**Comment by ReCodee** [comment]
@Aman09072000  This the screenshot of UI of the `HistoryFragment.java`

<img src = "https://user-images.githubusercontent.com/59660380/100189418-4b0d1f00-2f12-11eb-9324-cea34fa0e88e.jpg" height = "500" width = "300" >

to update your branch you can rebase your branch head with upstream repo branch head.

**Comment by Aman09072000** [comment]
Thanq very much buddy. I literally don't know about this.
in the updated App, there is also the same problem which I mentioned above. 

the relevant screenshots are attached below.
<img width="202" alt="Annotation 2020-11-25 144809" src="https://user-images.githubusercontent.com/64133045/100208018-40f91980-2f2e-11eb-9dfc-e64dae777da0.png">

<img width="212" alt="Annotation 2020-11-25 144703" src="https://user-images.githubusercontent.com/64133045/100208035-448ca080-2f2e-11eb-839e-c120683778a7.png">

<img width="213" alt="Annotation 2020-11-25 144854" src="https://user-images.githubusercontent.com/64133045/100208052-49515480-2f2e-11eb-823f-0902a28c6578.png">

**Comment by devansh-299** [comment]
@Aman09072000 the irregular chip sizes for "VPA" and "Mobile Number" inside the `Send Fragment` can in fact be made equal by settings the appropriate width value. But for the transaction amount and state names, I don't see any problem. Can you please explain what approach you have in mind for these?

**Comment by Aman09072000** [comment]
@devansh-299  yaa, sure buddy for "VPA" and "Mobile Number" my plan is to make them equally separated so the both of them look the same and good visually good. 
and my plan for transition amount I am planning to make them clickable so that when the user taps on it. it will directly go in the debited activity and the same with the credit one. I will make both of the credit and debit more attractive and try to change their styling as well. 

and bro would you see the line written in Account Activity and send Activity that "Linked Bank Account" and "Select transfer method" they both lines are looking very simple. I would like to style them properly and remove that extra space below these lines.

**Comment by Aman09072000** [comment]
@devansh-299  buddy ??
