### ISSUE TITLE
Adding a Save Button in Edit profile section to make App more user interactive. 

### ISSUE THREAD

**Issue by Aman09072000** [openMF/mobile-wallet#1060]
**Summary:**

In our Mifos wallet app when we go to the edit profile part. there is not any button for saving all the details which user will change. there are only  2 buttons for change passwords and change passcode and there is not any button for saving Data.
I will add that button there and make the app more user friendly.

**Steps to reproduce:**

1- goto edit the profile section of the app.
2- add the Save button there to save all data manually.
3-make button user-friendly and interactive place. 

**Expected behavior:**

make the Save button to make the app more interactive.

**Device and Android version:**

Samsung Galaxy S3 Android 4.1 Ice Cream Sandwich

**Screenshots:**

<img width="200" alt="ss1" src="https://user-images.githubusercontent.com/64133045/100215163-b23cca80-2f36-11eb-9e14-1141c881399a.png">

<img width="207" alt="ss2" src="https://user-images.githubusercontent.com/64133045/100215185-b668e800-2f36-11eb-97ab-cf821b9281d6.png">

**Comment by ReCodee** [comment]
@Aman09072000 There is a save button in form of a FloatingActionButton which shows up when changes are made.

**Comment by Aman09072000** [comment]
@ReCodee   I know there is Button Buddy but it is not user-friendly. it is placed in an unfriendly place so most of the users facing problem to find it and its size and color is not inappropriate in comparing to other components of the app.

my idea is to make this button more interactive and user friendly so the user will easily interact with it. I will also change the size and position of the app so it is more visible on the screen.

@devansh-299  what do you think bro?

<img width="170" alt="Annotation 2020-11-28 131124" src="https://user-images.githubusercontent.com/64133045/100496611-6038b680-317b-11eb-8d0c-8cc888882026.png">


<img width="167" alt="Annotation 2020-11-28 131209" src="https://user-images.githubusercontent.com/64133045/100496612-6333a700-317b-11eb-8128-2b08398953ab.png">

**Comment by devansh-299** [comment]
What changes do you have in mind exactly? To me personally, the floating action button looks fine

**Comment by Aman09072000** [comment]
@devansh-299 bro I want to change the design and style and position of that button so it will look more visually good. as it is placed in the corner user faces difficulty to find it. and in my view, the button will not suit the Screen as it is not mixed with the screen properly.
I think it looks great after my implementation and modification.

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 bro I want to change the design and style and position of that button so it will look more visually good. as it is placed in the corner user faces difficulty to find it. and in my view, the button will not suit the Screen as it is not mixed with the screen properly.
> I think it looks great after my implementation and modification.

Can you please attach a screenshot of your device?

**Comment by Aman09072000** [comment]
@devansh-299 I already above attach it buddy.

**Comment by Aman09072000** [comment]
issue resolve
