### ISSUE TITLE
Back Button is not visible for all Activities

### ISSUE THREAD

**Issue by rutvik-panchal** [openMF/mobile-wallet#1061]
**Summary:**

Change the color of back button, as it is not visible.
I have check the code already we are using different color for back button but is not reflected in the app.

**Steps to reproduce:**

Open Settings Activity (Back Button not visible initially)-> Click and Hold Back Button is visible

**Expected behavior:**

Back Button should be visible 

**Observed behavior:**

Back Button is not visible 

**Device and Android version:**

VIvo V17, Android 10 (FuntouchOS)

**Screenshots:**

<img width="30%" src="https://user-images.githubusercontent.com/39809059/100387096-32555400-304d-11eb-881f-e772298d0c7a.jpg">

**Comment by deepak-prajapatii** [comment]
@rutvik-panchal can i work on this issue?

**Comment by rutvik-panchal** [comment]
@deepak-prajapatii I have already raised a PR and is under review.

**Comment by Prashant830** [comment]
it's resolved. 
@devansh-299 please close this issue.

**Comment by devansh-299** [comment]
Closing this issue, please refer [this message](https://github.com/openMF/mobile-wallet/issues/1061#issuecomment-1207781670)
