### ISSUE TITLE
docs : update screenshots as per the latest UI of the app

### ISSUE THREAD

**Issue by ReCodee** [openMF/mobile-wallet#1072]
**Summary:**
There has been a lot of changes in the app UI and screenshots in `Screenshot.md` are not up to date.

**Comment by ritish099** [comment]
Can i take this issue ?

**Comment by ReCodee** [comment]
@ritish099 Sure but it's better to ask for the maintainer's approval on the issue first.

**Comment by ritish099** [comment]
@ReCodee kindly mention here any of the maintainer's you know of

**Comment by ReCodee** [comment]
@ritish099 I exactly don't know who are the maintainers, I usually tag whoever does the recent merges/reviews maybe you can do the same but the best way would be to ask this in the community channel.

**Comment by deepak-prajapatii** [comment]
@divyank00 @ritish099 @ReCodee @siebrand @vorburger Can I work on this issue?

**Comment by devansh-299** [comment]
@ReCodee we already have the updated screenshots [here](https://github.com/openMF/mobile-wallet/blob/dev/Screenshot.md). I am closing this issue for now but in case I missed something do let me know, will reopen this issue
