### ISSUE TITLE
Design of Mobile Number Field is Incorrect

### ISSUE THREAD

**Issue by ritish099** [openMF/mobile-wallet#1073]
**Summary:**

Summarize your issue here.
Design of Mobile Number Field is Incorrect

**Steps to reproduce:**

Open the app and Payments->SEND->Mobile Number

**Expected behavior:**

The design should be aligned

**Observed behavior:**

The design is not aligned

**Device and Android version:**

Samsung J6, Android 10

**Screenshots:**

<img src="https://user-images.githubusercontent.com/54978105/101445093-dd67e680-3946-11eb-9912-d88dc482a500.jpg" width="333">

**Comment by ritish099** [comment]
Can i work on it ? @miPlodder @danishjamal104 @robustTechie

**Comment by iamsh4shank** [comment]
Hey @ritish099 go ahead and feel free to ask your doubts :)

**Comment by leoshrey** [comment]
Hey, is this issue still open?
If not I would like to work on it.

**Comment by danishjamal104** [comment]
> Hey, is this issue still open?
> If not I would like to work on it.

Hey @leoshrey I think @ritish099 has already solved the issue.
