### ISSUE TITLE
App crashes while switching between SIFragment (or HistoryFragment) and SendFragment

### ISSUE THREAD

**Issue by Me-Abhishek-patel** [openMF/mobile-wallet#1074]
**Summary:**

The application crashes while executing getAllStandingInstructions in StandingInstructionsPresenter ( if SIFragment is not visible )

**Steps to reproduce:**

1. Go to Payments from Home
2. Go to SIFragment ( or HistoryFragment) by tapping on SI (or HISTORY)
3. Immediately switch back to SendFragment ( by tapping on SEND ) before SIFragment ( or HistoryFragment) can finish loading.
4. Wait few moments for app to crash

If app still doesn't crash go back to home then Go to Payments from Home again and repeat above steps.

**Expected behavior:**

The application shouldn't have crashed

**Observed behavior:**

App crashes
![stacktracess png](https://user-images.githubusercontent.com/62820147/101499978-e59a4300-3993-11eb-9451-77f5bcb0def0.jpg)

**Device and Android version:**

Honor 7x  
Android 9 Pie 
StockRom

**ScreenRecording:**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/62820147/101500758-eaabc200-3994-11eb-8d0b-645f7d8d76c9.gif)

**Comment by Me-Abhishek-patel** [comment]
@shiv07tiwari @devansh-299 @robustTechie Can I work on this issue?

**Comment by iamsh4shank** [comment]
Yeah you can work on it

**Comment by Me-Abhishek-patel** [comment]
> Yeah you can work on it

 I have linked a pr please review it.
