### ISSUE TITLE
Feat: Adding Toast for  Amount, Virtual Payment Address and Mobile Number in Payments.

### ISSUE THREAD

**Issue by Harshad09** [openMF/mobile-wallet#1088]
**Summary:**

Particular empty edittext field is not mentioned by toast on pressing submit button.

**Steps to reproduce:**

1. Go to Payments.
2. Go to SEND fragment.
3. Inside SEND fragment tap on VPA Chip or Mobile Number chip.
4. There you can press the submit button without entering anything inside both (or any) of the edittext.

**Expected behavior:**

After pressing the submit button if any of the edittext fields is empty the user should be highlighted edittext field which is empty. 

**Observed behavior:**
Application is just displaying a general toast("Please enter all the fields") not specifying which field, in particular, is not filled.

**Device and Android version:**

Redmi Note 5 Pro
Android 9 Pie
custom ROM

**Screenshots:**

![WhatsApp Image 2020-12-23 at 11 23 32 AM](https://user-images.githubusercontent.com/50478348/103035421-4bd6b680-458d-11eb-803d-2cb29f4cc87a.jpeg)
![WhatsApp Image 2020-12-23 at 11 23 31 AM](https://user-images.githubusercontent.com/50478348/103035426-4da07a00-458d-11eb-8dc4-4c6392254b44.jpeg)
![WhatsApp Image 2020-12-23 at 11 23 31 AM (1)](https://user-images.githubusercontent.com/50478348/103035429-4e391080-458d-11eb-9fa7-a81d420f2eae.jpeg)

**Comment by devansh-299** [comment]
Closing this issue, see [this](https://github.com/openMF/mobile-wallet/pull/1151#issuecomment-758161971) comment
