### ISSUE TITLE
Suggestions in Mifos Pay Android app

### ISSUE THREAD

**Issue by hg-harshitgoyal** [openMF/mobile-wallet#109]
THE 'LOG IN' PROCESS 
The login process took a lot of time and needs some amendments.
Logging in is the first step of the app and the first impression on a user so it would have been more better if the app offers them something interactive and interesting. 
Many a times when you log in the app shows error, but it does not display the reason for that error which annoys most of the users.

INTERFACE 
I found app's inner interface to be very dull and boring which automatically forces the user to close the app.
The app eventually fails to catch the users eye and attract him towards itself.
According to me the interface should be a user friendly one which I was not able to find in this app.
This is a serious issue and the company needs to work on this issue as soon as possible.

This information was for the latest version of the app and I used it on 'SAMSUNG J7 PRO' device on android version '8.1.0'.

As a conclusion I may say that the app's expected behaviour was a user friendly one having some interactive interface but the observed behaviour was totally opposite.

**Comment by luckyman20** [comment]
@hg-harshitgoyal Thank you for your suggestions, but this doesn't qualifies as a issue, so closing it.
