### ISSUE TITLE
Feat: Adding a security to check that device has root access or not.

### ISSUE THREAD

**Issue by Harshad09** [openMF/mobile-wallet#1094]
**Summary:**

We can add a security check that the device has root access or not. Because rooted devices are less secure than nonrooted devices for any banking and wallet transaction.

**Expected behavior:**

The user should not get registered if the device has root access.

**Observed behavior:**

We can add a security check for rooted devices.

**Comment by devansh-299** [comment]
@Harshad09 we do not need this change right now. In case we have a requirement for this in future, we can revisit this issue and the pull request
