### ISSUE TITLE
SI refresh doesn't work

### ISSUE THREAD

**Issue by divyank00** [openMF/mobile-wallet#1103]
**Summary:**
Refreshing SI page doesn't work.

**Steps to reproduce:**
1. Create a successful Standing Instruction
2. Press the back button on the toolbar
3. Refresh the SI page by pulling down
4. Go to Home Section
5. Open the SI page again

**Expected behavior:**
After refreshing the SI page, the new SI should be reflected

**Observed behavior:**
Refresh doesn't make a difference to the list. New SI is added only when the activity is recreated

**Device and Android version:**
OnePlus 6 
Android 10

**Screenshots:**

https://user-images.githubusercontent.com/50913976/103687417-3ebabe00-4fb6-11eb-8bed-a8bb1ab08957.mp4

**Comment by devansh-299** [comment]
Solved by #1107

**Comment by devansh-299** [comment]
Solved by #1107
