### ISSUE TITLE
EditText in debit_card_fragment to be changed to TextInputLayout

### ISSUE THREAD

**Issue by haran2248** [openMF/mobile-wallet#1119]
**Summary:**

Summarize your issue here.
The EditText in debit_card_fragment messes up the UI of the app.Therefore TextInputLayout has to be made instead of that to maintain uniformity in the UI.
**Steps to reproduce:**

How can we reproduce again the issue?
Finance->Accounts->linked accounts->Click Any bank account->Setup Upi pin-Debit card details

**Expected behavior:**

What did you expect the app to do?
An TextLayout was expected,but instead there is an editText.

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**
samsung SM-M013F
![WhatsApp Image 2021-01-06 at 14 53 36](https://user-images.githubusercontent.com/56928954/103752212-6d28af80-502f-11eb-826a-4e224b1ad295.jpeg)

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by devansh-299** [comment]
@haran2248 normal edit text seems more appropriate to me for this screen. I know it is a deviation from our overall application design. @luckyman20 what do you think?

**Comment by devansh-299** [comment]
Closing this issue because of the reason specified above. In case we require this change later, we can re-open this issue

**Comment by luckyman20** [comment]
@devansh-299 Can we handle this through our efforts in mobile UI library?
