### ISSUE TITLE
On pressing back button from passcode activity login activity is opening.

### ISSUE THREAD

**Issue by Harshad09** [openMF/mobile-wallet#1122]
https://user-images.githubusercontent.com/50478348/103763353-b254dd80-503f-11eb-9f0c-95126534d8f5.mp4

**Summary:**

Pressing the back button opens the login activity.

**Steps to reproduce:**

1. Go to the passcode activity 
2. Hit the back button

**Expected behavior:**

Login activity should only open when the user is logging in for the first time not when we press the back button in the passcode activity.

**Observed behavior:**

On pressing the back button in the passcode Activity login activity is opening.

**Device and Android version:**

Redmi Note 5 Pro
Android 9 Pie
custom ROM

**Comment by devansh-299** [comment]
@Harshad09 this issue has already been solved hence closing this issue and the linked pull request.
