### ISSUE TITLE
Feature : No confirmation on adding bank account in Accounts fragment in Finance.

### ISSUE THREAD

**Issue by Harshad09** [openMF/mobile-wallet#1152]
**Summary:**

Toast should be there in the Account fragment on adding a bank account.

**Steps to reproduce:**

1. Go to Accounts fragment in finance.
2. Click on Add Account.
3. Confirm verify mobile number.

**Expected behavior:**

A simple toast should be there "Bank added Successfully" for user understanding.

**Observed behavior:**

No toast leading to confusion.

**Comment by Prashant830** [comment]
@Harshad09 The bank added feature is still not be done or added. so we cant add Bank added Successfully toast message.

**Comment by devansh-299** [comment]
Closing this issue for the same reason @Prashant830 mentioned
