### ISSUE TITLE
Automate the EditText for date in setup UPI pin debit card section

### ISSUE THREAD

**Issue by EGOR-IND** [openMF/mobile-wallet#1154]
**Summary:**

The Edit Text to put the expiry date of debit card is not automated.

**Steps to reproduce:**

 1. Go to Setup UPI Pin activity.
 2. You can see a two EditText in debit card section one for month and another for year
 3. Try to type a date they both.
 4. You will have to fill month and year separately.

**Expected behavior:**

Those two EditText should work as one so that user don't have to switch.

**Observed behavior:**

Right now those two work separartely.

**Device and Android version:**

VIVO Y83, Android Version = 8.1.1

**Screen Recording**

https://user-images.githubusercontent.com/56648862/104602572-8c63b480-56a1-11eb-976c-4042d6146dfd.mp4

**Comment by divyank00** [comment]
Can you please upload a video

**Comment by EGOR-IND** [comment]
I uploaded a video in PR which shows the automated solution, actually I made the PR first and then made a issue because devansh told me to do so and now to upload a video i have to remove the solution code from there and then make a video but if you think it's necessary, i'll do it, So now tell me what you think?

**Comment by divyank00** [comment]
> I uploaded a video in PR which shows the automated solution, actually I made the PR first and then made a issue because devansh told me to do so and now to upload a video i have to remove the solution code from there and then make a video but if you think it's necessary, i'll do it, So now tell me what you think?

U just have to checkout in dev branch and run the code😊

**Comment by EGOR-IND** [comment]
😂I know that, I was just trying to procrastinate, okay I'll do it give me some time.

**Comment by EGOR-IND** [comment]
Hey @divyank00, man I did what you asked, I think now it's good.
