### ISSUE TITLE
Back button sequence doesn't work properly in profile fragment

### ISSUE THREAD

**Issue by EGOR-IND** [openMF/mobile-wallet#1159]
**Summary:**

when back pressed during the bottom view card is up it directly goes to the home fragment.

**Steps to reproduce:**

1. go to profile fragment.
2. swipe up the user info bottom view card 
3. now press back button, it directly exits the fragment and goes to home fragment.

**Expected behavior:**

when back pressed the bottom card should go down first and after that on second back it should exit.

**Observed behavior:**

Right now it directly exits the profile fragment.

**Device and Android version:**

VIVO Y83, Android Version = 8.1.1

**Screenshots:**

https://user-images.githubusercontent.com/56648862/104640720-dd3dd200-56ce-11eb-8d11-5dbcea6d3161.mp4

**Comment by devansh-299** [comment]
Seems valid, @EGOR-IND do you want to work on this issue?

**Comment by EGOR-IND** [comment]
Yeah @devansh-299  i'll work on this today.
