### ISSUE TITLE
The circular mask in edit profile picture activity is not visible for dark background.

### ISSUE THREAD

**Issue by EGOR-IND** [openMF/mobile-wallet#1175]
**Summary:**

The circular mask layer used as a crop layer in edit profile picture activity is not visible for dark background.

**Steps to reproduce:**

1. Go to profile fragment 
2. try to edit profile picture and choose a picture with dark background 
3. observe the circular crop.

**Expected behavior:**

the cropped section should be properly visible for every type of picture.

**Observed behavior:**

Right now that crop is not properly visible for pictures with dark background.

**Device and Android version:**

VIVO Y83, Android Version = 8.1.1

**Screenshots:**

<img src="https://user-images.githubusercontent.com/56648862/105208282-891f6b80-5b6e-11eb-9c6e-e6b56f58889b.jpeg" width="200" height="400"/>

**Comment by EGOR-IND** [comment]
I'm working on this one.

**Comment by devansh-299** [comment]
@EGOR-IND this will always be a problem for some colors

**Comment by EGOR-IND** [comment]
> @EGOR-IND this will always be a problem for some colors
 
Yeah but if you see the screenshots in PR, that makes the croping more visible to eyes because of border and grid, user will know the range from that.
