### ISSUE TITLE
QR code scanner to be added to VPA in Edit Profile

### ISSUE THREAD

**Issue by haran2248** [openMF/mobile-wallet#1177]
**Summary:**
The Edit Profile must have a QR Scanner for VPA
Summarize your issue here.

**Steps to reproduce:**

How can we reproduce again the issue?
Profile->EditProfile
**Expected behavior:**
![WhatsApp Image 2021-01-21 at 01 58 05](https://user-images.githubusercontent.com/56928954/105231119-60a66a00-5b8c-11eb-95b5-3e818eb7b78f.jpeg)

What did you expect the app to do?
The App should have 
**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?
Samsung SM-M013F
**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by divyank00** [comment]
Why would profile page have a QR code, can you justify?

**Comment by devansh-299** [comment]
Closing this issue, please refer the comments from [here](https://github.com/openMF/mobile-wallet/pull/1178)
