### ISSUE TITLE
Add image cropper for picture taken from camera

### ISSUE THREAD

**Issue by divyank00** [openMF/mobile-wallet#1187]
**Summary:**

Theres no image cropper for image taken by camera

**Steps to reproduce:**
1. Open profile
2. Click on the profile picture
3. Select camera
4. Capture image
5. Confirm
6. Observe

**Expected behavior:**
A cropper should appear as it appears for image taken from gallery

**Observed behavior:**
Image directly added to profile

**Device and Android version:**
OnePlus 6
Android 10

**Screenshots:**

https://user-images.githubusercontent.com/50913976/106235429-a6180680-6220-11eb-910b-a71500610f4b.mp4

**Comment by thedroiddiv** [comment]
Can I work on this feature?
