### ISSUE TITLE
Profile and Edit Profile Bugs

### ISSUE THREAD

**Issue by ritish099** [openMF/mobile-wallet#1193]
**Summary:**

In Profile fragment clicking on N(name icon) should only open the EditProfile not the camera option too and in EditProfile Activity clicking on N(name icon) should not open camera. The camera should be only open when user click on the camera icon below the name icon in the EditProfile

**Steps to reproduce:**

Open Profile Fragment

**Expected behavior:**

Explained above

**Observed behavior:**

Explained above

**Device and Android version:**

Any

**Screenshots:**

https://user-images.githubusercontent.com/54978105/106363189-1a4fc880-634d-11eb-8c94-9ebd1847ac2d.mp4

**Comment by divyank00** [comment]
This is not what is expected, the current behaviour is normal. For editing profile there's a button "Edit Profile". Clicking on image should edit profile image.
