### ISSUE TITLE
Problem in moving across fragment and holding in the middle between two tabs

### ISSUE THREAD

**Issue by haran2248** [openMF/mobile-wallet#1195]
**Summary:*

Moving across tabs in payment fragment is a problem,Adjacent pages are not visible
Summarize your issue here.

**Steps to reproduce:**

How can we reproduce again the issue?
Payments fragment->Switch across fragments
**Expected behavior:**

What did you expect the app to do?
It should show adjacent tabs while swiping
**Observed behavior:**

What did you see instead?  Describe your issue in detail here.
While moving across the fragments sometimes the tabs get stuck here and there causing failing in switching the tabs
**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?
samsung SM-M013F

**Screenshots:**
https://user-images.githubusercontent.com/56928954/106397409-2a41d800-6433-11eb-9e31-de11dfb73f82.mp4

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by divyank00** [comment]
Can you follow the structure to raise new issue 🙂
