### ISSUE TITLE
Mobile Number field in edit profile is accepting Ph. no. of length less than 10

### ISSUE THREAD

**Issue by EGOR-IND** [openMF/mobile-wallet#1197]
**Summary:**

Mobile Number field in edit profile is accepting Ph. no. of length less than 10

**Steps to reproduce:**

1. Go to edit profile activity,
2. change the phone number(it should have length less than 10),
3. try to save it and observe.

**Expected behavior:**

phone number should be of length 10, neither less nor more than 10.

**Observed behavior:**
Right now you can save a phone number with length less than 10

**Device and Android version:**

VIVO Y83, Android Version = 8.1.1

**Screenshots:**

https://user-images.githubusercontent.com/56648862/106501518-4607b580-64e9-11eb-9dcb-1a65fd43f95f.mp4

**Comment by EGOR-IND** [comment]
I'm working on this one.

**Comment by haran2248** [comment]
There might be phone numbers outside india possibly where the phone number is greater than or less than 10.I dont think it is possible to comment on this

**Comment by EGOR-IND** [comment]
> There might be phone numbers outside india possibly where the phone number is greater than or less than 10.I dont think it is possible to comment on this

Hey, you're right actually I was just looking into an article about it, the length is between 4-13, sorry I'm really bad with G.K LOL:).

**Comment by EGOR-IND** [comment]
I'm closing this issue but I think we should make a utility that can detect the correctness of phone number according to country, @devansh-299 @haran2248 what your thoughts on this, If you approve I'll be glad to work on it.
