### ISSUE TITLE
Does not show client details

### ISSUE THREAD

**Issue by deepak-prajapatii** [openMF/mobile-wallet#1198]
**Summary:**

The App not showing the client details

**Steps to reproduce:**

Just go to the MainActivity and see here the showclientdetails() function. There is the code that is commented out.

**Expected behavior:**

Show the client details

**Screenshots:**
![image](https://user-images.githubusercontent.com/65127291/106928627-63cb5980-6739-11eb-89e2-ce9a77530ce9.png)

**Comment by deepak-prajapatii** [comment]
@devansh-299 @EGOR-IND  
There is the issue I found. Please review it.

**Comment by Prashant830** [comment]
@deepak-prajapatii ` showclientdetails()` function is useless and still it is not used to showing client details in any mainActivity UI  so in mainActivity, mainPresenter, BaseHomeContract interface I am going to remove this function.
