### ISSUE TITLE
Progress dialog box doesn't disappear if debit card number is invalid

### ISSUE THREAD

**Issue by harshhks2** [openMF/mobile-wallet#1236]
**Summary:**

When the debit card number is invalid, a progress dialog box keeps on running until back button is pressed, and the focus is not shifted to edit Debit Card Number.

**Steps to reproduce:**

1. Go to Finance.
2. Click on any bank from the list.
3. Click on SETUP UPI.
4. Enter a wrong debit card number and any expiry date.
5. Click on the tick mark and try to go ahead.

**Expected behavior:**

A toast message indicating the error in debit card number is displayed and the focus shifts to editing the Debit card number.

**Observed behavior:**

An infinite progress dialog box appears. On pressing the back button, the focus doesn't automatically shifts to edit the debit card number.

**Device and Android version:**

Redmi Note 5 Pro, Android version 9.0

**Screenshots:**

![Dialog Box Error](https://user-images.githubusercontent.com/71138679/108075747-b76e6900-7090-11eb-9fbf-875bdda97c4b.jpeg)

**Comment by harshhks2** [comment]
I am working on it. Since this is my first issue, can somebody please guide me if this is relevant? Any help is appreciated.

**Comment by divyank00** [comment]
> I am working on it. Since this is my first issue, can somebody please guide me if this is relevant? Any help is appreciated.

Now try fixing the issue and once the issue is fixed at your side, run a gradle check by typing ./gradlew check. If all checks pass raise a pull request and you are good to go.

**Comment by harshhks2** [comment]
> > I am working on it. Since this is my first issue, can somebody please guide me if this is relevant? Any help is appreciated.
> 
> Now try fixing the issue and once the issue is fixed at your side, run a gradle check by typing ./gradlew check. If all checks pass raise a pull request and you are good to go.

Hey divyank, thanks for replying. I have generated a pull request. I know it is a small change but is my PR acceptable?
