### ISSUE TITLE
Add additional text with the recipt link when sharing

### ISSUE THREAD

**Issue by EGOR-IND** [openMF/mobile-wallet#1238]
**Summary:**

The receipt link that can be shared needs some extra message text rather than simple link while sharing.

**Steps to reproduce:**

1. Go to receipt activity,
2. share the receipt link given and observe.

**Expected behavior:**

There should be an extra message with the link it could be a promotional message or a simple sender message.

**Observed behavior:**

Right now there is no extra message with the link

**Device and Android version:**

VIVO Y83, Android Version = 8.1.1

**Screenshots:**

<img src="https://user-images.githubusercontent.com/56648862/109048971-b32ff480-76fd-11eb-831b-913866e8fc12.jpeg" width="200" height="400"/>

**Comment by EGOR-IND** [comment]
I'm working on this.

**Comment by EGOR-IND** [comment]
Hey @devansh-299 what do you think, should we add a promotional message or a sender message?

**Comment by devansh-299** [comment]
> 
> 
> Hey @devansh-299 what do you think, should we add a promotional message or a sender message?

It's a white-labelled application so I don't think we need promotional messages. Although we can have something like `Here's the receipt link for the transaction made using MifosPay from payer XYZ to payee ABC`, try referring to other bank messages etc. to get more idea.

**Comment by EGOR-IND** [comment]
> > Hey @devansh-299 what do you think, should we add a promotional message or a sender message?
> 
> It's a white-labelled application so I don't think we need promotional messages. Although we can have something like `Here's the receipt link for the transaction made using MifosPay from payer XYZ to payee ABC`, try referring to other bank messages etc. to get more idea.

Yeah the message you mentioned is good i think, I searched some sender messages too so let me create a message, i'll comment it here tommorow, if you think of some changes then just let me know I'll implement them😊.

**Comment by devansh-299** [comment]
> 
> 
> > > Hey @devansh-299 what do you think, should we add a promotional message or a sender message?
> > 
> > 
> > It's a white-labelled application so I don't think we need promotional messages. Although we can have something like `Here's the receipt link for the transaction made using MifosPay from payer XYZ to payee ABC`, try referring to other bank messages etc. to get more idea.
> 
> Yeah the message you mentioned is good i think, I searched some sender messages too so let me create a message, i'll comment it here tommorow, if you think of some changes then just let me know I'll implement them😊.

Great, will use this thread only to discuss the messages

**Comment by EGOR-IND** [comment]
Hey @devansh-299 I made the changes in code using the message you provided yesterday because I think it is the perfect message but just one question in place of XYZ and ABC, should we use user name or account number, which one is more better?
