### ISSUE TITLE
Bottom navigation bar poor visible.

### ISSUE THREAD

**Issue by Supriyo9** [openMF/mobile-wallet#1241]
**Observed behavior:**

In Home Activity bottom navigation bar is not visible properly in dark mode.

**Device and Android version:**

Xiaomi Redmi Note 7 pro, android 10

**Screenshots:**

![1614762266584](https://user-images.githubusercontent.com/65856435/109783986-95e4b400-7c30-11eb-8a25-62f185b3f054.jpg)

**Comment by Supriyo9** [comment]
I am  working in this issue.

**Comment by EGOR-IND** [comment]
@Supriyo9 actually, it is clearly visible in day mode but you're using dark mode and I can see that the bottom nav color is mixed up with fragment color so you have to do something that makes it visible in dark mode.

**Comment by Supriyo9** [comment]
> @Supriyo9 actually, it is clearly visible in day mode but you're using dark mode and I can see that the bottom nav color is mixed up with fragment color so you have to do something that makes it visible in dark mode.

Yeah @EGOR-IND , will it be better to make whole navigation bar blue and and it's options white colour

**Comment by EGOR-IND** [comment]
> > @Supriyo9 actually, it is clearly visible in day mode but you're using dark mode and I can see that the bottom nav color is mixed up with fragment color so you have to do something that makes it visible in dark mode.
> 
> Yeah @EGOR-IND , will it be better to make whole navigation bar blue and and it's options white colour

Actually i don't think it's a good choice because it doesn't go by the material design rules, we can't give a bright color to a big part of the UI because it will ruin the darl theme. How about you explore some options and I'm also going to explore some then we'll discuss them here.

**Comment by Supriyo9** [comment]
> > > @Supriyo9 actually, it is clearly visible in day mode but you're using dark mode and I can see that the bottom nav color is mixed up with fragment color so you have to do something that makes it visible in dark mode.
> > 
> > 
> > Yeah @EGOR-IND , will it be better to make whole navigation bar blue and and it's options white colour
> 
> Actually i don't think it's a good choice because it doesn't go by the material design rules, we can't give a bright color to a big part of the UI because it will ruin the darl theme. How about you explore some options and I'm also going to explore some then we'll discuss them here.

Ok It will be better to explore more options.

**Comment by DeepanshuPratik** [comment]
If it is not improvised yet can I do it?

**Comment by devansh-299** [comment]
@Supriyo9 we don't need this change at the moment hence closing this issue
