### ISSUE TITLE
Alignment in phone number in payments activity is wrong

### ISSUE THREAD

**Issue by haran2248** [openMF/mobile-wallet#1254]
**Summary:**

Summarize your issue here.
Alignment in phone number in payments activity is wrong.The phone number is aligned to center
**Steps to reproduce:**

How can we reproduce again the issue?
Payments->send fragment
**Expected behavior:**

What did you expect the app to do?
Phone number should be left aligned
**Observed behavior:**

What did you see instead?  Describe your issue in detail here.
Phone number should is right aligned
**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?
Samsung SM-M205F
![WhatsApp Image 2021-03-06 at 19 08 46](https://user-images.githubusercontent.com/56928954/110208857-7c04d480-7eaf-11eb-8eae-2e1e4e52299b.jpeg)

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by haran2248** [comment]
@EGOR-IND @devansh-299 Has this issue been solved before?

**Comment by haran2248** [comment]
Im working on this

**Comment by EGOR-IND** [comment]
@haran2248 I think this issue was raised earlier, look for that issue, maybe PR for that was submitted or not.
