### ISSUE TITLE
The Max length in phone no is 10 digits in send fragment

### ISSUE THREAD

**Issue by haran2248** [openMF/mobile-wallet#1255]
**Summary:**

Summarize your issue here.
The Max length in phone no is 10 in send fragment.When contacts with +91 are chosen from the contacts book.The phone no is partially taken.There are gaps in the phone no which the editText has not accounted for.There might be countries where phone no is greater than 10 digits.If we include +91 In india we get more than 10 digits
**Steps to reproduce:**

How can we reproduce again the issue?
Payments->send

**Expected behavior:**

What did you expect the app to do?

The entire phone has to be copied from the contact book

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

The phone is only partially copied.Due to restriction in size

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?
Samsung SM-M013F
**Screenshots:**
![WhatsApp Image 2021-03-06 at 19 08 46](https://user-images.githubusercontent.com/56928954/110209011-34327d00-7eb0-11eb-9242-81e3fbb37f71.jpeg)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by haran2248** [comment]
@EGOR-IND @devansh-299 Please let me know if the issue is valid

**Comment by EGOR-IND** [comment]
I think it's a valid issue but there is one problem that we both discussed before that in ph. no. length varies country to country so we can't bound it to size 13(including +91).

**Comment by haran2248** [comment]
im not planning on keeping any maximum size for this @EGOR-IND

**Comment by EGOR-IND** [comment]
> im not planning on keeping any maximum size for this @EGOR-IND

Okay then it's fine😄.

**Comment by alexanderon** [comment]
It would be better to keep the country selector to easily prefix related number

**Comment by thedroiddiv** [comment]
Can I work on this?

**Comment by devansh-299** [comment]
> Can I work on this?

@divyansh-dxn https://github.com/openMF/mobile-wallet/pull/1257 already addresses this issue. @haran2248 will you be able to update the PR or Divyansh can continue your work?

**Comment by haran2248** [comment]
I am busy with certain other things,divyansh can continue

**Comment by thedroiddiv** [comment]
I'm on it

**Comment by thedroiddiv** [comment]
<img src="https://user-images.githubusercontent.com/69595691/157644157-9dbb8188-a330-478c-a868-43879788057d.jpeg" alt="drawing"  width="300px" />

I'm unable to register as a new user. First of all, the error message was not properly coming then I tweaked a bit and got the response and error from server. Any idea?
