### ISSUE TITLE
App crashes when integer limit is exceeded in NewSIActivity

### ISSUE THREAD

**Issue by dubeyaayush07** [openMF/mobile-wallet#1261]
**Summary:**

The amount string is parsed to integer when creating a new standing instruction if the the string is too big it causes an integer overflow crashing the app. 

**Screen Recording**

https://user-images.githubusercontent.com/30518564/110449326-194a4d80-80e8-11eb-8c78-4dced2a09316.mp4

**Comment by dubeyaayush07** [comment]
@naman14  I would like to work on this

**Comment by EGOR-IND** [comment]
Hey @dubeyaayush07 this issue is not reproducible on my phone, I approved your PR cause I understand what you did but it's not reproducible on my phone.
