### ISSUE TITLE
Able to proceed without entering OTP at mobile number verification.

### ISSUE THREAD

**Issue by MGMSA6** [openMF/mobile-wallet#1273]
**Summary:**
At mobile number verification, after entering mobile number ,OTP is generated.
EditText for OTP and FloatingActionButton to verify OTP is made visible,
But user is able to verify OTP without entering OTP and it takes user to next registration screen.

**Steps to reproduce:**
SplashScreenActivity -> LoginActivity -> MobileVerificationActivity

**Expected behavior:**
After entering OTP there should be validation, if user has not entered OTP and try's to verify then a toast message should be shown "Please enter OTP"

**Observed behavior:**
User is able to verify OTP without entering OTP. 

**Device and Android version:**
Device name: MI A3
Android version : 10

**Screenshots:**
![Screenshot_20210606-163332](https://user-images.githubusercontent.com/47312473/120921815-4b6a4c00-c6e5-11eb-8ab2-f6717a4e7e9b.png)

**Comment by DeepanshuPratik** [comment]
If anyone is not working previously can I work over it?

**Comment by thedroiddiv** [comment]
![image](https://user-images.githubusercontent.com/69595691/157628599-b67308c6-065a-4218-920f-7c6224ef978c.png)

I think this part is has been kept intentionally, so ther would be less hassle during the dev environment.
