### ISSUE TITLE
Never Recieved OTP while trying to Sign Up as Customer

### ISSUE THREAD

**Issue by bauripalash** [openMF/mobile-wallet#132]
**Summary:**

While trying to sign up for Mifos Pay app as a customer, I entered my mobile number but never received OTP

**Steps to reproduce:**

* Open Up the app
* Signup as Customer
* Enter Mobile number
* Click next

**Expected behavior:**

Receive an OTP on my mobile

**Observed behavior:**

No OTP Received

**Device and Android version:**
* Google Pixel 2 : Android 9
* Samsung Galaxy S9+ : Android 8
* Samsung Galaxy S9 : Android 8
* Samsung Galaxy S8 : Android 7

**Screenshots :**

![screenshot from 2018-12-09 10-44-52](https://user-images.githubusercontent.com/16154204/49693725-d7489f00-fba0-11e8-9b01-868257bdd819.png)

**Comment by manddy** [comment]
@bauripalash  Is this issue resolved?

**Comment by tavishjain** [comment]
Has this issue been resolved ?

**Comment by jsahil730** [comment]
@luckyman20 we need to remove clutter. Please close this issue for now, as well all the other issues mentioned here.
