### ISSUE TITLE
Checkstyle generating error while executing gradlew check

### ISSUE THREAD

**Issue by avivijay19** [openMF/mobile-wallet#1326]
**Summary:**
Checkstyle generating error while executing `gradlew check`

**Steps to reproduce:**
Refactored according to requirement of documentation 

**Expected behavior:**
Build the application without any warning and bugs

**Observed behavior:**

1. `mobile-wallet\core\src\main\java\org\mifos\mobilewallet\core\data\fineract\repository\FineractRepository.ja
va:243: Line is longer than 100 characters (found 121). [LineLength]`

2.
`ERROR: <include id='@+id/inc_state_view'> conflicts with another tag that has the same ID file://mifospay\src\main\res\layout\fragment_si.xml Line:21`
`ERROR: <include id='@+id/inc_state_view'> conflicts with another tag that has the same ID file://mifospay\src\main\res\layout\fragment_si.xml Line:38`

**Screenshots:**

Case 1
![image](https://user-images.githubusercontent.com/66490629/162280651-99100386-b8b5-4a53-9260-d438b59fad7b.png)

Case 2
![image](https://user-images.githubusercontent.com/66490629/162280687-d3363561-c058-44f4-90c3-fa1be51c6c2c.png)

**Comment by avivijay19** [comment]
@devansh-299 
I have code ready should create a PR?

**Comment by devansh-299** [comment]
> @devansh-299 I have code ready should create a PR?

Yes, @avinash14022002! assigning this issue to you
