### ISSUE TITLE
Wrong text field labels on edit profile screen

### ISSUE THREAD

**Issue by rahul-gill** [openMF/mobile-wallet#1334]
**Summary:**
Instead of showing actual labels, the previous values of fields are used as labels.

**Screenshots:**
![image](https://user-images.githubusercontent.com/76812499/176173429-267c3ca1-1e10-4c79-91f3-8ad37af35c8e.png)

**Comment by LukasBrilla5** [comment]
hello can you please assign this issue to me ?

**Comment by rahul-gill** [comment]
@LukasBrilla5 I don't have repo access. You can work on the issue btw.

**Comment by debz-g** [comment]
@LukasBrilla5 Are you working on this issue?

**Comment by PratyushSingh07** [comment]
@rahul-gill is there any other way i can login to mobile wallet

**Comment by oyehanif** [comment]
hello can you please assign this issue to me ?

**Comment by sukarxn** [comment]
I'm working on this issue.
