### ISSUE TITLE
Redesign: /Payments/Send

### ISSUE THREAD

**Issue by letelete** [openMF/mobile-wallet#134]
**NOTICE** 

**Remember to checkout and send a pull request to the [redesign](https://github.com/openMF/mobile-wallet/tree/redesign)  branch.**

---

We are working on the app redesign. The prototype is done and can be found here: [show prototype](https://xd.adobe.com/view/8581e34d-8b91-49ec-7c21-000d98c8f18b-f3b0/?hints=off), and source files here: [show repository](https://github.com/letelete/mifos-pay-app-design). We will be working on the redesign implementation now.

This issue is about implementing the design and features of SEND tab in the Payments section.

That's what we want to achieve:

![image](https://user-images.githubusercontent.com/18665370/49696991-411d7480-fbb2-11e8-88f4-04f351c882bd.png)

**Comment by manddy** [comment]
@letelete 
![screenshot from 2018-12-24 18-30-36](https://user-images.githubusercontent.com/22556185/50400094-19313200-07aa-11e9-955e-d1a9d4843310.png)
Why is the button background color of button appearing blue even when i have set the android:background of the button to white or any other colour

**Comment by manddy** [comment]
working on this issue now

**Comment by luckyman20** [comment]
Solved in Pull Request #211
