### ISSUE TITLE
Redesign: /Payments/Invoices

### ISSUE THREAD

**Issue by letelete** [openMF/mobile-wallet#136]
**NOTICE** 

**Remember to checkout and send a pull request to the [redesign](https://github.com/openMF/mobile-wallet/tree/redesign)  branch.**

---

We are working on the app redesign. The prototype is done and can be found here: [show prototype](https://xd.adobe.com/view/8581e34d-8b91-49ec-7c21-000d98c8f18b-f3b0/?hints=off), and source files here: [show repository](https://github.com/letelete/mifos-pay-app-design). We will be working on the redesign implementation now.

This issue is about implementing the design and features of INVOICES tab in the Payments section.

That's what we want to achieve:

![image](https://user-images.githubusercontent.com/18665370/49697018-93f72c00-fbb2-11e8-982d-81533ba7b6e5.png)

**Comment by codepoet2017390** [comment]
Can i work on this @letelete  @luckyman20 ?

**Comment by letelete** [comment]
Sure @codepoet2017390

**Comment by codepoet2017390** [comment]
@letelete can u brief what all needs to be done for this issue?

**Comment by codepoet2017390** [comment]
@luckyman20 please close this
