### ISSUE TITLE
No stateview displayed if zero transactions of particular type is not present in history

### ISSUE THREAD

**Issue by devrahul-2508** [openMF/mobile-wallet#1361]
**Summary:**

Details not shown if zero transactions of particular type is performed in History Fragment. Suppose below the in the given picture no debit transactions were performed and therefore it is showing a empty recycler view which is a Bad User Experience

**Steps to reproduce:**

Go to Payments Fragment -> Select History TAB -> Select any chip(transaction type) which has zero transactions

**Expected behavior:**

A prompt should be shown that no transactions of a particular transaction type has not been performed

**Observed behavior:**

A blank recycler view

**Device and Android version:**

Device- Google Pixel 5
Api level-31

**Screenshots:**
<img src="https://user-images.githubusercontent.com/91717339/223678850-c7b6aa68-d7fb-41e0-ae99-52468f46978b.png" height=500/>

**Comment by lonewolf2208** [comment]
Hey @devrahul-2508 can you tell me how did you login to the wallet ?(As there is error showing up everytime I try to login)
