### ISSUE TITLE
Mobile(OTP) verification is not working effectively

### ISSUE THREAD

**Issue by Axhaat** [openMF/mobile-wallet#1368]
**Summary:**
Mobile verification process is not working. Without entering the valid OTP, the user can easily move to the next step. 

**Video**

https://user-images.githubusercontent.com/103241090/226285034-78284283-f49a-4585-96c9-7231bf39c4b5.mp4

**Comment by chsaikumar445** [comment]
@vorburger  @Axhaat assign this issue to me I will fix this.

**Comment by vorburger** [comment]
@chsaikumar445 surry I'm happy to assign this to you. But please note that I am not currently involved in the maintenance of this repository. You will have to find someone else in the community to review and merge your PR. All the best!

**Comment by ektaag369** [comment]
assign this issue to me. I will fix it.

**Comment by kanahia1** [comment]
assign me this issue I will do it.

**Comment by anishlukk123** [comment]
i think this has already been assigned guys

**Comment by hghost50** [comment]
Hello, can't log in using my local server credentials, it displays: Error During login. any idea?
