### ISSUE TITLE
Redesign: /Finance/Accounts

### ISSUE THREAD

**Issue by letelete** [openMF/mobile-wallet#137]
**NOTICE** 

**Remember to checkout and send a pull request to the [redesign](https://github.com/openMF/mobile-wallet/tree/redesign)  branch.**

---

We are working on the app redesign. The prototype is done and can be found here: [show prototype](https://xd.adobe.com/view/8581e34d-8b91-49ec-7c21-000d98c8f18b-f3b0/?hints=off), and source files here: [show repository](https://github.com/letelete/mifos-pay-app-design). We will be working on the redesign implementation now.

This issue is about implementing the design and features of the ACCOUNTS tab in the Finance section.

That's what we want to achieve:

![image](https://user-images.githubusercontent.com/18665370/49697043-c7d25180-fbb2-11e8-8cad-237acd525dd3.png)

**Comment by manddy** [comment]
@luckyman20 @ankurs287  i want to work on this issue ! kindly assign me this issue

**Comment by manddy** [comment]
@letelete The link for the design of the screens is not opening

**Comment by luckyman20** [comment]
@manddy I don't you need, you are given design of the screen which you need to make for this issue.

**Comment by luckyman20** [comment]
Fixed in #169
