### ISSUE TITLE
Redesign: /Finance/Cards

### ISSUE THREAD

**Issue by letelete** [openMF/mobile-wallet#138]
**NOTICE** 

**Remember to checkout and send a pull request to the [redesign](https://github.com/openMF/mobile-wallet/tree/redesign)  branch.**

---

We are working on the app redesign. The prototype is done and can be found here: [show prototype](https://xd.adobe.com/view/8581e34d-8b91-49ec-7c21-000d98c8f18b-f3b0/?hints=off), and source files here: [show repository](https://github.com/letelete/mifos-pay-app-design). We will be working on the redesign implementation now.

This issue is about implementing the design and features of the CARDS tab in the Finance section.

That's what we want to achieve:

![image](https://user-images.githubusercontent.com/18665370/49697050-e3d5f300-fbb2-11e8-8182-255e3ca7e873.png)

**Comment by shiv07tiwari** [comment]
Working on this.

**Comment by manddy** [comment]
@shiv07tiwari are you working on this issue now ?

**Comment by shiv07tiwari** [comment]
@manddy Yes.

**Comment by RajaVamsi11** [comment]
@shiv07tiwari It has been a month. Are you still working on this issue? If not I am interested in implementing this feature. Please reply asap.

**Comment by RajaVamsi11** [comment]
@letelete @luckyman20  As @shiv07tiwari was inactive on this issue for a month. I am interested in implementing this feature . Can I start working on this issue?

**Comment by shiv07tiwari** [comment]
I was busy with some college work. I already have some parts of this issue coded in my system. I will send the PR ASAP. Sorry for the delay.

**Comment by RajaVamsi11** [comment]
Sure

**Comment by luckyman20** [comment]
@shiv07tiwari Are you still working on it?

**Comment by shiv07tiwari** [comment]
@luckyman20 I am not able to properly check the implementation due to server issue. I'll send a PR as soon as the server is up.
