### ISSUE TITLE
Migrate to kotlin : home package 

### ISSUE THREAD

**Issue by zaidazaize** [openMF/mobile-wallet#1385]
**Summary:**
Migrate home package files from java to kotlin 

1. Migrate the files to kotlin
2. Perform kotlin clean up

**Comment by zaidazaize** [comment]
hey @rchtgpt can you assing me this ?

**Comment by rchtgpt** [comment]
Hi, @zaidazaize. Thanks for taking the initiative. This issue is a duplicate of a sub-issue within #1305 so I am closing it.
