### ISSUE TITLE
Cannot Login on the Mobile-Wallet

### ISSUE THREAD

**Issue by j0nimost** [openMF/mobile-wallet#1397]
**Summary:**
I cannot not login, application is stuck on the login load screen

**Steps to reproduce:**
Build and Run the Mobile Wallet then use the provided credentials on the ReadMe as login credentials
https://github.com/openMF/mobile-wallet/blob/2091f6dfe8f30515a861de6935cd579225e12da8/README.md#L40-L44
**Expected behavior:**
Expected the App to Login

**Observed behavior:**
Login Load screen is stuck

**Device and Android version:**
Google Pixel 6 Running Android 11

**Screenshots:**

<img width="189" alt="image" src="https://github.com/openMF/mobile-wallet/assets/24381727/61b56f84-a46e-4e36-a85d-0ce24f148d9e">

**Comment by therajanmaurya** [comment]
I am working on demo credentials, I will update on readme file.
