### ISSUE TITLE
Redesign Login Screen

### ISSUE THREAD

**Issue by rchtgpt** [openMF/mobile-wallet#1398]
**Summary:**

We are currently redesigning the mobile wallet to cater to our use cases. 

**Expected behavior:**
The login page should look like this:
<img width="351" alt="image" src="https://github.com/openMF/mobile-wallet/assets/44428198/29ec41f7-d94c-4780-9cb2-05d5718e04f9">

**Comment by Niranjan029** [comment]
#1398
I want to work on this.

**Comment by Krunal-375** [comment]
Can I work on it if issue still exists?
