### ISSUE TITLE
Redesign Signup Screen

### ISSUE THREAD

**Issue by rchtgpt** [openMF/mobile-wallet#1400]
**Summary:**

We are currently redesigning the mobile wallet to cater to our use cases better.

**Expected behavior:**

The signup page should look like this:
<img width="341" alt="image" src="https://github.com/openMF/mobile-wallet/assets/44428198/d9d5e1a6-e389-4953-b84d-3c131f0bf73f">

**Comment by its-me-debk007** [comment]
I wanna work on this issue. Can u assign this to me

**Comment by VishalGoel11** [comment]
If you donit mind , I wanna work on this issue . I can design a respinsive UI as you mentioned  above . So Will you assign it to me ???

**Comment by GautamCoder4019k** [comment]
@rchtgpt is the issue still open?
