### ISSUE TITLE
Redesign Home Screen Fragment

### ISSUE THREAD

**Issue by rchtgpt** [openMF/mobile-wallet#1402]
Summary:

We are currently redesigning the mobile wallet to cater to our use cases.

Expected behavior:
The home page fragment should look like this:

<img width="350" alt="image" src="https://github.com/openMF/mobile-wallet/assets/44428198/42b1dfd4-1ac9-47c8-83b9-4280bcc5776c">

**Comment by Sarthak9504** [comment]
I have forked this repo git clone https://github.com/yourUsername/mobile-wallet.git

**Comment by Sarthak9504** [comment]
Hey @rchtgpt i want to work on this issue but i am getting render problem while working can you help me with it.

**Comment by GautamCoder4019k** [comment]
hey @rchtgpt can i work on this issue if no one is working on this?
