### ISSUE TITLE
Redesign Pay From Wallet Screen Fragment

### ISSUE THREAD

**Issue by rchtgpt** [openMF/mobile-wallet#1404]
Summary:

We are currently redesigning the mobile wallet to cater to our use cases.

Expected behavior:
The pay_from_wallet page fragment should look like this:
<img width="222" alt="image" src="https://github.com/openMF/mobile-wallet/assets/44428198/8d4cd422-ade3-47c1-abb2-3c222c5527dc">

**Comment by Miteshhsingla** [comment]
Hey @rchtgpt!  i would like to take up this issue of redesigning this screen, would love to work upon this.
Regards, 
Mitesh

**Comment by rchtgpt** [comment]
> Hey @rchtgpt! i would like to take up this issue of redesigning this screen, would love to work upon this. Regards, Mitesh

Hi @Miteshhsingla, this issue already has an open PR. Please find some other issue to work on.
