### ISSUE TITLE
Bug: App crashes when FAQ  is selected

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/mobile-wallet#1440]
**Summary:**

App crashes when FAQ  is selected from the top right menu

https://github.com/openMF/mobile-wallet/assets/90026952/debb8cbc-b9f8-4e44-856a-854c58b0d7e7

**Steps to reproduce:**

- when logged into the app , click on the top right menu
- select FAQ

**Expected behavior:**

- FAQ activity should have been opened

**Observed behavior:**

- App crashes with the below message

![image](https://github.com/openMF/mobile-wallet/assets/90026952/9eb5d3aa-af8b-4fce-ae73-75fb5e60b4ec)

**Device and Android version:**
Device: Pixel 7
Android: 14

**Comment by NiranjanNlc** [comment]
please asighn this to me  @PratyushSingh07

**Comment by PratyushSingh07** [comment]
I am working on it @NiranjanNlc
