### ISSUE TITLE
Fix stretched arrow icon in mobile signup screen

### ISSUE THREAD

**Issue by Vikashgathala** [openMF/mobile-wallet#1441]
**Summary:**

Arrow button on mobile number signup screen is stretched for normal screen size phones.

**Steps to reproduce:**

Change the layout_height of button's Textview accordingly.

**Expected behavior:**

Icon should look perfectly round.

**Observed behavior:**

Arrow button was stretched making it look not good.

**Device and Android version:**

Redmi note 9 pro(curtana), Android 11
Custom rom- ArrowOS
But tested it in redmi 4x also(physical device), and pixel 7 and 7 pro (AVD).

**Screenshots:**

![Screenshot_20231231-095021](https://github.com/openMF/mobile-wallet/assets/12993867/6e3eebc8-38e5-4658-9491-4ce5542668d5)

**Comment by rdbhardwaj** [comment]
Is the PR still open?

**Comment by lkant8** [comment]
hey @Vikashgathala I wanna work on this project so can you assist me? 
Hangout: laxmipalkant01@gmail.com

**Comment by Vikashgathala** [comment]
> hey @Vikashgathala I wanna work on this project so can you assist me? Hangout: [laxmipalkant01@gmail.com](mailto:laxmipalkant01@gmail.com)

Yupp. How can i help you?
