### ISSUE TITLE
Feat: Fingerprint authenticaion in passcode screen

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/mobile-wallet#1454]
**Summary:**

There is no fingerprint authentication but only passcode.

**Expected behaviour:**

When the app asks for passcode, the user should also be able to authenticate using his fingerprint

**Observed behaviour:**

The PassCode feature only asks for passcode user saved.

**Comment by PratyushSingh07** [comment]
I will be working on this issue

**Comment by therajanmaurya** [comment]
This issue should be registered on passcode project https://github.com/openMF/mifos-passcode
