### ISSUE TITLE
Bug: Unresponsive bottom sheet in profile section

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/mobile-wallet#1492]
**Summary:**

There is a bottom sheet in the profile section of mobile wallet. However when you try to scroll up the sheet to see further details you are met with disappointment

**Steps to reproduce:**

Go to the profile section (icon at the bottom right)

**Expected behavior:**

Bottom sheet go up when swiped in that direction

**Observed behavior:**

Bottom sheet remains stuck

**Device and Android version:**

Device: Pixel 7
Android: 14

**Screenshots:**
![profile](https://github.com/openMF/mobile-wallet/assets/90026952/25b6452b-2cd0-44db-a1e2-fc386ae88951)

**Comment by PratyushSingh07** [comment]
once the login issue gets fixed i will like to work on this issue

**Comment by VivekJaiswal18** [comment]
Is there any update on this issue. Can i work on this?

**Comment by PratyushSingh07** [comment]
Yes @VivekJaiswal18 . Earlier the idea was to change the XML but right now we are in the midst of migration. So I'll be migrating the entire screen to compose and fix this during the migration itself
