### ISSUE TITLE
Migrate Java models to Kotlin Data classes of core:models

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/mobile-wallet#1529]
**Summary:**
`core:models `have most of data holder classes written in java, We need to upgrade them in kotlin data models

**Steps to reproduce:**

How can we reproduce again the issue?

**Expected behavior:**

What did you expect the app to do?

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by NiranjanNlc** [comment]
@therajanmaurya please assighn this to me .
I will be working on this ..

**Comment by NiranjanNlc** [comment]
I messed up with the previous PR and raised the new one with the suggested changes by you .
Please get it reviewed @therajanmaurya
