### ISSUE TITLE
Migrate xml to Jetpack compose - home/ui/FinanceFragment

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/mobile-wallet#1530]
**Summary:**

Summarize your issue here.

**Steps to reproduce:**

How can we reproduce again the issue?

**Expected behavior:**

What did you expect the app to do?

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by AbrahamOsmondE** [comment]
[Working](https://mifos.slack.com/archives/C5TTJS4BX/p1709304570260329?thread_ts=1709304514.152449&cid=C5TTJS4BX) on this issue

**Comment by AbrahamOsmondE** [comment]
Issue is more or less done ([PR](https://github.com/openMF/mobile-wallet/pull/1553)) but would need to wait for issue #1533 , #1534 , #1535 and #1536 to be completed
