### ISSUE TITLE
Migrate xml to Jetpack compose - home/ui/PaymentsFragment 

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/mobile-wallet#1531]
**Summary:**

Summarize your issue here.

**Steps to reproduce:**

How can we reproduce again the issue?

**Expected behavior:**

What did you expect the app to do?

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by PratyushSingh07** [comment]
It will be a big PR if we change the entire payments fragment @therajanmaurya . It will be better if we proceed by changing the components first. 
In this case we should first migrate SendFragment, ReceiveFragment, SIFragment, InvoicesFragment and HistoryFragment individually and then at last implement a Horizontal Pager to display all of these composable screen

**Comment by PratyushSingh07** [comment]
can i take up this issue After we are done with profile fragment ? I believe we may have to use HorizontalPager here and since I have never used that I would like to take it up as a challenge
