### ISSUE TITLE
Migrate xml to Jetpack compose - home/ui/ProfileFragment

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/mobile-wallet#1532]
**Summary:**

Summarize your issue here.

**Steps to reproduce:**

How can we reproduce again the issue?

**Expected behavior:**

What did you expect the app to do?

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by PratyushSingh07** [comment]
which UI should we implement in profile screen ? 

<table>
<tr> 
<th> Figma Design </th>
<th> Current Design </th>
</tr>
  <tr>
    <td><img src="https://github.com/openMF/mobile-wallet/assets/90026952/0e3ec708-7e06-4e09-8129-a125e94b9986" width=250 height=510></td>
    <td><img src="https://github.com/openMF/mobile-wallet/assets/90026952/64174433-5089-49b2-a7bb-cf1ac1c272ca" width=250 height=510></td>
  </tr>
  </table>

**Comment by PratyushSingh07** [comment]
I would like work on this @therajanmaurya . Can you please assign me this issue ?
