### ISSUE TITLE
Migrate xml to Jetpack compose - savedcards/ui/CardsFragment

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/mobile-wallet#1534]
**Summary:**

Summarize your issue here.

**Steps to reproduce:**

How can we reproduce again the issue?

**Expected behavior:**

What did you expect the app to do?

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by NiranjanNlc** [comment]
I will be working on this issues .
Please get me assigned .

**Comment by AdityaKumdale** [comment]
Hello, @therajanmauryaI I would like to work on this issue, Hey @NiranjanNlc are you working this issue too, would it be cool if I try to solve this as I saw you assigned to AccountsFragment migration.

**Comment by NiranjanNlc** [comment]
sure @AdityaKumdale , please go ahead .

**Comment by AdityaKumdale** [comment]
Thanks @NiranjanNlc

**Comment by AdityaKumdale** [comment]
@therajanmaurya can you please review my pr whenever it is convenient for you.

**Comment by AdityaKumdale** [comment]
@therajanmaurya Made changes as asked in this new PR please review when possible.
