### ISSUE TITLE
Migrate xml to Jetpack compose - merchants/ui/MerchantsFragment

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/mobile-wallet#1535]
**Summary:**

Summarize your issue here.

**Steps to reproduce:**

How can we reproduce again the issue?

**Expected behavior:**

What did you expect the app to do?

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by Akshay2004-701** [comment]
@therajanmaurya I would like to work on this issue, can I be assigned with this issue

**Comment by AbrahamOsmondE** [comment]
Hi @Akshay2004-701, have you worked on this issue? Would love to work on this issue as an issue Im working on #1530 relies on this to be done

**Comment by AdityaKumdale** [comment]
@AbrahamOsmondE are you working on this issue ?

**Comment by Akshay2004-701** [comment]
I am working in it

**Comment by PratyushSingh07** [comment]
closing this as completed
