### ISSUE TITLE
migrate finance screen to compose

### ISSUE THREAD

**Issue by UduakUmanah10** [openMF/mobile-wallet#1554]
Issue Summary:
==========
The current finance screen, drawn in XML, lacks responsiveness on Samsung Galaxy S10. The account screen, displaying a list of linked bank accounts, is non-scrollable, and the button component is compressed, diminishing user experience quality.

Steps to Reproduce:
=============
Launch the mobile wallet app on a Samsung Galaxy S10.
Navigate to the finance screen.

Expected Behavior:
=============

The account screen should display a scrollable list of linked bank accounts.
The button component should maintain proper formatting and not appear compressed.

Observed Behavior:
==============
The linked bank account list is non-scrollable.
The button XML component appears compressed, reducing user experience quality.
Device and Android Version:

manufacturers info
=============
Make and Model: Samsung Galaxy S10
Android Version: 12
Stock Android: True
Manufacturer Version: True

Screenshots:
============
![Screenshot (104)](https://github.com/openMF/mobile-wallet/assets/90254566/554380db-472b-4889-8ad2-d1ccd587f620)

**Comment by UduakUmanah10** [comment]
kindly assign this issue #1554 to me

**Comment by PratyushSingh07** [comment]
#1530 deals with the same thing @UduakUmanah10 . You might as well close this issue. 

Also look at the comment left in #1553
