### ISSUE TITLE
Migrate xml to Jetpack compose - payments/ui/RequestFragment

### ISSUE THREAD

**Issue by AbrahamOsmondE** [openMF/mobile-wallet#1571]
**Summary:**

Summarize your issue here.

**Steps to reproduce:**

How can we reproduce again the issue?

**Expected behavior:**

What did you expect the app to do?

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by AbrahamOsmondE** [comment]
@therajanmaurya I will be working on this now

**Comment by PratyushSingh07** [comment]
Hey @AbrahamOsmondE I have already raised the PR to this issue. Please check #1548

**Comment by AbrahamOsmondE** [comment]
Ahh I see, thanks for the reply. Didnt see the pull request

**Comment by PratyushSingh07** [comment]
closing this as a subpart of #1531
