### ISSUE TITLE
Issue when  cloning the app

### ISSUE THREAD

**Issue by Ej-leone** [openMF/mobile-wallet#16]
Error:(4, 0) Could not get unknown property 'RblClientIdProp' for project ':app' of type org.gradle.api.Project.
<a href="openFile:/home/Ej/Mosee/peet/mobile-wallet/app/build.gradle">Open File</a>

Any help would be gladly appreciated

**Comment by naman14** [comment]
@Ej-leone I have mentioned this in the wiki [here](https://github.com/openMF/mobile-wallet/wiki/Building-the-code)
You need to add RblClientIdProp and RblClientSecretProp as environment variables.
Alternatively, you can also add both variables in `gradle.properties` file

Add the following lines in `gradle.properties`
`RblClientIdProp=randomstring`
`RblClientSecretProp=randomstring`

Let me know if you are still facing problems building the project
