### ISSUE TITLE
App crashing on start

### ISSUE THREAD

**Issue by manddy** [openMF/mobile-wallet#161]
**Summary:**

The app crashes as soon as it launches but when run again it does not crashes
The terminal shows this error
 '' java.lang.NullPointerException: Attempt to invoke virtual method 'void org.mifos.mobilewallet.mifospay.data.local.PreferencesHelper.setFirebaseRegId(java.lang.String)' on a null object reference''

**Comment by luckyman20** [comment]
@manddy May I know the reason of closing this issue?

**Comment by RajaVamsi11** [comment]
@luckyman20 I also faced this issue while the first attempt. I solved the issue by checking the mPreferenceHelper is not null and now it works fine. Can I send a PR now?

**Comment by luckyman20** [comment]
@RajaVamsi11 Yeah, you can go ahead but please open another issue (somewhat detailed) and refer it in your PR.
