### ISSUE TITLE
Error while building the application

### ISSUE THREAD

**Issue by Sarthak9504** [openMF/mobile-wallet#1646]
**Summary:**

There is an error in the file EditPasswordScreen.kt inside the password package.
The issue is while calling the MifosScaffold Composable function where one of the parameters is the RowScope.() -> Unit. The error message is as follows: 
Type mismatch: inferred type is RowScope.(Any?) -> Unit but RowScope.() -> Unit was expected
Cannot infer a type for this parameter. Please specify it explicitly.
Expected no parameters 
there is one more error but it is not practical to put it here.

**Steps to reproduce:**

Try building the application.

**Expected behavior:**

The application should build smoothly without any error

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

Please help me with this I wanted to contribute to the project. I am not able to figure out what's the error. Thank you.

**Comment by PratyushSingh07** [comment]
Unable to replicate this. Try cleaning and then rebuilding the project

**Comment by Sarthak9504** [comment]
> Unable to replicate this. Try cleaning and then rebuilding the project

Hello, honestly I have tried a bunch of things cleaning, Invalidating caches and rebuilding but thats not working the error is associated with the MifosScaffold Composable. Also, its not only causing problem in the files I mentioned but a bunch of other files too. Here is a ss of the IDE.
![Screenshot 2024-06-03 005205](https://github.com/openMF/mobile-wallet/assets/130087140/3256ca1d-c042-4537-94f9-626bae4dba69)

**Comment by PratyushSingh07** [comment]
Just running the application should have worked.
If not then I think that  This can be fixed by explicitly encapsulating with scaffoldContent

**Comment by Sarthak9504** [comment]
I have recently updated the project so might be there have been made changes to the MifosScaffold Composable which are not considered in the other files where the function is used. Because there is also an error related to this parameter : 
actions: @Composable RowScope.() -> Unit = {}. Please can you confirm that everything's fine from your side I am trying since yesterday

**Comment by Sarthak9504** [comment]
@PratyushSingh07 Can you please check the files I have mentioned.

**Comment by PratyushSingh07** [comment]
I checked it yesterday, everything was fine from my end. Join the slack channel and maybe I'll get on a call with you tonight

**Comment by Sarthak9504** [comment]
Ohh, okay. I'll join  the channel. Thank you.
