### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by nb2998** [openMF/mobile-wallet#17]
**Summary:**

On entering the credentials,the progressDialog keeps loading or a Toast is displayed saying 'Error logging in'.

**Steps to reproduce:**

Enter the credentials mentioned in [Wiki](https://github.com/openMF/mobile-wallet/wiki) to login.

**Expected behavior:**

Should have logged in successfully.

@naman14 Could you please help? Is it a backend issue? Thanks!

**Comment by naman14** [comment]
@nb2998 The password was expired for both pixiepay and mifospay, I have disabled the password expiry on the backend. You can use following credentials for logging in - 
Pixie Pay - pixiepay, password
Mifos Pay - mifospay, password1
