### ISSUE TITLE
Adding add account button in finance tab

### ISSUE THREAD

**Issue by manddy** [openMF/mobile-wallet#171]
**Summary:**
Currently there is no add accounts button in the accounts fragment in finance tab

**Expected behavior:**
There should be a add account button

**Observed behavior:**
No add account button seen right now

**Comment by manddy** [comment]
@ankurs287  kindly assign me this

**Comment by codepoet2017390** [comment]
@manddy  what do you plan on implementing on clicking the Add accounts button?

**Comment by manddy** [comment]
@codepoet2017390  have a  look at the master branch code ,We have to implement a separate page for adding more accounts for users

**Comment by codepoet2017390** [comment]
@manddy yes but the master branch already has a functional add account screen existing and finally the redesign branch will be merged with master so i dont think you should implement the backend part again in the redesign and also button as an UI element was a part of the redesign issue https://github.com/openMF/mobile-wallet/issues/137
So i just wanted to know if u planned on doing something different on clicking the button

**Comment by manddy** [comment]
@codepoet2017390  we had actually divided the merchants and account section in 2 parts one for fetching and one for adding right now i have done the fetching part adding part is still left to implement and it is not only a backend part but requires different screens after clicking the button.Implementation part of the next window is still vague to me right now .
