### ISSUE TITLE
Change Passcode in edit profile

### ISSUE THREAD

**Issue by manddy** [openMF/mobile-wallet#172]
**Summary:**
Right now there is a button in edit profile to change passcode  in edit profile but it is not working

**Expected behavior:**
Steps to make it workable 

**Screenshots:**
![canvas](https://user-images.githubusercontent.com/22556185/50762537-38908a80-1293-11e9-8c02-44bc2004326b.png)

**Comment by manddy** [comment]
@ankurs287  kindly assign me this issue

**Comment by RajaVamsi11** [comment]
@manddy Can I work on this issue as this is inactive?

**Comment by nirmalhk7** [comment]
@manddy @RajaVamsi11 @ankurs287 Given that no PR has referred this issue yet, Can I work on this issue?

**Comment by luckyman20** [comment]
@nirmalhk7 Please tell your approach first. I guess this issue has some blocker related to library/API.
