### ISSUE TITLE
Updating the Readme of the project

### ISSUE THREAD

**Issue by codepoet2017390** [openMF/mobile-wallet#173]
**Summary:**
I will update the readme.md file of the project and make it more informative and presentable for first time contributors. The readme would also contain contribution guidelines and important links for contributing to the project.

![screenshot_20190113-174944](https://user-images.githubusercontent.com/37406965/51085243-86f2cd00-175c-11e9-9f5e-8a2324cfda4a.jpg)
![screenshot_20190113-175035](https://user-images.githubusercontent.com/37406965/51085245-8823fa00-175c-11e9-949a-c5292037b970.jpg)
![screenshot_20190113-175100](https://user-images.githubusercontent.com/37406965/51085246-89552700-175c-11e9-9a5b-5a85ecb5bfae.jpg)

![2019-01-13 7](https://user-images.githubusercontent.com/37406965/51078238-20c46680-16d8-11e9-82c7-4d457312fd2e.png)

**Comment by codepoet2017390** [comment]
@luckyman20  I would like to work on this

**Comment by luckyman20** [comment]
Work on only one issue at a time. I think you have already claimed one redesign issue.
