### ISSUE TITLE
Document the files in mifopay/auth package

### ISSUE THREAD

**Issue by ankurs287** [openMF/mobile-wallet#174]
**Summary:**
Document the files in mifospay/auth package: https://github.com/openMF/mobile-wallet/tree/master/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth

**Comment by PraneethVankayala** [comment]
@ankurs287 or @luckyman20 can u elaborate this issue

**Comment by PraneethVankayala** [comment]
@luckyman20 can I work on this issue

**Comment by luckyman20** [comment]
Yeah, sure. Please go ahead.
