### ISSUE TITLE
Document the files in mifopay/base package

### ISSUE THREAD

**Issue by luckyman20** [openMF/mobile-wallet#176]
**Summary:**

Document the files in mifopay/base package: https://github.com/openMF/mobile-wallet/tree/master/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base

**Comment by theamritanair** [comment]
@luckyman20 I would like to work on this issue.

**Comment by theamritanair** [comment]
@luckyman20 I would like to work on this issue.
