### ISSUE TITLE
Document the files in mifopay/common package

### ISSUE THREAD

**Issue by luckyman20** [openMF/mobile-wallet#177]
**Summary:**

Document the files in mifopay/common package: https://github.com/openMF/mobile-wallet/tree/master/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/common

**Comment by theamritanair** [comment]
@luckyman20 I would like to work on this issue.

**Comment by RajaVamsi11** [comment]
@theamritanair As  [this](https://github.com/openMF/mobile-wallet/issues/182) issue is assigned to you. @luckyman20 I would like to work on this issue.

**Comment by luckyman20** [comment]
@RajaVamsi11 Thanks for easing my work. Yes, you can go ahead. I hope you aren't working on any other issue.

**Comment by RajaVamsi11** [comment]
@luckyman20 I am on it. No, there are no issues assigned to me.
