### ISSUE TITLE
Document the files in mifopay/data package

### ISSUE THREAD

**Issue by luckyman20** [openMF/mobile-wallet#178]
**Summary:**

Document the files in mifopay/data package: https://github.com/openMF/mobile-wallet/tree/master/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data

**Comment by manddy** [comment]
@luckyman20  do we have to write comments in the code or make a separate document for it

**Comment by luckyman20** [comment]
Comment in the code.

**Comment by 991rajat** [comment]
@luckyman20 Is this issue still open? Can I work on this.
