### ISSUE TITLE
Document the files in mifopay/editprofile package

### ISSUE THREAD

**Issue by luckyman20** [openMF/mobile-wallet#179]
**Summary:**

Document the files in mifopay/editprofile package: https://github.com/openMF/mobile-wallet/tree/master/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile

**Comment by manddy** [comment]
@luckyman20 Kindly assign me this issue

**Comment by luckyman20** [comment]
Please go ahead.

**Comment by RajaVamsi11** [comment]
@luckyman20 @manddy Can I start working on this issue as manddy is inactive.

**Comment by RajaVamsi11** [comment]
Working on this issue.
