### ISSUE TITLE
No action on clicking the signup button

### ISSUE THREAD

**Issue by batbrain7** [openMF/mobile-wallet#18]
**Summary:**
On clicking the signup button on the login screen no action is performed.

**Steps to reproduce:**
Click on the sign up button on the login screen.
**Expected behavior:**
A new activity should open up asking for the details of a new user to sign up.
**Observed behavior:**
No action on clicking the button
**Device and Android version:**
Samsung Galaxy J2(2016) Android 6.0.1

**Comment by naman14** [comment]
@batbrain7 Can you explain the issue? You did not provide the necessary information. What do you mean by cl?

**Comment by batbrain7** [comment]
@naman14 I pressed enter by mistake while typing and incomplete issue was raised.

**Comment by batbrain7** [comment]
@naman14 I want to contribute to this issue.

**Comment by naman14** [comment]
Signup process is not feasible with the current backend system. There will have to be some changes to the Fineract platform to support user onboarding.
You can remove the signup button from Mifos Pay module and submit a pr. The signup button in PixiePay does move to some screens for collecting user information and account details

**Comment by batbrain7** [comment]
Okay, thanks.
