### ISSUE TITLE
Document the files in mifopay/kyc package

### ISSUE THREAD

**Issue by luckyman20** [openMF/mobile-wallet#183]
**Summary:**

Document the files in mifopay/kyc package: https://github.com/openMF/mobile-wallet/tree/master/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/kyc

**Comment by manddy** [comment]
@luckyman20  Can i work on this issue?

**Comment by luckyman20** [comment]
Yes, please go ahead.

**Comment by codepoet2017390** [comment]
@luckyman20 I would like to work on this
