### ISSUE TITLE
Document the files in mifopay/merchants package

### ISSUE THREAD

**Issue by luckyman20** [openMF/mobile-wallet#184]
**Summary:**

Document the files in mifopay/merchants package: https://github.com/openMF/mobile-wallet/tree/master/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants

**Comment by shiv07tiwari** [comment]
Hello @luckyman20 @ankurs287 
I would like to work on this and similar issues.
What guidelines you want me to follow ?
How exactly do you need the documentation?
