### ISSUE TITLE
Document the files in mifopay/qr package

### ISSUE THREAD

**Issue by luckyman20** [openMF/mobile-wallet#187]
**Summary:**

Document the files in mifopay/qr package: https://github.com/openMF/mobile-wallet/tree/master/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr

**Comment by codepoet2017390** [comment]
@luckyman20  can i work on this

**Comment by luckyman20** [comment]
@codepoet2017390 Work on only one issue at a time.
