### ISSUE TITLE
Document the files in mifopay/transactions package

### ISSUE THREAD

**Issue by luckyman20** [openMF/mobile-wallet#192]
**Summary:**

Document the files in mifopay/transactions package: https://github.com/openMF/mobile-wallet/tree/master/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/transactions

**Comment by nikhil-sachdeva** [comment]
Can I work on this? It'll help me understand the codebase better.

**Comment by RajaVamsi11** [comment]
As this is not assigned to anyone, you can start working on this @nikhil-sachdeva.
