### ISSUE TITLE
App crashes on clicking Send Button

### ISSUE THREAD

**Issue by batbrain7** [openMF/mobile-wallet#21]
**Summary:**

In the transfer fragment on clicking the send money button when Amount is not entered the app crashes.

**Steps to reproduce:**

Click on Transfer or Send or Request on wallet screen and then click on Send Money button without entering any amount.

**Expected behavior:**

App should prompt the user to enter the amount or not leave the required fields empty.

**Observed behavior:**

The app crashes on clicking the send money button

**Device and Android version:**

Samsung Galaxy J2(2016) Android Version : 6.0.1

**Comment by batbrain7** [comment]
May I rectify it @naman14 ?

**Comment by naman14** [comment]
@batbrain7 Sure, Feel free to work on the issue
