### ISSUE TITLE
User's profile picture upload fails

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#214]
**Summary:**

User's profile picture upload fails.

**Steps to reproduce:**

1. Go to profile activity
2. Click on Edit Profile
3. Change profile picture
4. Go back to profile activity

**Expected behavior:**

It should upload the picture.

**Observed behavior:**

Profile picture not uploaded

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0
.

**Comment by shaliniv16** [comment]
@luckyman20 can I work on this issue?

**Comment by luckyman20** [comment]
App is being re-designed and I think it is resovled in redesign branch. Can you please check and update?

**Comment by shaliniv16** [comment]
Yeah alright.

**Comment by shaliniv16** [comment]
@luckyman20 I am getting merge conflict in redesign branch.

**Comment by luckyman20** [comment]
Create the branch from `redesign` and then make the required changes and then send the PR.

**Comment by shaliniv16** [comment]
@luckyman20 The user's profile picture still fails to upload in redesign branch. The Save button in edit profile fragment is not working when I try to upload a profile picture. Can I work on this issue?

**Comment by RahulPrajapati97** [comment]
After selecting user profile image from storage there must be a button of save then user profile set and changes are reflected.

**Comment by Bhavnaharitsa** [comment]
@luckyman20 
@RahulPrajapati97 
@RajaVamsi11 
@shaliniv16 This feature is not implemented and I think, this issue stands invalid

**Comment by devansh-299** [comment]
Yes, I can still reproduce this issue.

**Comment by luckyman20** [comment]
@devansh-299 Do we have API for this?

**Comment by devansh-299** [comment]
> @devansh-299 Do we have API for this?

@luckyman20 The updating/uploading service has already been created but hasn't been used yet. I think using that service we can solve this issue.
Should I work on this?

![Screenshot from 2020-03-11 21-42-23](https://user-images.githubusercontent.com/46667021/76438692-569ad300-63e1-11ea-97dc-df9c10e4aabe.png)

**Comment by luckyman20** [comment]
In that case, go ahead!

**Comment by devansh-299** [comment]
> In that case, go ahead!

Thanks
