### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#216]
**Summary:**
Since AndroidX is released, we should migrate the support libraries to the androidx namespace.AndroidX maps the original support library API packages into the androidx namespace. Atleast migrate the stable libraries to the androidx namespace.

**Additional Context:**
Please refer this [link](https://developer.android.com/jetpack/androidx/migrate#migrate)

@luckyman20 @ankurs287 What do you think about this? I am interested in working on this issue?

**Comment by deepak-prajapatii** [comment]
@RajaVamsi11 can i work on this issue?

**Comment by devansh-299** [comment]
Closing this issue as #1012 solves the problem mentioned
