### ISSUE TITLE
Add ScrollView in login page

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#220]
**Summary:**
As of now, we are not able to scroll the login page.
When the user enters the username and password then he has to press back the keypad down and hit on login button. If there is scrolling he simply will scroll up and log in.

**Expected behavior:**
Login page must scroll up

**Observed behavior:**
There is no scrolling in login

**Device and Android version:**
Asus (Version 4.4.2)

**Screenshots:**
![screenshot_2019-01-18-22-37-55](https://user-images.githubusercontent.com/30550059/51401947-273c5d80-1b72-11e9-8f30-88ed0da5010c.jpg)

**Comment by luckyman20** [comment]
@RajaVamsi11 I think alternatively we can move the button a little bit up so that user can click the button even if keyboard is opened.

Also, do this for redesign branch.

**Comment by RajaVamsi11** [comment]
@luckyman20 I think moving the button a little up only solves the problem for some of the devices. Adding scroll view is better than changing the button because if we change the padding between the button and password text field the gap between them becomes less and it will affect the UI.
I added the scroll view in the login page. Just take a look at it.
I scrolled up to make the login button visible

![screenshot_2019-01-18-22-50-03](https://user-images.githubusercontent.com/30550059/51402732-4fc55700-1b74-11e9-9ab1-0d1d3816e2c2.jpg)

**Comment by RajaVamsi11** [comment]
@luckyman20 Can you tell me what should I implement now?

**Comment by luckyman20** [comment]
@RajaVamsi11 I get your point but this screen is static and not a list so there is no need of implementing ScrollView. Have you tried the padding solution on bigger devices?

**Comment by RajaVamsi11** [comment]
@luckyman20 I will try and inform you.

**Comment by RajaVamsi11** [comment]
@ankurs287 What do you think about this issue?

**Comment by RahulPrajapati97** [comment]
Is this issue is solved?

**Comment by RajaVamsi11** [comment]
@RahulPrajapati97 Adding scroll view in the static page is not necessary as @luckyman20 said.

**Comment by RahulPrajapati97** [comment]
@RajaVamsi11  .k
