### ISSUE TITLE
Problem in UI while setting up UPI PIN.

### ISSUE THREAD

**Issue by nikhil-sachdeva** [openMF/mobile-wallet#229]
**Summary:**

Since the width of PinEntryEditText is fixed(160dp), for smaller screens, the year text goes out of bounds.
**Steps to reproduce:**

Go to Banks, select an account, setup UPI

**Expected behavior:**

The Edit Text should be within the screen.

**Observed behavior:**

The last digit goes out of bounds.

**Device and Android version:**

Redmi Note 3
**Screenshots:**

![upi](https://user-images.githubusercontent.com/34986121/51489928-bd20f400-1dcf-11e9-8d56-5d6853544ecb.png)

**Comment by nikhil-sachdeva** [comment]
@luckyman20 can i work on this?

**Comment by luckyman20** [comment]
We can resolve this issue in the redesigning part.

**Comment by nikhil-sachdeva** [comment]
Should I make a PR to the redesign branch or is the UI changing completely in that branch?

**Comment by luckyman20** [comment]
See, when the UI will be redesigned, we will try to fix these small bugs too. Thank you for your contribution.
