### ISSUE TITLE
Fix lint warnings and errors

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#236]
**Summary:**
We have something like 454 lint warnings and errors in our whole project.

**Steps to reproduce:**
Open the project in Android studio and click
Analyze --> Inspect code ( Whole project ) 

**Expected behavior:**
We need to go through them and either fix and suppress them

**Screenshots:**

![screenshot from 2019-01-23 23-04-58](https://user-images.githubusercontent.com/30550059/51625831-2cc7e800-1f64-11e9-8ac7-591873de56a1.png)

**Comment by RajaVamsi11** [comment]
@therajanmaurya @luckyman20 I am going to fix the warnings if it can be fixed else I will suppress the warning. Can you please assign me the task so that I can start working on this issue.

**Comment by RajaVamsi11** [comment]
@luckyman20 Ok. I will start fixing the warnings.

**Comment by luckyman20** [comment]
Closing this because this is a very old issue and we might have different warnings and errors now.
