### ISSUE TITLE
App crashes while registering user

### ISSUE THREAD

**Issue by ThisIsNSH** [openMF/mobile-wallet#242]
**Summary:**

App crashes when registering in app. 

**Steps to reproduce:**

Click on create one (dont have an account, create one) button on login page 

**Expected behavior:**

Successfully register user.

**Observed behavior:**

App crashes

**Device and Android version:**

Redmi 3S Prime, Android 6

**Screenshots:**

Nil. App crashes on login screen.

**Comment by ThisIsNSH** [comment]
Please assign me this

**Comment by shaliniv16** [comment]
I can't find this issue.

**Comment by RajaVamsi11** [comment]
@shaliniv16 The app is crashing in my device (Android version 6.0.1, Redmi Note 3). I will attach the GIF today evening. You can take look at the GIF.

**Comment by RajaVamsi11** [comment]
@luckyman20 I am working on this issue and will send PR to night.
