### ISSUE TITLE
Java compiler error while building.

### ISSUE THREAD

**Issue by jddeep** [openMF/mobile-wallet#243]
**Summary:**
There is a Java compiler error which hinders the app during Runtime and the app crashes.

**Steps to reproduce:**
Build the application.

**Expected behavior:**
Build correctly and runs on the device.

**Observed behavior:**
The build shows error and the app crashes.

**Device and Android version:** Lenovo k8 Note, Android 8

**Screenshots:**
![screenshot 114](https://user-images.githubusercontent.com/43133646/51731872-4ec78480-20a2-11e9-971b-b7989526292b.png)
![screenshot 115](https://user-images.githubusercontent.com/43133646/51731892-5d15a080-20a2-11e9-942c-b556605b93fe.png)

I would like to work on the issue.

**Comment by codepoet2017390** [comment]
Looks like there is an issue with the project on your local machine as i'm not facing any issue like this.

**Comment by codepoet2017390** [comment]
Yes there is no FATAL exception either in dev or master. The project works fine for me. Try debugging through suggestions via android studio and if still error persists mentors and other community members are there to help :)

**Comment by jddeep** [comment]
@codepoet2017390 Okay then I will try running it again from the initial state of the project when I forked it and see if there is a problem. Will discuss on that if there is any I find again.....Thanks.

**Comment by jddeep** [comment]
Resolved locally.
