### ISSUE TITLE
The app crashes on start.

### ISSUE THREAD

**Issue by jddeep** [openMF/mobile-wallet#245]
**Summary:**
The app gets crashed just on start. This is similar to #161 

**Steps to reproduce:**
Run the app.

**Expected behavior:**
App to run.

**Observed behavior:**
App crashes.
![screenshot_20190125-131351](https://user-images.githubusercontent.com/43133646/51732189-7cf99400-20a3-11e9-8409-9cbd1b481b8f.png)

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

I would like to work on the issue. The issues #244 and #243 are related to the fix.

**Comment by luckyman20** [comment]
PR #163 is already there.
