### ISSUE TITLE
Redesign: TextInputEditText fields in EditProfile activity

### ISSUE THREAD

**Issue by codepoet2017390** [openMF/mobile-wallet#249]
**Summary:**

Presently the helper text becomes the EditText header when it is clicked.

**Steps to reproduce:**
1) Go to Profile and then Edit profile.
2) Click any of the EditText fields.  

**Expected behavior:**
Title headings such as Email, Name etc. should be the EditText headers.

**Device and Android version:**
OnePlus5 and Oreo 8.1

**Screenshots:**
![screenshot_20190125-194228](https://user-images.githubusercontent.com/37406965/51751985-42f8b400-20dc-11e9-9e0f-e9c12193aa92.jpg)

**Comment by codepoet2017390** [comment]
@luckyman20 @ankurs287  can i work on this?

**Comment by luckyman20** [comment]
@codepoet2017390 I hope you have checked this in `redesign` branch and not testing on `dev` branch for this issue.

**Comment by codepoet2017390** [comment]
Yes Yes i took care of that

**Comment by Bhavnaharitsa** [comment]
@luckyman20 Sir, I think this issue is solved in the dev branch and hence we can close this
