### ISSUE TITLE
No change in brightness on viewing QR Code

### ISSUE THREAD

**Issue by nb2998** [openMF/mobile-wallet#25]
**Summary:**

There is no change in brightness of device when QR Code is shown to the user.

**Steps to reproduce:**

Transfer -> Show Code

**Expected behavior:**

The brightness of device can be maximised when clicked on "Show Code" and returned to normal when pressed back.

Can I work on this? @naman14

**Comment by codepoet2017390** [comment]
@luckyman20 @naman14  Can i work on this?

**Comment by luckyman20** [comment]
@codepoet2017390 Please go ahead.
