### ISSUE TITLE
Error while Sign Up.

### ISSUE THREAD

**Issue by jddeep** [openMF/mobile-wallet#251]
**Summary:**
While Signing up an error message pops up as toast and hinders while registering.

**Steps to reproduce:**
Go to Sign up.
Enter mobile number and proceed.
Enter all details and proceed.
The error toast message pops up.

**Expected behavior:**
Sign up correctly.

**Observed behavior:**
the error toast message pops up.

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**
![screenshot_20190126-111948](https://user-images.githubusercontent.com/43133646/51783229-fa350f80-215c-11e9-8809-23131a1f4622.png)

**Comment by luckyman20** [comment]
I think there is someone already working on it, moreover I was thinking that we would work on it after it the sign up screen is redesigned.
