### ISSUE TITLE
No Email validator present in the Sign Up Details page. 

### ISSUE THREAD

**Issue by jddeep** [openMF/mobile-wallet#252]
**Summary:**There is no validation check for correct email while filling up details.

**Steps to reproduce:**
Go to Sign up.
Proceed.
enter details.

**Expected behavior:**
To have a validation check on  the email,

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

**Comment by jddeep** [comment]
@luckyman20 what do you think on this issue? I would like to work on this issue.

**Comment by ankurs287** [comment]
@jddeep Email validation method is already defined in mifospay.utils package.

**Comment by jddeep** [comment]
@ankurs287 But i did not see that implemented while i was Signing up.

**Comment by ankurs287** [comment]
@jddeep then call the method defined in mifospay.utils.ValidationUtils class

**Comment by luckyman20** [comment]
This issue can be taken up anyone now. Please comment here before you start working.

@s-ayush2903 tagging you since you asked on its closed PR.

**Comment by s-ayush2903** [comment]
Is there any plan to write the new code in Kt? As I found some kt libs. in the gradle files. If it is so then, am I allowed to change the file for textUtils to Kotlin as it is very small and won't require much efforts. 
Contrarily, if we change our mind later to write that file in kt. then by that time there would've been a lot of java stuff.

So what should I do now:- Just call that required function at the appropriate place or even change that function file to kt. as well?

Please Elaborate/Suggest

**Comment by s-ayush2903** [comment]
(Taking up this issue)

**Comment by luckyman20** [comment]
@s-ayush2903 can you please open up another issue for converting the file into Kotlin?

**Comment by s-ayush2903** [comment]
> @s-ayush2903 can you please open up another issue for converting the file into Kotlin?

#903 Has been opened considering the same
