### ISSUE TITLE
Replace String with StringBuilder

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#259]
**Summary:**
As we are using String for appending [here](https://github.com/openMF/mobile-wallet/blob/master/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/DebugUtil.java#L12) in `DebugUtil.java` and [here](https://github.com/openMF/mobile-wallet/blob/master/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/kyc/presenter/KYCLevel2Presenter.java#L66) in `KYCLevel2Presenter.java`. It is better to use StringBuilder as it is mutable. A string is immutable and when you invoke a method on String it creates a new object and returns it. My idea is to place String with StringBuilder.
Here is the [link](https://stackoverflow.com/questions/5234147/why-stringbuilder-when-there-is-string) for more explanation.
This type of issues will throw warnings which comes under Java --> Performance warnings.

**Comment by RajaVamsi11** [comment]
@luckyman20 @ankurs287 I would like to work on this issue.

**Comment by luckyman20** [comment]
Discussed in #268
