### ISSUE TITLE
Redesign: Use TextInputLayout instead of EditText

### ISSUE THREAD

**Issue by nikhil-sachdeva** [openMF/mobile-wallet#260]
**Summary:**
In activity_signup.xml EditTexts are used. TextInputLayouts are more informative and goes in accordance with the Login Page layout.

**Steps to reproduce:**

Create an account either as merchant or customer, verify mobile number.

**Device and Android version:**

Redmi Note 3

**Screenshots:**

![screenshot_2019-01-27-22-44-08-086_org mifos mobilewallet mifospay](https://user-images.githubusercontent.com/34986121/51804375-f355ec00-2285-11e9-8272-c694f64aed03.png)

**Comment by nikhil-sachdeva** [comment]
@luckyman20 Can I work on this? This is in the redesign branch.

**Comment by devansh-299** [comment]
Closing this as this issue has already been addressed
