### ISSUE TITLE
Redesign: It's taking two clicks to switch between Mobile Number and VPA in Select transfer method

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#263]
**Summary:**

Redesign: It's taking two clicks to switch between Mobile Number and VPA in Select transfer method, this problem occurs in the second time.

**Steps to reproduce:**

- Go to Payments Activity
- Click on Mobile Number
- Click on VPA
- Again click on Mobile Number

**Expected behavior:**

It should open Mobile Number option.

**Observed behavior:**

Nothing happen. We have to click again to open Mobile Number option.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Comment by shaliniv16** [comment]
@luckyman20 please review.

**Comment by shaliniv16** [comment]
@luckyman20 I am facing this issue in both redesign and master branch. Can you please confirm it?

**Comment by rchtgpt** [comment]
@shaliniv16 This issue is already fixed.
