### ISSUE TITLE
Redesign: On clicking Change Passcode nothing is shown.

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#264]
**Summary:**

Redesign: On clicking Change Passcode nothing is shown.

**Steps to reproduce:**

- Go to Profile Activity
- Click on Edit Profile
- Click on Change Passcode

**Expected behavior:**

Change Passcode option should be open up.

**Observed behavior:**

Nothing happened.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Comment by shaliniv16** [comment]
@luckyman20 may I work on it?

**Comment by RajaVamsi11** [comment]
@shaliniv16 In which branch are you facing this problem?

**Comment by shaliniv16** [comment]
@RajaVamsi11 on redesign branch. I am currently working on this issue.

**Comment by devansh-299** [comment]
@shaliniv16 @luckyman20 @shiv07tiwari can I work on this issue?

**Comment by shiv07tiwari** [comment]
@devansh-299 This will be implemented when the change passcode option is available.

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 This will be implemented when the change passcode option is available.

Can I work on implementing the change passcode functionality? I have already worked on a similar functionality for Mifos Mobile
