### ISSUE TITLE
Scroll function is not available on screen rotation

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#272]
**Summary:**

In the redesign branch, the scroll function is not available on screen rotation

From the home screen, enable screen rotation

**Expected behavior:**

It should show all the options available.

**Observed behavior:**

![videotogif_2019 02 05_07 02 21](https://user-images.githubusercontent.com/32845033/52248425-601b5700-2914-11e9-8b72-cdc49cfdd2e0.gif)

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Comment by shaliniv16** [comment]
@luckyman20 can I work on it?

**Comment by luckyman20** [comment]
Same reason for closing this as issue #273
