### ISSUE TITLE
Add scroll bar to Trusted Merchants screen and Link Bank Account screen

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#275]
**Summary:**

As a user,
I need scroll bar on Trusted Merchants screen and Link Bank Account screen,
so that I can be aware of the list length.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Screenshots**

![videotogif_2019 02 06_20 31 07](https://user-images.githubusercontent.com/32845033/52350613-fce20f80-2a4e-11e9-8c64-a1a38d92651c.gif)

![videotogif_2019 02 06_20 31 44](https://user-images.githubusercontent.com/32845033/52350648-0e2b1c00-2a4f-11e9-8ff0-b0d4efa60b0c.gif)

**Comment by shaliniv16** [comment]
@luckyman20 can I work on it?

**Comment by luckyman20** [comment]
@shaliniv16 In which branch you are facing this issue.?

**Comment by shaliniv16** [comment]
@luckyman20 In master branch.

**Comment by luckyman20** [comment]
@shaliniv16 Please check this in redesign branch. We should focus on UI related issues in redesign branch only.

**Comment by shaliniv16** [comment]
@luckyman20 Same issue with redesign branch too.

**Comment by luckyman20** [comment]
@shaliniv16 Go ahead but the scrollbar should follow the material design guidelines.
