### ISSUE TITLE
Create About screen

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#276]
**Summary:**

As a user of the system,
I need to see more info about the app,
so that I can better understand its origins.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Comment by shaliniv16** [comment]
@luckyman20 Can I work on it?

**Comment by luckyman20** [comment]
I don't think it is very necessary to add this in a payment app. If you can come up with a reason, reopen the issue.
