### ISSUE TITLE
Create confirmation dialog to logout from the app

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#277]
**Summary:**

As a user of Mobile Wallet,
I need to have an extra step to log out from the app,
so that I can be sure of the action I'm choosing.

**Comment by shaliniv16** [comment]
@luckyman20 Can I work on it?

**Comment by RajaVamsi11** [comment]
@shaliniv16 I am interested in adding this feature. Can I work on this issue as you are busy with solving other issues?

**Comment by shaliniv16** [comment]
@RajaVamsi11 I am waiting for mentor to reply on this issue.

**Comment by Bhavnaharitsa** [comment]
@luckyman20 @shiv07tiwari This issue is solved too

**Comment by luckyman20** [comment]
@Bhavnaharitsa Thank you for the heads up!
