### ISSUE TITLE
Hide Popular Bank when search is pressed.

### ISSUE THREAD

**Issue by prajurock** [openMF/mobile-wallet#279]
**Summary:**

Hide the Popular Bar view when search bar is editable

**Steps to reproduce:**

1.Invisible the popular screen view when the search is pressed

**Device and Android version:**
Asus Zenfone MAx m1 pro Android 8.1 (API 27)

**Branch**
Latest Mater

**Screenshots:**

![whatsapp image 2019-02-07 at 11 43 41 pm](https://user-images.githubusercontent.com/26791135/52433104-448d9780-2b32-11e9-8b5c-c15156ed109f.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by prajurock** [comment]
@luckyman20 @ankurs287

**Comment by RahulPrajapati97** [comment]
@prajurock  yes When search is pressed popular bank should hide and if bank is not present then these should give one screen of No Bank Available

**Comment by prajurock** [comment]
Yes. I am not working on this.anyone can take this issue.

**Comment by shaliniv16** [comment]
I am working on this.

**Comment by prajurock** [comment]
ok.sure

**Comment by RahulPrajapati97** [comment]
@prajurock Can I work On this?

**Comment by RahulPrajapati97** [comment]
@prajurock I have solve this issue.

**Comment by luckyman20** [comment]
Solved in #466
