### ISSUE TITLE
Changing password

### ISSUE THREAD

**Issue by manddy** [openMF/mobile-wallet#280]
**Summary:**
In the edit profile when the the change password section is opened and save button is clicked without filling any field it say incorrect password,Although it should be showing complete all fields message

**Comment by manddy** [comment]
@ankurs287  kindly let me work on this

**Comment by shaliniv16** [comment]
@manddy this issue is being resolved in redesign branch

**Comment by manddy** [comment]
@shaliniv16 
Thanks for telling me ,closing it right now
