### ISSUE TITLE
Kyc Levels

### ISSUE THREAD

**Issue by manddy** [openMF/mobile-wallet#284]
**Summary:**
In the kyc tab on selecting one level of kyc the other kyc levels apart from the next kyc level be disabled.

What did you expect the app to do?
The order of the kyc levels be corrected

**Comment by manddy** [comment]
@ankurs287  kindly let me work on this

**Comment by RajaVamsi11** [comment]
@manddy You are proposing to disable the other two kyc levels when the user is working on one kyc level right. If this was your issue then it was solved in redesign branch. Please take a look at there. For your convenience, I am attaching a screenshot of kyc level fragment of redesign branch. 
![screenshot_2019-02-15-14-30-48](https://user-images.githubusercontent.com/30550059/52846066-a9e31900-312e-11e9-8b89-5e7945b0ab36.png)

**Comment by manddy** [comment]
@RajaVamsi11 yes I know this thing we have change this in the master branch also  apart from the redesign

**Comment by RajaVamsi11** [comment]
@manddy If an issue is solved in any one of the branches, it is not necessary to solve that in other branches. This type of issues will be solved when mentors merge the branches. Hope you understand.
@luckyman20 What are your views on this?

**Comment by luckyman20** [comment]
@RajaVamsi11 You are right, our main goal is to get everything correct at the time of release.
