### ISSUE TITLE
Keyboard should be disappear on toggling between Virtual Payment Address and Mobile Number

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#287]
**Summary:**

Keyboard should be disappear on toggling between Virtual Payment Address and Mobile Number, in Payments Activity.

**Steps to reproduce:**

- Go to Payments Activity
- Click on Virtual Payment Address
- Click on Mobile Number

**Expected behavior:**

The keyboard should disappear

**Observed behavior:**

The keyboard didn't disappear.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Screenshots:**

![videotogif_2019 02 11_14 23 49](https://user-images.githubusercontent.com/32845033/52553620-1649d980-2e0a-11e9-87fa-e986c5b94d83.gif)
.

**Comment by shaliniv16** [comment]
@ankurs287 @luckyman20 Can I work on it?

**Comment by luckyman20** [comment]
@shaliniv16 Go ahead.

**Comment by devansh-299** [comment]
@luckyman20 can I work on this issue?

**Comment by haran2248** [comment]
Can i work on this issue?
@luckyman20

**Comment by luckyman20** [comment]
@haran2248 If it still exists, you may.

**Comment by MaskedCarrot** [comment]
This issue is not yet resolved. Can I work on it?

**Comment by luckyman20** [comment]
I believe @haran2248 isn't working anymore since @haran2248 hasn't replied to this thread. In that case, @Masked-Carrot, you may. But whoever creates the pull request first would be acknowledged.

**Comment by sachin-0102** [comment]
The issue is still open, Can I work on it?

**Comment by rchtgpt** [comment]
> The issue is still open, Can I work on it?

sorry, there's already a PR for it.

**Comment by AniketNS** [comment]
Hey @shaliniv16, can you assign this issue to me? I want to work on this issue.

**Comment by luckyman20** [comment]
Fixed in #1026
