### ISSUE TITLE
The app doesn't let me set the Passcode once I have entered the app if I skip in the beginning

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#295]
**Summary:**

The app doesn't let me set the Passcode once I have entered the app if I skip the Passcode setting process in the beginning.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Comment by shaliniv16** [comment]
@luckyman20 @ankurs287

**Comment by luckyman20** [comment]
Issue title could be better. Also, please explain why it is not accepting passcode. This might be the issue of the library.

**Comment by luckyman20** [comment]
Closing this because of unresponsiveness.
