### ISSUE TITLE
Wrong type of keyboard is appearing on clicking on the text field for Mobile Number

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#296]
**Summary:**

Wrong type of keyboard is appearing on clicking on the text field for Mobile Number

**Steps to reproduce:**

Go to Payments Activity
Click on Mobile Number

**Expected behavior:**

On clicking the Text field for `Mobile Number` Numeric keyboard will appear.

**Observed behavior:**

On clicking the Text field for `Mobile Number` Alphanumeric keyboard will appear. (Where Mobile Number can only be a numeric value.)

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Screenshots:**

![screenshot_2019-02-13-08-27-01-70 1](https://user-images.githubusercontent.com/32845033/52683640-7014e580-2f69-11e9-8322-ce46caccdd83.png)

![screenshot_2019-02-13-08-44-05-52 1](https://user-images.githubusercontent.com/32845033/52684244-9cc9fc80-2f6b-11e9-80a0-bf866cde6b62.png)

**Comment by shaliniv16** [comment]
@ankurs287 @luckyman20 Can I work on it?

**Comment by luckyman20** [comment]
I see that it is a numeric keyboard only. Try installing GBoard to get clear insights.

**Comment by shaliniv16** [comment]
@luckyman20 The numeric keyboard won't show even after installing GBoard.

**Comment by codepoet2017390** [comment]
@shaliniv16  it works fine for me.
 there might be minor settings changes to be done on your device.

**Comment by RajaVamsi11** [comment]
@shaliniv16 It works fine for me too.

**Comment by luckyman20** [comment]
@shaliniv16 Enough of the opinions to close this. Thank you very much for your contribution, we do appreciate it.

**Comment by shaliniv16** [comment]
@codepoet2017390 @RajaVamsi11 Can you please send me the screenshots of the numeric keyboard appearing, while entering Mobile Number in Send Fragments.

**Comment by shaliniv16** [comment]
@luckyman20 As mentioned in #332  someone else also found this issue. Can you please reopen it?

**Comment by luckyman20** [comment]
Your issue is entirely different, include this bug in issue #318 and then solve it.

**Comment by shaliniv16** [comment]
@luckyman20 okay
