### ISSUE TITLE
The keyboard doesn't slide back down after clicking on the save option

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#299]
**Summary:**

The keyboard doesn't slide back down after clicking on the save option after editing in the text field in Edit Profile fragament

**Steps to reproduce:**

Go to Profile Activity
Click on Edit text in any field, edit something
Click on save button

**Expected behavior:**

Keyboard should slide down

**Observed behavior:**

The keyboard is not sliding down

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Screenshots:**

![videotogif_2019 02 13_16 22 28 1](https://user-images.githubusercontent.com/32845033/52706541-a83d1800-2fab-11e9-989b-c4a01faa98a2.gif)

**Comment by shaliniv16** [comment]
@luckyman20 Can I work on it?

**Comment by rchtgpt** [comment]
fixed in #627
