### ISSUE TITLE
There should be a limit of 4 digits on changing Passcode in Edit Profile 

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#300]
**Summary:**

There should be a limit of 4 digits on changing Passcode in Edit Profile, since the app only allows a 4 digit pin to be entered while opening the app

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Screenshots:**

![screenshot_2019-02-13-17-01-39-73 1](https://user-images.githubusercontent.com/32845033/52708876-4089cb80-2fb1-11e9-81f1-12a486ab4547.png)

**Comment by PraneethVankayala** [comment]
@luckyman20 I will work on this issue

**Comment by shaliniv16** [comment]
@PraneethVankayala I am already working on it.

**Comment by PraneethVankayala** [comment]
@shaliniv16 ok

**Comment by luckyman20** [comment]
@shaliniv16 We can change its design too. Instead of simple TextField, something more interactive and user-friendly should be implemented.

**Comment by shaliniv16** [comment]
@luckyman20 Can I work on its design?

**Comment by luckyman20** [comment]
This issue doesn't exists anymore because change passcode functionality isn't implemented yet.
