### ISSUE TITLE
Redesign : UI of buttons in SettingsActivity

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#301]
**Summary:**

The buttons ( Disable Account and Logout ) in settings activity looks odd. The buttons are not constrained to left and right. The text color of the disable account button is dark which is being mixed with the color of the button.

**Steps to reproduce:**

Open the app and go to settings activity.

**Expected behavior:**

UI of the buttons must be changed.

- Buttons should constrained to left and right of the parent view.

- We have to change the text color of the disable account button to white.

**Device and Android version:**
Device : Samsung Galaxy S5 
Android Version : 6.0.1

**Screenshots:**
**Before:**
![screenshot_2019-02-13-19-11-00](https://user-images.githubusercontent.com/30550059/52718229-00cede00-2fc9-11e9-9020-639cf6e68949.png)
**After Changes**
![screenshot_2019-02-13-19-29-07](https://user-images.githubusercontent.com/30550059/52718267-10e6bd80-2fc9-11e9-8393-cf63ba90d1d9.png)

**Comment by RajaVamsi11** [comment]
@luckyman20 Can I proceed with this issue?

**Comment by luckyman20** [comment]
This issue persists in redesign branch too?

**Comment by RajaVamsi11** [comment]
@luckyman20 I am talking about Redesign branch. What should I do now? Solve in two branches or in Redesign branch.

**Comment by luckyman20** [comment]
Go ahead with solving this in redesign branch only.

**Comment by RajaVamsi11** [comment]
ok

**Comment by RajaVamsi11** [comment]
Closing this as it is solved in #302.
