### ISSUE TITLE
Change the design of SignUp Activity   

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#305]
**Summary:**
Presently, sign up activity uses simple EditText fields. Instead of them, we can use TextInputEditText fields which are being used in the login activity to increase user interface of the app. Parent layout can be changed to Constraint layout and make changes in design according to it. Making these changes will be more interactive and user-friendly.

**Screenshots:**
**SignUp Layout**
![screenshot_2019-02-14-00-05-50](https://user-images.githubusercontent.com/30550059/52772830-7f765a80-305f-11e9-9e3f-d8d21584bd5d.png)
**Login Layout**
![screenshot_2019-02-14-13-13-21](https://user-images.githubusercontent.com/30550059/52772846-88ffc280-305f-11e9-8cee-cce3985ecbfd.png)

**Comment by RajaVamsi11** [comment]
@luckyman20 Can I start working on this issue.

**Comment by RajaVamsi11** [comment]
@luckyman20 Can I work on it?

**Comment by RajaVamsi11** [comment]
@luckyman20 Can I work on it?

**Comment by luckyman20** [comment]
Work on this in redesign branch.

**Comment by RajaVamsi11** [comment]
@luckyman20 Ok.

**Comment by DhaneshShetty** [comment]
@luckyman20  @rachittt Can I work on it?
