### ISSUE TITLE
There should be a limit of digits while entering Mobile Number

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#306]
**Summary:**

There should be a limit of digits while entering Mobile Number, in Edit Profile. We only have 10 digit mobile numbers in India, and every country has its own defined number of digits in Mobile Number.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Screenshots:**

![screenshot_2019-02-14-18-24-35-28 1](https://user-images.githubusercontent.com/32845033/52788132-06d6c480-3086-11e9-9830-b4419d84e295.png)

![screenshot_2019-02-14-18-24-52-07 1](https://user-images.githubusercontent.com/32845033/52789884-23293000-308b-11e9-9bc6-75e289bc244f.png)

**Comment by shaliniv16** [comment]
@luckyman20 Can I work on it?

**Comment by luckyman20** [comment]
Yeah, you can go ahead.

**Comment by shaliniv16** [comment]
@luckyman20 This issue is resolved in redesign branch.

**Comment by luckyman20** [comment]
@shaliniv16 Should be solved in dev branch.

**Comment by shaliniv16** [comment]
This issue is not present in dev branch.
