### ISSUE TITLE
There should be a limit of digits while entering Mobile Number in Send Fragment

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#310]
**Summary:**

There should be a limit of digits while entering Mobile Number in Send Fragment.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Screenshots:**

![videotogif_2019 02 15_09 17 35 1](https://user-images.githubusercontent.com/32845033/52833523-18aa7d00-3103-11e9-986b-8209a6bdd691.gif)

**Comment by shaliniv16** [comment]
@luckyman20 This issue is present both in redesign as well as master branch

**Comment by luckyman20** [comment]
@shaliniv16 Solve it in dev branch.

**Comment by codepoet2017390** [comment]
@shaliniv16  are u working on this

**Comment by shaliniv16** [comment]
Yes

**Comment by luckyman20** [comment]
Solved in #629
