### ISSUE TITLE
App crashing on trying to signup with Google as a Customer

### ISSUE THREAD

**Issue by rohap97** [openMF/mobile-wallet#316]
**Summary**
App crashes on trying to signup with Google Account as a Customer

**Steps to reproduce:**

How can we reproduce again the issue?
1. On Login Screen, Create one account
2.  Then click on Customer in "Sign up as"
3. Choose your account to continue to Mifos pay
4. On selecting the account the App crashes.

**Expected behavior:**

The Sign up process should have been completed.

**Observed behavior:**

App crashed

**Device and Android version:**

Device: Lenovo Vibe K5 Note
Android Version: Android 6.0 Marshmallow

**Comment by shaliniv16** [comment]
@rohap97 It works fine for me.

**Comment by RahulPrajapati97** [comment]
When i am try to sign in with google it give me Error of  "Goggle Sign In Fail " in android version 6,7,8,9 .
All device get this error and otp also not working.

**Comment by RahulPrajapati97** [comment]
When I am try to log in with google in device J7 prime android version 6,Moto G5 android version 7,MI Y2 android version 8 and Nokia 6.1 android version 9 all device have error of "Google Sign In Failed"

**Comment by Bhavnaharitsa** [comment]
@luckyman20 @shiv07tiwari @naman14 I think this issue is not valid as the app doesn't crash but the google login fails
