### ISSUE TITLE
Account column in Transfer fragment should accept up to 2 decimal digits in the amount

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#318]
**Summary:**

Account column in Transfer fragment should accept up to 2 decimal digits in the amount 

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Comment by shaliniv16** [comment]
@luckyman20 please verify this issue.

**Comment by luckyman20** [comment]
Why the amount length should not be greater than 7. Please explain.

**Comment by shaliniv16** [comment]
@luckyman20 Amount should not be greater than the 10 lakhs or the barrier you have set on the transfer amount.

**Comment by luckyman20** [comment]
For now, we do not have such barriers. Remove that part from the issue desc. and start working on it.
