### ISSUE TITLE
The User Name or User Mobile Number should appear in place of Mifos when Submit option is Clicked on, in the Send Fragment

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#320]
**Summary:**

The `User Name` or `User Mobile Number` should appear in place of` Mifos` when `Submit` option is Clicked on, in the Send Fragment

**Device and Android version:**

Device Realme 2 Pro
Android version 8.1.0

**Screenshots:**

![screenshot_2019-02-16-16-35-42-29](https://user-images.githubusercontent.com/32845033/52899851-dec99b80-3214-11e9-9959-31d2a86570aa.png)

**Comment by shaliniv16** [comment]
@luckyman20 Please verify this issue.

**Comment by luckyman20** [comment]
I think this is the username in this case. Please confirm this.

**Comment by haran2248** [comment]
Can i take the issue up?Is it still relevant?

**Comment by devansh-299** [comment]
Payee's `username` and `externalId` are already being shown. This issue is not relevant anymore, hence closing this issue.
