### ISSUE TITLE
Alphabetical order is missing in Trusted Merchants

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#323]
**Summary:**
.
Alphabetical order is missing in Trusted Merchants

**Device and Android version:**

Device Real Me 2
Android Version 8.1.0

**Screenshots:**

![videotogif_2019 02 17_09 11 14](https://user-images.githubusercontent.com/32845033/52908083-4d017300-3294-11e9-87bb-8afc547521f2.gif)

**Comment by shaliniv16** [comment]
@luckyman20 Please verify this issue.

**Comment by luckyman20** [comment]
Go ahead.
