### ISSUE TITLE
Add a confirmation dialog in forgot pin.

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/mobile-wallet#327]
**Summary:**

When user clicks on forgot pin, he is directed to login page.

**Expected behavior:**

He should get a confirmation dialog.

**Comment by shiv07tiwari** [comment]
@luckyman20 Can I work on this ?

**Comment by luckyman20** [comment]
I don't think that the user should be given an option to enter the pin again, that would be quite annoying for the user. 

If you can tell a real-life application which is doing that please let me know.

**Comment by shiv07tiwari** [comment]
![img_20190219_181352](https://user-images.githubusercontent.com/38163725/53015974-619b6200-3472-11e9-862f-05cef35bffa9.jpg)

I was thinking about adding this kind of feature, where its in the hand of user to select the login type.
Its the screenshot of Windows login screen.

**Comment by luckyman20** [comment]
Alternatively, what we can do is that we can show a confirmation dialog.

**Comment by shiv07tiwari** [comment]
Yes that is also fine.
But IMO this feature will look good on the login screen, as well as provide a dynamic user experience to the user.

**Comment by Bhavnaharitsa** [comment]
@shiv07tiwari Are we still working on this issue or is this even a valid issue?
