### ISSUE TITLE
Central alignment issues in Send Fragment

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#329]
**Summary:**

In Send fragment, the `Mobile Number` text and the `SUBMIT` button is not centrally aligned.

**Steps to reproduce:**

Go to Home --> Payments --> Send fragment

**Expected behavior:**

The Mobile Number text and the SUBMIT button must be centrally aligned.

**Observed behavior:**

The Mobile Number text and the SUBMIT button are not centrally aligned.

**Device and Android version:**

Device : Samsung Galaxy s1
Andoid Version: 6.0.1
**Screenshots:**
![screenshot_2019-02-15-14-49-43](https://user-images.githubusercontent.com/30550059/53109467-f2e80280-355e-11e9-851f-1664b2a1b9c3.png)

**Comment by RajaVamsi11** [comment]
@luckyman20 I am working on this issue.

**Comment by luckyman20** [comment]
Fixed in #330
