### ISSUE TITLE
Amount doesnt accept decimal and Phone number can be decimal in Send

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/mobile-wallet#332]
**Summary:**

Amount doesnt accept decimal and Phone number can be decimal in Send, which is logically wrong and might lead to bugs.

**Steps to reproduce:**

Send Fragment -> amount -> phone no
![videotogif_2019 02 21_07 56 02](https://user-images.githubusercontent.com/38163725/53139187-db386a80-35ae-11e9-90ff-a08dc7bce696.gif)

**Comment by shaliniv16** [comment]
@shiv07tiwari @luckyman20 This issue is already opened in #318 and #296.

**Comment by shiv07tiwari** [comment]
@shaliniv16 Sorry i didn't see that. But I guess their is no PR for both the issues , right ?
This PR simultaneously solves both the issues.

**Comment by shaliniv16** [comment]
@shiv07tiwari I am working on these issues.

**Comment by luckyman20** [comment]
@shaliniv16 Yeah right, I also had this feeling that someone else has already opened this issue but was not able to find it. Thank you!
