### ISSUE TITLE
Add reCaptcha

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/mobile-wallet#336]
**Summary:**

We can add captcha to improve the security in a sensitive app like a walket.
Similar to https://github.com/openMF/mifos-mobile/issues/844

**Comment by shiv07tiwari** [comment]
@luckyman20 Can i work on this feature?

**Comment by luckyman20** [comment]
Can you suggest an example for the same?

**Comment by shiv07tiwari** [comment]
@luckyman20 Example as in a real life example ? 
openMF/mifos-mobile#844 their was a discussion regarding this on mifos mobile, and i think we can adf this feature here as well.

**Comment by luckyman20** [comment]
Yes, a real-life example.

**Comment by shiv07tiwari** [comment]
@luckyman20 their is no real life app in my knowledge.
The mifos mobile discussion was the only reference i got.

**Comment by luckyman20** [comment]
Let's first discuss in the community and then we will implement it.

**Comment by shiv07tiwari** [comment]
Yes Sure. We gonna discuss it on gitter ?

**Comment by luckyman20** [comment]
Here only. Although you can share the link of the issue and ask for opinions (on gitter).

**Comment by shiv07tiwari** [comment]
Okay sure.

**Comment by naman14** [comment]
There's no need to add reCaptcha on a mobile app, that's just bad user experience.
