### ISSUE TITLE
Grammatical mistake is there in Readme file

### ISSUE THREAD

**Issue by atm1504** [openMF/mobile-wallet#339]
**Summary:**
Inside "Building to Code" section there is grammatical error.

**Steps to reproduce:**
By editing the file.

**Expected behavior:**
Browse to the directory where you have cloned the mobile-wallet repo and click OK.

**Observed behavior:**

Browse to the directory where you cloned the mobile-wallet repo and click OK.
<img width="1324" alt="screenshot 2019-02-22 at 8 43 52 pm" src="https://user-images.githubusercontent.com/43731599/53251410-97df1880-36e2-11e9-9704-83aad4a1691b.png">

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by atm1504** [comment]
I am working on it.

**Comment by luckyman20** [comment]
Fixed in #343
