### ISSUE TITLE
Spelling mistake is there in ISSUE_TEMPLATE file

### ISSUE THREAD

**Issue by atm1504** [openMF/mobile-wallet#341]
**Summary:**
"Behaviour" is misspelled in ISSUE_TEMPLATE file 

**Steps to reproduce:**
 Correcting the spelling.

**Expected behavior:**
The spelling should be "behaviour".

**Observed behavior:**
The current spelling is "behavior".

**Comment by atm1504** [comment]
I am working on it

**Comment by luckyman20** [comment]
Invalid issue. Reason mentioned on PR #342
