### ISSUE TITLE
Cloning url is wrong in readme file

### ISSUE THREAD

**Issue by atm1504** [openMF/mobile-wallet#344]
**Summary:**
The cloning url written is wrong. The branch name should be dev not development.
**Steps to reproduce:**

By editing the file

**Expected behavior:**

the url should be "git clone -b dev --single-branch https://github.com/username/mobile-wallet.git"

**Observed behavior:**

Url observed "git clone -b development --single-branch https://github.com/username/mobile-wallet.git"

**Comment by luckyman20** [comment]
Fixed in #345
