### ISSUE TITLE
Setting emptyview if there is no data to display.

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#346]
**Summary:**

Currently, there is no empty view present in Notifications and many activities if there is no data to display. It's a good practice to put an empty view if there is no data present.

**Device and Android version:**

Device Real Me 2
Android Version 8.1.0

**Comment by jasnasuresh** [comment]
@shaliniv16 are you working on this issue? If not, can I send a PR on the fix I created yesterday on issue #347 for this one?

**Comment by shaliniv16** [comment]
@jasnasuresh Yes, I am working on this issue. The PR I am sending is not only for Notifications activity but also for other activities.

**Comment by jasnasuresh** [comment]
@shaliniv16 Oh that's cool :)

**Comment by shaliniv16** [comment]
@luckyman20 In which branch should I solve this problem?

**Comment by RajaVamsi11** [comment]
@shaliniv16 As this is UI related issue, you should work on redesign branch.

**Comment by luckyman20** [comment]
Solved in #494
