### ISSUE TITLE
Notifications activity does not display any message when there are no notifications

### ISSUE THREAD

**Issue by jasnasuresh** [openMF/mobile-wallet#347]
**Summary:**

Notifications activity does not display any message when there are no notifications to be displayed. 

**Steps to reproduce:**

- Login to the application
- Click on Notifications

**Expected behavior:**

There should be some message on the screen when there are no notifications to be displayed.

**Observed behavior:**

The Notifications activity shows a blank screen.

**Device and Android version:**

Device:Redmi Note 5 Pro
Android version:8.1.0

**Screenshots:**

![photo_2019-02-22_18-57-48](https://user-images.githubusercontent.com/43848691/53259702-bbf82500-36f5-11e9-8f49-3e095eceb739.jpg)

**Comment by jasnasuresh** [comment]
I would like to work on this issue.

**Comment by shaliniv16** [comment]
@luckyman20 @jasnasuresh I have already opened this issue in #346

**Comment by luckyman20** [comment]
@jasnasuresh @shaliniv16 is right. Thank you for your contribution

**Comment by jasnasuresh** [comment]
@shaliniv16 @luckyman20 sorry for not noticing. Will take care next time..Can this fix be implemented in issue #346 as it has already been made?
