### ISSUE TITLE
No validation while verifying DebitCard

### ISSUE THREAD

**Issue by nikhil-sachdeva** [openMF/mobile-wallet#352]
**Summary:**
Currently, there is no validation for DebitCards while this method receives Card Number, Year and Month of the card.
~~~ java
@Override
    public void verifyDebitCard(String s, String s1, String s2) {
        String otp = "0000";
        mDebitCardView.verifyDebitCardSuccess(otp);
//        String message = "error";
//        mDebitCardView.verifyDebitCardError(message);
    }
~~~
**Steps to reproduce:**

Add a Debit Card
**Expected behavior:**
There should at least be length validators, if not card number validators.
The length of a payment card number can be anything between 12 and 19(mostly 16). [Reference](https://en.wikipedia.org/wiki/Payment_card_number)
**Observed behavior:**

No validation.

**Device and Android version:**

Redmi Note 3

**Comment by nikhil-sachdeva** [comment]
@luckyman20  @ankurs287 
Can I work on this? Just to implement length validators, further we can have validators for different companies with their logos as they are recognised. [Link for reference](https://stackoverflow.com/questions/28207252/regex-for-determining-credit-cards-in-android)

**Comment by luckyman20** [comment]
@nikhil-sachdeva We already that function ready, we aren't implementing it before release (we will implement it at the time of release).
