### ISSUE TITLE
Add Splash Screen to the app

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#354]
**Summary:**

Mobile-Wallet app lacks splash screen which increases UI of the app and is very useful for preparing any app by making background API calls.

**Steps to reproduce:**

1.Open the app
2.It directly opens the login screen

**Expected behavior:**

There must be a splash screen.

**Observed behavior:**

As soon as the app is launched,login screen is launched. (There is no splash screen)

**Device and Android version:**

Device : Samsung Galaxy S5
Android Version : 6.0.1

**Comment by RajaVamsi11** [comment]
@luckyman20 Can I work on this issue. As of reference, Mifos-Mobile app also contains Splash screen. You can check [here](https://github.com/openMF/mifos-mobile/blob/development/app/src/main/java/org/mifos/mobilebanking/ui/activities/SplashActivity.java).

**Comment by codepoet2017390** [comment]
@RajaVamsi11  Im not sure but maybe https://github.com/openMF/mobile-wallet/issues/276 this issue tries to accomplish the same

**Comment by luckyman20** [comment]
@codepoet2017390 I think that is a different issue, for this, we do not have our app's logo yet so we can't proceed.

**Comment by RajaVamsi11** [comment]
@luckyman20, For now, can we use Mifos logo as app logo and when mobile-wallet app logo is made we can replace it with it. What are your views on this?

**Comment by MukulCode** [comment]
@RajaVamsi11 I believe adding a splash screen is counted under Enhancement and is not considered as an issue.

**Comment by RajaVamsi11** [comment]
@MukulCode yes, you are right. The maintainers/ mentors will add tags according to the issue like Enhancement, bug, feature etc.,

**Comment by naman14** [comment]
@RajaVamsi11 we don't make any API call or do heavy work when app is launching and splash screens are generally considered to be a bad user experience. It doesn't make sense to unnecessarily add splash screen in the app
