### ISSUE TITLE
Fetching linked bank accounts

### ISSUE THREAD

**Issue by nikhil-sachdeva** [openMF/mobile-wallet#364]
**Summary:**

Currently, a static bank account detail list is added in the Linked Bank Accounts Screen.
~~~ java
    @Override
    public void fetchLinkedBankAccounts() {
        // TODO:: fetch linked bank accounts

        List<BankAccountDetails> bankAccountDetailsList = new ArrayList<>();
        bankAccountDetailsList.add(new BankAccountDetails("SBI", "Ankur Sharma", "New Delhi",
                mRandom.nextInt() + " ", "Savings"));
        mBankAccountsView.showLinkedBankAccounts(bankAccountDetailsList);
    }
~~~

**Steps to reproduce:**

mifospay->java->bank->presenter->BankAccountPresenter.java

**Expected behavior:**

I believe an API call should be made to retrieve the list of linked bank accounts, I haven't studied the Fineract API, hence would like to know if a suitable call can be made.

**Observed behavior:**

A static list is observed

**Device and Android version:**

Redmi Note 3

**Comment by luckyman20** [comment]
@nikhil-sachdeva API is not available for this right now, hence, it looks like this.
