### ISSUE TITLE
Send and request

### ISSUE THREAD

**Issue by manddy** [openMF/mobile-wallet#373]
Summary:
The send and the request tab has the same layout screens in the master branch,although it should be  different

Expected behavior:
layout screens of send and request tab should be different 

Observed behavior:
layout screens of send and request tab are the same

**Comment by shaliniv16** [comment]
@manddy This issue is not present in redesign branch

**Comment by RajaVamsi11** [comment]
@manddy Before opening an issue, please check dev and redesign branches. Because there are many issues which are solved in one branch and not solved in a different branch. Hope you understand.

**Comment by manddy** [comment]
OK.. I will close it, didn't knew about it before
