### ISSUE TITLE
PinEntryEditText is going out of LinearLayout in Debit Card Fragment

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#382]
**Summary:**

In `dev` branch while setting up UPI pin, when we enter the expiry year of the debit card in PinEntryEditText the text is going out of linear layout (The fourth digit of the year is not shown to the user) as shown in the screenshot.

**Steps to reproduce:**

Open the app and navigate to BankAccount --> click on linked bank account --> Setup UPI --> Enter debit card expiry year.

**Expected behavior:**

The expiry year must not be trimmed.

**Observed behavior:**

The expirt year fourth didgit is not visible to the user.

**Device and Android version:**

Device :  Redmi 4
Version : 7.1.2

**Screenshots:**

![screenshot_2019-03-01-16-46-19-561_org mifos mobilewallet mifospay](https://user-images.githubusercontent.com/30550059/53636884-a7f97980-3c47-11e9-86f7-f6794123af12.png)

**Comment by RajaVamsi11** [comment]
@naman14 @luckyman20 I am working on this issue.

**Comment by shaliniv16** [comment]
@RajaVamsi11 please refer to this issue #229

**Comment by RajaVamsi11** [comment]
@naman14  As this issue is persisting in redesigning branch also, I think It would be better to solve the small bugs accordingly rather than solving at once @luckyman20 . As I solved the issue I am sending a PR. If it seems unfair to you then please close the PR and issue.
Thankyou for your reference @shaliniv16

**Comment by luckyman20** [comment]
Fixed in #383
