### ISSUE TITLE
Redesign: /Payments/Request

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#386]
**Summary:**

This issue is about implementing the design and features of REQUEST tab in the Payments section. Presently, In redesign branch the request tab is empty and my idea is to integrate the request fragment into the Payments section.

That's what we want to achieve in the Request fragment of Payments section:

![52901644_2082380511837859_4035335943136215040_n 1](https://user-images.githubusercontent.com/30550059/53679241-24479780-3cf0-11e9-9102-783808bd785d.png)
Both UI and functionality of show QR code.

**Comment by RajaVamsi11** [comment]
@luckyman20 @naman14 @ankurs287 I am working on this issue.

**Comment by luckyman20** [comment]
This is now implemented. Thanks for the PR.
