### ISSUE TITLE
Even after an error, sign in is proceeding

### ISSUE THREAD

**Issue by tavishjain** [openMF/mobile-wallet#390]
**Summary:**

While creating a new account and signing in with Google account, there occurs an error, still I am passed on to the next screen

**Steps to reproduce:**

As shown in the attached GIF

**Expected behavior:**

The app must not have moved to the next screen to accept the mobile number

**Observed behavior:**

I saw the error and the intent should not have been sent

**Device and Android version:**

Redmi Note 4X - Android 7 Nougat

**Screenshots:**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31106411/53685965-8e3f5b80-3d47-11e9-99f3-7afe5a3512c8.gif)

**Comment by manddy** [comment]
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        showProgressDialog(Constants.PLEASE_WAIT);
        // Result returned from launching the Intent from GoogleSignInApi.getSignInIntent(...);
        if (requestCode == 11) {
            Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(data);
            try {
                // Google Sign In was successful, authenticate with Firebase
                account = task.getResult(ApiException.class);
                hideProgressDialog();
                signup(mMifosSavingProductId);

            } catch (Exception e) {
                // Google Sign In failed, update UI appropriately
                DebugUtil.log(Constants.GOOGLE_SIGN_IN_FAILED, e.getMessage());
                Toaster.showToast(this, Constants.GOOGLE_SIGN_IN_FAILED);
                hideProgressDialog();
                signup(mMifosSavingProductId);
            }
        }
    }

**Comment by manddy** [comment]
@tavishjain read this piece of code and see that firebase authentication is not implemented and it will signin even if there is an error in signing in

**Comment by RajaVamsi11** [comment]
@tavishjain, @manddy is right, according to the code sign up process is not implemented in the app. You don't need to worry about sign up. Just use the credentials that are provided in the wiki page to login. For ease, I am providing here.

**username:** mifospay01
**password:** Password1

**Comment by tavishjain** [comment]
@RajaVamsi11 I am getting an error while entering these credentials

**Comment by RajaVamsi11** [comment]
@tavishjain You can ask your queries in gitter. Join gitter channel https://gitter.im/openMF/mobile-wallet

**Comment by hghost50** [comment]
Is it possible to use own server to connect the mobile wallet
