### ISSUE TITLE
OTP not received

### ISSUE THREAD

**Issue by tavishjain** [openMF/mobile-wallet#392]
**Summary:**

When I am signing up for the app, I am not receiving the OTP, even after 5 to 10 minutes

**Steps to reproduce:**

Go to the sign up screen and create a new account, then disable the Google Sign in checkbox, and then continue to enter your mobile number 

**Expected behavior:**

The OTP must have arrived within 2 to 3 minutes, or even seconds 

**Observed behavior:**

When I am signing up for the app, I am not receiving the OTP, even after 5 to 10 minutes

**Device and Android version:**

Redmi Note 4X - Android Nougat

**Screenshots:**
The screen is as it is since the past 10 minutes I have been noticing it 

![whatsapp image 2019-03-03 at 1 03 37 am](https://user-images.githubusercontent.com/31106411/53686722-da42ce00-3d50-11e9-9c0b-a8f55a80cabe.jpeg)

**Comment by shaliniv16** [comment]
@tavishjain This issue is similar to #132

**Comment by manddy** [comment]
@Override
    public void requestOTPfromServer(String fullNumber, String mobileNo) {

        mUseCaseHandler.execute(searchClientUseCase, new SearchClient.RequestValues(mobileNo),
                new UseCase.UseCaseCallback<SearchClient.ResponseValue>() {
                    @Override
                    public void onSuccess(SearchClient.ResponseValue response) {
                        mMobileVerificationView.onRequestOtpFailed("Mobile number already exists.");
                    }

                    @Override
                    public void onError(String message) {
                        // TODO:: request OTP
                        mMobileVerificationView.onRequestOtpSuccess();
                    }
                });
    }

    @Override
    public void verifyOTP(String otp) {
        // TODO:: verify OTP
        mMobileVerificationView.onOtpVerificationSuccess();

        // TODO::

//        if (false) { // on error
//            mMobileVerificationView.onOtpVerificationFailed("OTP Verification Failed.");
//        }
    }
}

**Comment by manddy** [comment]
@tavishjain likewise this part is not implemented as of yet that is reason why you are not getting an otp

**Comment by tavishjain** [comment]
@manddy Then how am I supposed to proceed onto the main application ?

**Comment by manddy** [comment]
@tavishjain instead login with credentials username as mifospay01 and password as password1

**Comment by tavishjain** [comment]
@manddy I am getting an error while entering these credentials

**Comment by manddy** [comment]
@tavishjain even i am getting this error ,what i know is ,it a server issue that happens quite frequently so you just have to wait for it to be working again properly .I am putting up this issue on gitter channel kindly come there

**Comment by tavishjain** [comment]
@manddy aure

**Comment by RahulPrajapati97** [comment]
I am also facing the same error. I am not getting OTP. 
When i am entering my mobile no to get otp  it give me this response

GET https://demo.openmf.org/fineract-provider/api/v1/search?query=972*****05&resource=clients&exactMatch=false http/1.1
03-05 13:24:55.411 26485-17444/org.mifos.mobilewallet.mifospay D/OkHttp: --> END GET
03-05 13:25:05.811 26485-17444/org.mifos.mobilewallet.mifospay D/OkHttp: <-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: Connection closed by peer
03-05 13:25:05.811 26485-15936/org.mifos.mobilewallet.mifospay D/OkHttp: <-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: Connection closed by peer

And mifospay01 and password as password1 this credentials are also not working.

**Comment by RahulPrajapati97** [comment]
Can any one give me login credential because I am not getting Otp and I am also not able to login through Google.

**Comment by RajaVamsi11** [comment]
@RahulPrajapati97  Try these
username: mifospay01
password: Password1

**Comment by RahulPrajapati97** [comment]
@RajaVamsi11 Thank you

**Comment by RahulPrajapati97** [comment]
@RajaVamsi11 Is there any demo data from which i can test the application?

**Comment by RajaVamsi11** [comment]
@RahulPrajapati97 What do you mean by demo data? If you log in into the app, there are demo cases/data of every activity from which we can test our app.

**Comment by jsahil730** [comment]
@tavishjain please close this issue as of now

**Comment by hghost50** [comment]
This issue is not sort.

**Comment by hghost50** [comment]
This issue is not sort.
