### ISSUE TITLE
Transaction dialog opens multiple times

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#397]
**Summary:**

Transaction dialog opens multiple times if opens multiple times quickly

**Device and Android version:**

Device Real Me 2
Android version 8.1.0

**Gif:**

![videotogif_2019 03 03_11 50 58](https://user-images.githubusercontent.com/32845033/53691805-5407a580-3dab-11e9-948a-adc5fdb342ee.gif)

**Comment by RajaVamsi11** [comment]
@shaliniv16 Can you please refer [this](https://github.com/openMF/mifos-mobile/issues/1012) issue comment. As @therajanmaurya said this is not an issue. It is normal behavior. If you will try to click on any button in any app twice or more than twice before opening the app. It will intent twice.

**Comment by shaliniv16** [comment]
@RajaVamsi11 Can you please refer [this](https://github.com/openMF/mifos-mobile/issues/1013)

**Comment by RajaVamsi11** [comment]
@shaliniv16 I don't know but according to @therajanmaurya, it is normal behavior as explained above. Let's leave to the mentors to review.

**Comment by devansh-299** [comment]
This issue has already been solved, hence closing this issue
