### ISSUE TITLE
Even after Firebase Sign in is skipped Empty OTP is also Accepted !

### ISSUE THREAD

**Issue by Vipinsoni38** [openMF/mobile-wallet#410]
After firebase sign in is failed 

An empty OTP is also accepted 

![20190304_123319](https://user-images.githubusercontent.com/32003964/53716134-e7a7a780-3e79-11e9-9b92-0609125bb72c.gif)

**Comment by Vipinsoni38** [comment]
Currently using mEtOtp.getText().toString().trim().length()==0
if there is a fixed size otp then would change the code to 
mEtOtp.getText().toString().trim().length()!=OTP_SIZE

**Comment by shaliniv16** [comment]
@Vipinsoni38 please refer to #132

**Comment by Vipinsoni38** [comment]
@shaliniv16  the issue is yet to be resolved!
also, the code to send and verify OTPis yet to be written so looking forward to resolve it.

**Comment by justdvnsh** [comment]
The Issue still persists. @shaliniv16 @Vipinsoni38 . Can I work on this issue, if available ?

**Comment by justdvnsh** [comment]
@ReCodee How about this one ? Is this relevant ?

**Comment by ReCodee** [comment]
@justdvnsh This functionality is yet to be implemented, I guess we don't have the necessary APIs.

**Comment by justdvnsh** [comment]
@ReCodee Ohkayy 😅
