### ISSUE TITLE
Support for Gradle Play Publisher

### ISSUE THREAD

**Issue by aggarwalpulkit596** [openMF/mobile-wallet#419]
**Summary:**
All Support for Triple t Gradle Play Publisher for automated publishing of app to play store
References
https://github.com/Triple-T/gradle-play-publisher

**Comment by RajaVamsi11** [comment]
@aggarwalpulkit596 I think it is not necessary for now as our project is still under development and many features need to be added.What are your views on this issue @luckyman20 @naman14 .

**Comment by naman14** [comment]
Not required for now
