### ISSUE TITLE
ScrollView size validation issue in XML files

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#433]
**Summary:**

When the inspection is done on the whole project, Android studio throws ScrollView size validation issue in some of the XML files.

![screenshot from 2019-03-08 19-59-46](https://user-images.githubusercontent.com/30550059/54034811-d6de9500-41dd-11e9-8c6b-685843a19439.png)
I am going to change layout_width or layout_height to wrap_content rather than match_parent or fill_parent to remove Android Lint Correctness (ScrollView size validation)  warnings.

**Comment by rachittt** [comment]
@RajaVamsi11 the screens have been redesigned. Can you confirm if the issue still persists? Please close if not. Thanks.
