### ISSUE TITLE
Limit the digits of Mobile Number in Mobile Verification and KYC Registration level 1 Activities

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#451]
**Summary:**

 There should be a limit of digits while entering Mobile Number in Mobile Verification Activity and in KYC Registration level 1. 

**Steps to reproduce:**

[dev]  Login Page --> Sign Up --> Merchant --> Mobile number filed has no limit on digits.
[dev]  Home --> Complte KYC --> level 1 --> Mobile Number field has no limit on digits.

**Expected behavior:**

There should be a limit on digits in Mobile Number field.

**Observed behavior:**

There is no limit on digits in Mobile Number field.

**Device and Android version:**

Device: Redmi 4
Version: 7.1.2

**Screenshots:**

![Screenshot_2019-03-09-18-02-59-513_org mifos mobilewallet mifospay](https://user-images.githubusercontent.com/30550059/54072832-1a9cd180-42a6-11e9-9b66-994aebc89f8c.png)

**Comment by luckyman20** [comment]
Solved in #452
