### ISSUE TITLE
Select a country pop-up dialog box is showing only two countries

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#453]
**Summary:**

In Mobile Verification activity and KYC Registration level 1 activity, when we are going to select a country the pop-up dialog box shows only two countries as shown in screenshots. The pop-up dialog box should show all the countries as an options to select as it shows in edit profile activity.

**Steps to reproduce:**

[dev] Login Page --> Sign Up --> Merchant --> Select country.
[dev] Home --> Complte KYC --> level 1 --> Select country code.

**Expected behavior:**

All countries should be shown in the list to select.

**Observed behavior:**

Only two countries are showing in the list to select.

**Device and Android version:**

Device: Redmi 4
Version: 7.1.2

**Screenshots:**

**Mobile Verification Activity**
![Screenshot_2019-03-09-00-35-18-447_org mifos mobilewallet mifospay](https://user-images.githubusercontent.com/30550059/54073624-9bac9680-42af-11e9-82f2-f04f817ec9a5.png)

**KYC Registration level 1 Activity**
![Screenshot_2019-03-09-00-01-20-682_org mifos mobilewallet mifospay](https://user-images.githubusercontent.com/30550059/54073626-a23b0e00-42af-11e9-9032-78b742fe24bd.png)

**Comment by luckyman20** [comment]
@RajaVamsi11 Our target market through this app is India so I don't we need to show other countries.

@edcable @naman14 Thoughts?
