### ISSUE TITLE
Link Your Bank Account button is not responding on first click

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#462]
**Summary:**

In Linked bank Accounts Activity, there is a button to link a bank account (Link Your Bank Account). When it is clicked for the first time it does nothing and when clicked the second time it opens a new activity showing all the banks to link your bank account.

**Steps to reproduce:**

[dev]  Home --> Bank Account --> Link Your Bank Account  (No response on the first click) --> Click one more time on Link Your bank Account (Now it opens a new activity)

**Expected behavior:**

Link Your bank Account button is not showing any response on the first click.

**Observed behavior:**

Link Your Bank Account button should open new activity on the first click.

**Device and Android version:**

Device : Redmi 4
Version : 7.1.2

**Screenshots:**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30550059/54091056-4fda1a00-43a1-11e9-8bb9-e6bc06413f8b.gif)

**Comment by rchtgpt** [comment]
There have been UI changes since and the 'Add Account' button is now working so this issue is not reproducible anymore.
