### ISSUE TITLE
Not showing Merchants with no Virtual payment address 

### ISSUE THREAD

**Issue by Vipinsoni38** [openMF/mobile-wallet#467]
**Summary:**

the merchants which do not have a VPA (Virtual Payment address ) which may be created by mistake will not be shown Thus will give user a better experience 

**Screenshots:**
![image](https://user-images.githubusercontent.com/32003964/54121393-5196f280-4420-11e9-8de8-687becc0b234.png)

**Comment by RajaVamsi11** [comment]
@Vipinsoni38 I think they are added for testing purpose.

**Comment by Vipinsoni38** [comment]
Yes but what if they get added by some mistake i mean no VPA!
in that case it will omit those without VPA
