### ISSUE TITLE
Adding card search functionality 

### ISSUE THREAD

**Issue by Vipinsoni38** [openMF/mobile-wallet#470]
**Summary:**

Adding search functionality in the cards section will help user to easily find a card saved which will improve user experience with the app.

**Comment by Bhavnaharitsa** [comment]
@luckyman20 We don't have this function yet,...can I take this up?
Also, please review my recent prs

**Comment by luckyman20** [comment]
I don't think it is necessary to implement a search feature for cards as a normal user has max 5-6 cards which he/she can easily access and navigate through.
