### ISSUE TITLE
Removing Toast messages in faq

### ISSUE THREAD

**Issue by Vipinsoni38** [openMF/mobile-wallet#472]
Removing toast messages in FAQ

![Screenshot_20190311-224421](https://user-images.githubusercontent.com/32003964/54143191-5921c000-444f-11e9-8fb4-74dba710c9a9.png)

**Comment by RajaVamsi11** [comment]
@Vipinsoni38 I think toast messages are added for testing purpose and they will be removed at the time release. Don't need to worry about the toasts.

**Comment by Bhavnaharitsa** [comment]
@luckyman20 We can close this! :)
