### ISSUE TITLE
Empty view is missing in Link Your Bank Account

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#490]
**Summary:**

There should be an empty view when no bank is found in Link Your Bank Account.

**Comment by Bhavnaharitsa** [comment]
@luckyman20 I would like to take up this issue

**Comment by luckyman20** [comment]
@Bhavnaharitsa Yes, please take up this issue but keep in mind that don't block too many issues at a time and allow other contributors to contribute too.

**Comment by Bhavnaharitsa** [comment]
@luckyman20 Sure sir, I will not. I will start creating my own issues soon. And give you updated of the blocked issues too :)

**Comment by devansh-299** [comment]
Closing as this issue has already been addressed by #692
