### ISSUE TITLE
Adding snackbar to alert user if he's not connected to the internet

### ISSUE THREAD

**Issue by codepoet2017390** [openMF/mobile-wallet#493]
**Summary:**

If the user is disconnected from the internet he should be notified via a prolonged Snackbar that he is not connected to the Internet. though there are toast messages showing error fetching information but none of them identifies the network connection. This issue is pretty annoying in the Passcode Activity as there is no visual indication of any errors.

**Expected behavior:**
User should be notified via Snackbar.

**Device and Android version:**
OnePlus5 android 9(Pie)

**Would you like to work on this**
Yes

**Comment by RajaVamsi11** [comment]
@codepoet2017390 Can you please refer #398. Adding sweet error library when it is not connected to internet is better than toasts and snackbars. I am presently working on this issue to show No internet screen using sweet error library which is implemented in Mifos-Mobile.

**Comment by codepoet2017390** [comment]
@RajaVamsi11 have the mentors approved the use of this library.

**Comment by RajaVamsi11** [comment]
As it is implemented in Mifos Mobile, I think there will be no problem in implementing in this project. The mentors are busy with the works and they will respond very soon.

**Comment by codepoet2017390** [comment]
@RajaVamsi11 ok i'll close this issue depending on mentors respose.

**Comment by shaliniv16** [comment]
@RajaVamsi11 what is the need of sweet error library? In redesign branch in some of the activity when not connected to the internet it is already showing an error state view.

**Comment by shaliniv16** [comment]
@codepoet2017390 Can you please once check the redesign branch for the same issue?

**Comment by codepoet2017390** [comment]
@RajaVamsi11  i just saw the library. I dont think there is some spefic use case that the library serves for our app. 
@shaliniv16 the issue was found in redesign branch itself.

**Comment by RajaVamsi11** [comment]
@codepoet2017390 @shaliniv16 Yes the fragments/activities which are retrieving data to display using the internet are suitable to add the library like Saved cards, Notifications, and other fragments and activities.

**Comment by codepoet2017390** [comment]
@RajaVamsi11 the library cannot be used in passcode Activity. A snackBar is the only solution for that so i'm adding a Snackbar to passcode Activity and will be adding more checks to other activities is mentors dont find it useful to to add another third party dependency.

**Comment by RajaVamsi11** [comment]
@codepoet2017390 I think you are talking about this error message to be shown when the device is not connected to the internet. If yes, then it is implemented in dev branch, please take a look.
![Screenshot_2019-03-17-23-32-23](https://user-images.githubusercontent.com/30550059/54495798-40148580-490d-11e9-92e1-9058793a4ca1.png)

**Comment by codepoet2017390** [comment]
@RajaVamsi11 yes yes i'm sorry i didnt check in both the branches.

**Comment by RajaVamsi11** [comment]
@codepoet2017390 Not a problem. Just check dev, redesign branch and opened issues before opening a new issue :smiley:
