### ISSUE TITLE
Cancel Button is not working in Edit Profile

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#498]
**Summary:**

On clicking cancel button it should clear the editText in password and passcode field.

**Device and Android version:**

Device Real me 2
Android version 8.1.0

**Gif:**

![videotogif_2019 03 18_16 43 50](https://user-images.githubusercontent.com/32845033/54526918-4a329480-499e-11e9-8c5e-d9e12c6f1736.gif)

**Comment by arunikayadav42** [comment]
If this issue is still open I would like to take this up :). Please help me get started.

**Comment by Bhavnaharitsa** [comment]
@arunikayadav42 
I think the UI is quote different now. Please check with the mentors

**Comment by rachittt** [comment]
@shaliniv16 this issue does not exist anymore, so please close it. Thanks
