### ISSUE TITLE
Add Card option in branch dev_redesign

### ISSUE THREAD

**Issue by Vipinsoni38** [openMF/mobile-wallet#502]
No add card functionality in the redesign branch 

![20190319_131934_rmscr](https://user-images.githubusercontent.com/32003964/54588843-08f7be80-4a4a-11e9-800e-7f1d29b4bb24.jpg)

**Comment by shaliniv16** [comment]
@vipinsoni38 please refer to #337

**Comment by Vipinsoni38** [comment]
Cool

**Comment by shaliniv16** [comment]
@vipinsoni38 Can you please close this issue? This one is already solved.

**Comment by RajaVamsi11** [comment]
@Vipinsoni38 Please close this issue to remove duplicate issues from the projects.
