### ISSUE TITLE
Clicking on back button directly exits even if search results are displayed

### ISSUE THREAD

**Issue by Vipinsoni38** [openMF/mobile-wallet#508]
**Summary:**

When a user enters merchants Fragment and search for a merchant and press back button this should first clear the search results and on the second back press it should exit that fragment 

![20190319_200746](https://user-images.githubusercontent.com/32003964/54614642-c1415900-4a82-11e9-9763-859c27f8cb59.gif)

**Comment by shaliniv16** [comment]
@vipinsoni308 I am already working on this issue #500

**Comment by Vipinsoni38** [comment]
mine is different @shaliniv16  
will you please again explain yours issue its not clear enough

**Comment by RajaVamsi11** [comment]
@shaliniv16 I think your issue #500 and this issue is not similar. Can you please go through the summary of the issues again.

**Comment by shaliniv16** [comment]
I am trying to implement this.
![videotogif_2019 03 19_21 38 30](https://user-images.githubusercontent.com/32845033/54637947-e00a1480-4aaf-11e9-8f6a-54192186f108.gif)

**Comment by Vipinsoni38** [comment]
So that's something different 
and its the work for redesign branch
you want to implement a design and I am trying to resolve onBackPressed event, I think they are pretty different

**Comment by Vipinsoni38** [comment]
@shaliniv16 that's something different 
and its the work for redesign branch
you want to implement a design and I am trying to resolve onBackPressed event, I think they are pretty different

**Comment by Vipinsoni38** [comment]
@shaliniv16  Would you please reply to the prev thread 
just wanted to know should i start working on this issue
