### ISSUE TITLE
Log Out functionality Should be in Menu Option

### ISSUE THREAD

**Issue by Vipinsoni38** [openMF/mobile-wallet#510]
Logout Option should be in the menu option in the Home page 

PS: currently it is in Menu Option -> Settings -> Logout 

![20190320_155224_rmscr](https://user-images.githubusercontent.com/32003964/54677238-7ed25780-4b28-11e9-9941-c56065a188c2.jpg)

**Comment by shaliniv16** [comment]
@Vipinsoni38 Most of the apps has log out functionality inside the Settings option.
