### ISSUE TITLE
App icon missing

### ISSUE THREAD

**Issue by njwardhan** [openMF/mobile-wallet#521]
**Summary:**

This issue is about the missing icon of the Mifos Mobile Wallet app. 

**Expected behavior:**

It is expected that once the repo is cloned on the local device and is run, it should have the official Mifos Initiative logo to have a better and credible appearance.

**Observed behavior:**

Currently, the icon is set to the default android logo and is thus giving a poor appearance to the app.

**Device and Android version:**

I have encountered this issue while running the app on my device which is OnePlus 6 (Android Pie-OxygenOS Version 9.0.4)

**Screenshots:**
This is the change which I am proposing:-
https://docs.google.com/document/d/1a-2bq4vu56zR85zm2ArgRk7HSTTpegKk-FZXIoeoDvI/edit?usp=sharing

I would like to work on this issue and solve it.

**Comment by shaliniv16** [comment]
@njwardhan Can you please refer #354 once?

**Comment by njwardhan** [comment]
@shaliniv16 , thanks for the concern.
I've made an issue regarding this and will wait for any of the mentor to
give a feedback. I'll accordingly make changes.
Thanks again and Happy Coding! :)

**Comment by njwardhan** [comment]
Sir, @droidchef , @naman14 , I would like to work on this issue. Can you please review it and give consent?

**Comment by RajaVamsi11** [comment]
@njwardhan Can I know that why did you closed the PR #520 . Any specific issue with that Pull Request? Just asking to help you if you have any problems.

**Comment by njwardhan** [comment]
@RajaVamsi11 , I closed the PR #520 because it was not getting its Travis CI check cleared. I had missed out a few steps in the PR guidelines. So anticipating that to be a reason, I deleted the PR and planned to re-submit the PR after completing all the steps properly and then hopefully getting my checks cleared.
However, if you could give some info on the Travis CI check which showed my build to have been failed, I would be thankful.

**Comment by RajaVamsi11** [comment]
You can run the `./gradlew check` in the terminal of Android studio and you will know where the code is breaking the Travis build.

**Comment by njwardhan** [comment]
@RajaVamsi11 , I tried the command in the android studio terminal. However, the build is still failing with some actionable tasks. This is the exact piece of the terminal which I am seeing:-


> Configure project :mifospay
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :core:compileDebugJavaWithJavac FAILED
Gradle may disable incremental compilation as the following annotation processors are not incremental: dagger-compiler-2.11.jar (com.google.dagger:dagger-compiler:2.11).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: javax/annotation/Generated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.









I would appreciate if you could guide me through this issue in getting my Gradle build successful.

**Comment by luckyman20** [comment]
@njwardhan We are still in process in making a logo specific to this app.

**Comment by njwardhan** [comment]
@luckyman20 , ok great!
