### ISSUE TITLE
Inappropriate answers to questions in FAQ activity

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#528]
**Summary:**

In Frequently Asked Questions activity, the answers to the questions are not correct. The answer to all questions is showing `Answer 1`. The answers must be updated in the strings.xml file according to the question number.

**Device and Android version:**

Device: Redmi Note 3
Android version: 6.0.1

**Screenshots:**

![Screenshot_2019-03-27-19-59-19-523_org mifos mobilewallet mifospay](https://user-images.githubusercontent.com/30550059/55084885-b3678580-50cb-11e9-8d3b-ca6774b82a4c.png)

**Comment by Bhavnaharitsa** [comment]
@luckyman20 @shiv07tiwari Sir, this issue is solved too. And I was wondering if we could add more questions on FAQ related to the app. If yes, I would like to take up the issue :)

**Comment by luckyman20** [comment]
@Bhavnaharitsa No, 4-5 questions are enough for now. We will add them in future if need arises.
