### ISSUE TITLE
Wrong Toast messages in FAQ activity

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#535]
**Summary:**

Wrong Toast messages are popping in FAQ activity. When the question in the faq activity is expanded the toast message is displayed as "Question is collapsed" which must be changed to "Question is expanded"

**Steps to reproduce:**

Home --> FAQ --> Expand any question 

**Expected behavior:**

Toast message should be correct

**Observed behavior:**

Toast message is displaying wrong

**Device and Android version:**

Device: ASUS Zenfone 2
Version: 4.4.2

**Screenshots:**

![Screenshot_2019-04-12-00-26-47](https://user-images.githubusercontent.com/30550059/55984529-4eab4e00-5cbb-11e9-9c40-2858d7aa20cb.jpg)

**Comment by shaliniv16** [comment]
@RajaVamsi11 Is your issue is similar to # 472?

**Comment by RajaVamsi11** [comment]
@shaliniv16 No.That issue is about removing and this is about updating the toasts.

**Comment by shaliniv16** [comment]
@RajaVamsi11 Yes, you are right, but you said that these toast messages should be removed at the time of release.

**Comment by RajaVamsi11** [comment]
@shaliniv16 I corrected the toats messages for development purpose only so that developer know that it was collapsed and expanded. It seems quite odd that toasts occurring collapsed all the time. So I updated those messages. The toasts can serve the purpose until the release of the app.

**Comment by Bhavnaharitsa** [comment]
@luckyman20  @shiv07tiwari As this is resolved, I guess we can close this now
