### ISSUE TITLE
Outdated Wiki

### ISSUE THREAD

**Issue by ankurs287** [openMF/mobile-wallet#54]
I've updated the wiki [here](https://github.com/ankurs287/mobile-wallet/wiki)
Updated Wiki link: https://github.com/ankurs287/mobile-wallet/wiki

To merge latest changes, follow [this](https://gist.github.com/larrybotha/10650410)

**Comment by ankurs287** [comment]
@naman14 @puneetkohli521 Kindly merge the latest wiki.

**Comment by naman14** [comment]
updated the wiki
