### ISSUE TITLE
Use sp instead of dp for text sizes

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/mobile-wallet#542]
**Summary:**

For declaring text sizes one must use `sp` instead of `dp` as sp respect the user preferences. When setting text sizes, you should normally use sp, or "scale-independent pixels". This is like the dp unit, but it is also scaled by the user's font size preference. It is recommended you use this unit when specifying font sizes, so they will be adjusted for both the screen density and the user's preference.

 Here is the simple [example](http://www.singhajit.com/tutorial-1-android-ui-desgin-and-styling/) and [explanation](https://medium.com/@rayacevedo45/android-sp-vs-dp-ca50ad53162d) between `sp` and `dp`.
The project is using dp for some text size declaration in files like `fragment_send.xml`. My idea is to change them from dp to sp.

**Comment by jsahil730** [comment]
@RajaVamsi11 since your PR has been merged, please close this issue.

**Comment by RajaVamsi11** [comment]
Solved in #543
