### ISSUE TITLE
Change Profile Picture

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#545]
**Summary:**

`Change profile picture` button must show option like the gallery, google photos and camera instead of google drive.

**Steps to reproduce:**

- Go to Edit Profile
- Click on Profile Picture
- Click on Change Profile Picture

**Expected behavior:**

Its must show options like `Gallery`, `Google Photos` and `Camera`.

**Observed behavior:**

Its open google drive.

**Device and Android version:**

Device Real Me 2 
Android Version 8.1.0

**Gif:**

![videotogif_2019 04 28_20 50 06](https://user-images.githubusercontent.com/32845033/56866751-bcb17e00-69fa-11e9-927c-df9d86e0fcc9.gif)

**Comment by shaliniv16** [comment]
@naman14 @luckyman20 Should I start working on this issue?

**Comment by mayankwadhwani** [comment]
I'll like to take this up @shaliniv16

**Comment by 991rajat** [comment]
@shaliniv16 Works fine on my device.
Moto E2 Nougat 7.1.2

**Comment by luckyman20** [comment]
This is working now.
