### ISSUE TITLE
Remove hardcoded strings

### ISSUE THREAD

**Issue by GOVINDDIXIT** [openMF/mobile-wallet#560]
**Summary:**

Remove hardcoded strings. Convert them into String resource file.

**Steps to reproduce:**

Open Android Studio and Find out hard-coded text in XML file.

**Expected behavior:**

There should be no hardcoded strings

**Observed behavior:**

Few of the strings are hardcoded

**Device and Android version:**

Android 9
Redmi Note 5 Pro
MIUI 10

**Comment by GOVINDDIXIT** [comment]
This issue is for GCI Students

**Comment by TarunPal3551** [comment]
I want to work on this, can I?

**Comment by GOVINDDIXIT** [comment]
Issues under GCI label are for GCI Students and can be claimed by only GCI Students after Dec 2, 2019

**Comment by TarunPal3551** [comment]
Ok sir, can you please help me in contribution for GSOC 2020

**Comment by GOVINDDIXIT** [comment]
@TarunPal3551 Sure, You can pick from any other open issues and ask for help if you are facing any problem.
