### ISSUE TITLE
Add frequently asked question under FAQ section

### ISSUE THREAD

**Issue by GOVINDDIXIT** [openMF/mobile-wallet#561]
**Summary:**

Add frequently asked question under the FAQ section
**_Check Help section of mifos mobile app for reference_**
Add question like how to add an account
How to access your payment history
How to add card etc
You can add a walkthrough statement in the answer

**Steps to reproduce:**

Open the FAQ section.

**Expected behavior:**

There should be some frequently asked question for the help of new users

**Observed behavior:**

Currently, there is only a template for the FAQs which need to be edited
 
**Device and Android version:**

Android 9
Redmi Note 5 Pro
MIUI 10

**Screenshots:**

Open FAQ section

**Comment by GOVINDDIXIT** [comment]
This issue is for GCI

**Comment by luckyman20** [comment]
@GOVINDDIXIT Please be more specific as to what questions you want to get added.

**Comment by GOVINDDIXIT** [comment]
@luckyman20 updated

**Comment by Bhavnaharitsa** [comment]
@GOVINDDIXIT Are you still working on the issue?
@luckyman20 Can I tale this up?

**Comment by GOVINDDIXIT** [comment]
@Bhavnaharitsa This issue is for GCI Students. You can look at other available issues. @luckyman20 Can you place a GCI label on it?

**Comment by jsahil730** [comment]
@GOVINDDIXIT this issue can be closed now.
