### ISSUE TITLE
Set up passcode and Payments tab does not follow the color scheme of the app

### ISSUE THREAD

**Issue by harshshinde07** [openMF/mobile-wallet#562]
**Summary:**

The color of setup passcode screen after login and the send money screen in the payment tab does not follow the overall color scheme of the application

**Steps to reproduce:**

- Passcode screen
Login to the app to see the color difference in the passcode screen.
The passcode screen does not follow the color scheme.

- Payments screen
After login, press on the payments option in the bottom bar.
You will see that the selected transfer method does not follow the color scheme.

**Screenshots:**

- Passcode screen
<img src="https://user-images.githubusercontent.com/25999879/68728051-36eace00-05ec-11ea-8080-e74db4b57128.png" width=200 />

-Payments screen
<img src="https://user-images.githubusercontent.com/25999879/68728049-36eace00-05ec-11ea-87d1-efb95ce580ac.png" width=200 />

**Comment by TarunPal3551** [comment]
I want to work on this issue

**Comment by harshshinde07** [comment]
@TarunPal3551 As you can see, this issue is tagged as GCI so you can't take up this issue

**Comment by TarunPal3551** [comment]
@harshshinde07 Ok can you please guide me for GSOC 2020?

**Comment by harshshinde07** [comment]
@TarunPal3551 Can you please elaborate what kind of guidance you need?

**Comment by TarunPal3551** [comment]
I want to contribute, so how I will start?

**Comment by harshshinde07** [comment]
First decide the technology in which you want to  work. Then start finding projects that you want to contribute to. Find and create issues and solve them. Hope this helps :)

**Comment by luckyman20** [comment]
@ankurs287 Can you please look into this since you were there while the redesign?

@letelete If you can help.

**Comment by shiv07tiwari** [comment]
@luckyman20 @harshshinde07 The passcode screen is basically using the passcode library. So, if we want to sync the color scheme, we'll have to do it manually. It is opening the custom screen from the library.

**Comment by luckyman20** [comment]
@shiv07tiwari I was talking about payments screen. Is that color tertiary for the app?

**Comment by harshshinde07** [comment]
@luckyman20 If you permit me, I can try to fix this as no one is active here

**Comment by luckyman20** [comment]
Well, if the colors are complementing the theme then we can keep it as it is.
