### ISSUE TITLE
Add margin start and end

### ISSUE THREAD

**Issue by sukhbeer** [openMF/mobile-wallet#563]
**Summary:**

 If minSdkVersion is less than 17, we should add both the older left/right attributes as well as the new start/end attributes. find XML file and add margin start and end.

**Comment by sukhbeer** [comment]
This issue for GCI student. @luckyman20  add GCI tag.

**Comment by luckyman20** [comment]
@sukhbeer You have told half of the solution already and guessing the other half is no-brainer. How can we add this as a task now?

**Comment by sukhbeer** [comment]
@luckyman20  so can I remove the code?
