### ISSUE TITLE
Pressing logout button should open alert dialog box

### ISSUE THREAD

**Issue by GOVINDDIXIT** [openMF/mobile-wallet#564]
**Summary:**

Pressing logout should open an alert dialog box asking for confirmation of user to logout

**Steps to reproduce:**

Go to Settings and press the log out button

**Expected behavior:**

It should open an alert dialog box asking for user confirmation to log out

**Observed behavior:**

Immediate log out from the app
**Device and Android version:**

Android 9
Redmi Note 5 pro
MIUI 11

**This issue is for GCI Students**

**Comment by jsahil730** [comment]
@GOVINDDIXIT Since this issue has been resolved, please close this issue
