### ISSUE TITLE
Update library dependencies and build tools, configure build variant

### ISSUE THREAD

**Issue by jddeep** [openMF/mobile-wallet#565]
**Summary:**

Update library dependencies and build tools versions to correct and latest ones.
Irradicate sync and build errors + warnings.
Issues with build variant.

**Steps to reproduce:**

Clone the project and build it.

**Expected behavior:**

The build should be successful without any dependency warnings or errors.

**Observed behavior:**

Dependency warnings, build tools outdated, build variant issues.

**Device and Android version:**

Android Pi.

**Comment by PiyushSharma99** [comment]
I want to work on this as part of GCI 2019. @jddeep @luckyman20 @santoshconflux please guide me.

**Comment by luckyman20** [comment]
@PiyushSharma99 Let the GCI start ;)

@jddeep Please add more info and screenshots.

**Comment by luckyman20** [comment]
Solved in #581
