### ISSUE TITLE
Lacking dependency

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#566]
**Summary:**

The Request Fragment uses a third party library for Phone number and Number Exception but initially the library is missing in gradle file and a new contributor has to manually add it. 

**Steps to reproduce:**

Simple fork and clone

**Expected behavior:**

Clean build

**Observed behavior:**

Error in RequestFragment.java

**Device and Android version:**

Samsung J8

**Would you be working on this issue?**
Yes

**Comment by luckyman20** [comment]
Solved in #574
