### ISSUE TITLE
Issues in dev branch

### ISSUE THREAD

**Issue by jsahil730** [openMF/mobile-wallet#569]
**Summary:**

There are various issues with dev branch, especially in Manifest and while building.

**Steps to reproduce:**

Simply open the folder in Android Studio, and try to build. Build fails.
If you try to install the app in your phone, errors appear.

**Expected behavior:**

Build and install completes without errors.

**Observed behavior:**

io.michaelrocks.libphonenumber.android.numberparseexception not found.
Manifest file has 'TransactionsHistoryActivity' which is nowhere, same goes for 'MifosPayIDInstance' service.
These files were present in redesign branch but are no more there.

**Device and Android version:**

Redmi 5 Pro, Android 10

**Screenshots:**

Will add soon.

**Comment by luckyman20** [comment]
This issue is already there #566 

I would advice you to please check if that issue is already is reported or not.

**Comment by jsahil730** [comment]
@luckyman20 
Manifest file of mifospay module has 'TransactionsHistoryActivity' which is nowhere, same goes for 'MifosPayIDInstance' service.
These files were present in redesign branch but are no more there.

**Comment by luckyman20** [comment]
You can create separate issue for that, please try avoiding merging multiple issues.
