### ISSUE TITLE
Feature Request: Hosting app on appetize

### ISSUE THREAD

**Issue by akkywadhwa** [openMF/mobile-wallet#570]
**Summary:**
Appetize provides a free evaluation of the app, new contributors do not need to install/build the app to check it. Several people can manage single app using the token and the key. 

Please check https://appetize.io/

Check out this [susi](https://appetize.io/app/mbpprq4xj92c119j7nxdhttjm0?device=nexus5&scale=75&orientation=portrait&osVersion=8.1) hosted app from fossasia

**Steps to reproduce:**
NA

**Expected behavior:**
NA

**Observed behavior:**
NA

**Device and Android version:**
NA 

**Screenshots:**
NA

**Comment by luckyman20** [comment]
@akkywadhwa Is it free for open source?

**Comment by akkywadhwa** [comment]
> 
> 
> @akkywadhwa Is it free for open source?

![55542866-e8468e80-5702-11e9-9347-979c11abd8f5](https://user-images.githubusercontent.com/666752/69887717-53864600-130e-11ea-8211-0a0c6f663b74.png)


From that, I guess that we will not advertise appetize.io as a mainstream way to try the app, as we would quickly overflow the free tier. Setting up scripts to automatically push APKs is probably not worth the trouble.
Pushing an APK could be perfectly fine, the app is open source after all :-)

**Comment by devansh-299** [comment]
@akkywadhwa we don't need this currently, hence closing this issue
