### ISSUE TITLE
Travis CI does not run anymore

### ISSUE THREAD

**Issue by vorburger** [openMF/mobile-wallet#573]
The Travis CI build does not run anymore for recent PRs, such as e.g. #567.

The README points to the old wrong TravisCI.org instead of TravisCI.com which is now used.

https://github.com/openMF/mobile-wallet/commits/dev has links to CloudBees Codeship, e.g. https://app.codeship.com/projects/332704/builds/b17ee1e9-ffe3-4c9f-98ea-1dc2cafcf059, but those do not appear to be public?  Also the README only links to and mentions TravisCI, not Codeship.

I'll see if I can do anything quick & easy to make TravisCI kick in again...

@edcable @Bhavnaharitsa @jsahil730 @luckyman20 FYI, feel free to chime in here, if anything

**Comment by vorburger** [comment]
The `master` branch currently [still passes the build on Travis](https://travis-ci.com/openMF/mobile-wallet/builds/138872442).

But the `dev` branch of this project currently does not build anymore (on Travis), see https://travis-ci.com/openMF/mobile-wallet/builds/138872225, due to `Caused by: org.gradle.api.GradleException: Checkstyle rule violations were found. See the report at: file:///home/travis/build/openMF/mobile-wallet/mifospay/build/reports/checkstyle/checkstyle.html`

PS: https://github.com/openMF/mobile-wallet/blob/dev_redesign/.travis.yml makes it look like this project at least at some point in the past definitely used Travis... if this project meanwhile would like to use CloudBees Codeship instead of Travis, then that file should be removed and the README updated accordingly... otherwise could I suggest that whoever set up CloudBees Codeship disable that again?

**Comment by jsahil730** [comment]
@vorburger I might try doing something, but could you please tell me how to do Travis build on my pc, I don't quite seem to get the hang of it?

**Comment by luckyman20** [comment]
@naman14 @ankurs287 @shiv07tiwari You all might have more info about this.

**Comment by vorburger** [comment]
You can't really run Travis on your PC, but all that probably needs to be
done here is to fix the Checkstyle error which Travis hits, see log on
Tarvis. You should get that same error in a regular local Gradle build as
well, no?

You can also have a look at the . travis.yml file in the root of this repo
to find the exact Gradle command which Travis actually runs.

>

**Comment by jsahil730** [comment]
@luckyman20 @vorburger Travis build works fine now, albeit with a lot of warnings, since I know nothing about either pmd or findbugs, also findbugs has issues with java version 13; maybe someone should change findbugs to spotbugs, as findbugs is probably deprecated?

**Comment by vorburger** [comment]
> @luckyman20 @vorburger Travis build works fine now

Cool, thanks for #574. Who will review and merge that?

This issue can be closed (from my side) when that PR is merged.

**Comment by luckyman20** [comment]
@vorburger It is merged now. I think we can close this issue now.

**Comment by vorburger** [comment]
The Travis Badge on the README is still red.. I'm keeping this open to remember to change the Settings on Travis to build both master and dev.

**Comment by vorburger** [comment]
Oh, the Build Pushed Branches was disabled (only PRs), I've fixed that, and manually triggered a build if the Dev branch, so it should turn green; thus closing this now.
