### ISSUE TITLE
'Building the Code' steps misleading

### ISSUE THREAD

**Issue by jsahil730** [openMF/mobile-wallet#575]
**Summary:**

The steps to build the code in README are as misleading as they could be.

**Steps to reproduce:**

Simply read the README :)

**Expected behavior:**
- Fork the repo
- Clone my own fork
- Set upstream to pull changes as and when needed
- No errors observed in Gradle build.

**Observed behavior:**
- Clone the original repo
- Errors will appear in Gradle build

**Device and Android version:**

Any

**Screenshots:**

![image](https://user-images.githubusercontent.com/49490887/70040586-cd098700-15e1-11ea-8739-d0920d8347c7.png)

**Comment by jsahil730** [comment]
@luckyman20 Why do we have so many branches here as redesign, dev_resign, is someone supposed to work on them?

**Comment by luckyman20** [comment]
@jsahil730 redesign branch was created when we redesigned the whole app to make it look more attractive and make sure it is according to Material guidelines, I think there are some PRs still left to merged into this branch. I don't know exactly about `dev_redesign` maybe @ankurs287 might be able to give more insights on that.

We cannot give you write access as of now, you can surely review them and drop comments on issues and PRs, this way it will save lots of mentors' time and will give you a better overview of the project.

**Comment by Bhavnaharitsa** [comment]
@jsahil730 @luckyman20 Could I work on it?

**Comment by jsahil730** [comment]
Yeah sure, please also resolve the 'google sign-in failing' issues, if any. @Bhavnaharitsa

**Comment by Bhavnaharitsa** [comment]
Sure

**Comment by luckyman20** [comment]
@Bhavnaharitsa Try to modify README file accordingly.

@jsahil730 Google Sign-in issue is a different issue and we should address it separately.

**Comment by Bhavnaharitsa** [comment]
I think this issue is solved so it should be closed now @jsahil730
