### ISSUE TITLE
App Crashes when trying to sign up without Google Account

### ISSUE THREAD

**Issue by luckyman20** [openMF/mobile-wallet#58]
**Summary:**

The App crashed when I tried to sign up without a Google Account.

**Steps to reproduce:**

Login -> Register a Account -> Uncheck the checkbox of Google Account **_(important)_** -> Click on Register

**Expected behavior:**

I expected that it will take me to a screen where I can fill in my details and register myself.

**Observed behavior:**

The App crashed when I tried to Register account. 

**Device and Android version:**

Pixel 2 Android Marshmallow (Android Emulator)

**Comment by ankurs287** [comment]
@luckyman20 Try signing up again. It has been fixed now. Let me know if the issue stills occurs.
