### ISSUE TITLE
Bug:  Unnecessary Toast In FAQ Section

### ISSUE THREAD

**Issue by rachittt** [openMF/mobile-wallet#586]
**Summary:**
On clicking the list items of the FAQ section, a toast message is being displayed.

**Steps to reproduce:**
FAQ -> Click on any Question

**Expected behavior:**
No toast should be shown as it does not look good from the eyes of the user.

**Observed behavior:**
A toast is displayed with some irrelevant text in it.

**Device and Android version:**
Android 9, Mi A2
**Screenshots:**
![issue](https://user-images.githubusercontent.com/44428198/70388209-b645a480-19d4-11ea-91eb-9c0ab3620358.png)

**Comment by rachittt** [comment]
@luckyman20 What do you think about it ? Can i fix it ?

**Comment by luckyman20** [comment]
@rachittt Go ahead!

**Comment by jsahil730** [comment]
Why is a toast needed here?

**Comment by luckyman20** [comment]
@jsahil730 You are actually right. We can remove the toast here.

@rachittt Please modify the issue accordingly and then solve it.
