### ISSUE TITLE
Content not clearly visible in split screen mode

### ISSUE THREAD

**Issue by akkywadhwa** [openMF/mobile-wallet#590]
**Summary:**
Content is not clearly visible in split screen mode.

**Steps to reproduce:**
1. Open the app and login to account. 
2. Switch to split screen mode.
3. Navigate to finance section
4.  Click on merchants.

**Expected behavior:**
Content must be clearly visible.

**Observed behavior:**
Screenshot Below

**Device and Android version:**
Samsung J5 Prime and 8.0.0 

**Screenshots:**
![Screenshot_20191211-171924_Mifos Pay](https://user-images.githubusercontent.com/666752/70619723-9cf26180-1c3b-11ea-9909-b6149c0345e0.jpg)

**Comment by luckyman20** [comment]
@akkywadhwa We haven't made this app compatible for split screen neither we plan to do so because I don't think any user would take risk of operating the app into split screen and do the transactions and stuff. Still, I would keep this open for discussion.

**Comment by akkywadhwa** [comment]
> 
> 
> @akkywadhwa We haven't made this app compatible for split screen neither we plan to do so because I don't think any user would take risk of operating the app into split screen and do the transactions and stuff. Still, I would keep this open for discussion.

@luckyman20 Different payment apps like PayTm keep support of split screen because these are useful in case of copying account numbers, ifsc code and other details. Usually in such cases, pasting the details is not allowed. For smooth user experience one of the both things(pasting details or split screen) should work. You thoughts?

**Comment by akkywadhwa** [comment]
Also, @luckyman20 could you please let me know what type of issues we are focusing on for this project?

**Comment by rachittt** [comment]
@akkywadhwa hey, I believe that there exists a lot of other issues that we should solve before actually worrying about the split screen mode as it is hardly used by the users for any payments app. We should right now focus more on the bug fixes, functionality and design and in later stages if the Mifos team decides, then make it compatible for split screen mode. Does it make sense to you ?

**Comment by luckyman20** [comment]
Closing this issue as we do not support split screen as of now.
