### ISSUE TITLE
User can continue sign in with empty OTP

### ISSUE THREAD

**Issue by harshshinde07** [openMF/mobile-wallet#591]
**Summary:**

The user can continue his registration even without entering the OTP

**Steps to reproduce:**

 - Open the app
 - Click on `Create one`
 - Enter mobile number and click button beside it
 - Don't enter the OTP and click on the blue `fab` to continue the signup process

**Expected behavior:**

The app should only continue the registration process if the OTP is valid and not empty

**Observed behavior:**

The app continues user registration by going to the next screen

**Comment by jsahil730** [comment]
@harshshinde07 Since this app is still under development, we haven't yet included APIs for sending and verifying OTPs, however if you're interested in the same, I would request you to go ahead and create a PR incase you're working on it.

**Comment by luckyman20** [comment]
@jsahil730 @harshshinde07 We don't have APIs available for sending OTPs right now so this issue is not relevant as of now.
