### ISSUE TITLE
App crashing while switching to spilt screen

### ISSUE THREAD

**Issue by akkywadhwa** [openMF/mobile-wallet#592]
**Summary:**
App crashing while switching to split screen from merchant screen.

**Steps to reproduce:**
1. Open the app and login to account. 
2. Navigate to finance section
3. Click on merchants.
4. Switch to split screen
 
**Expected behavior:**
App must not crash.

**Observed behavior:**
GIF Below

**Device and Android version:**
Samsung J5 Prime and 8.0.0 

**Screenshots:**
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/666752/70620861-50f4ec00-1c3e-11ea-9f94-b5a92962e456.gif)

**Comment by amit6663** [comment]
@akkywadhwa can I work on this issue?

**Comment by luckyman20** [comment]
Closing this as discussed in #590
