### ISSUE TITLE
Feature Request: Take Profile Picture

### ISSUE THREAD

**Issue by akkywadhwa** [openMF/mobile-wallet#601]
**Summary:**
Taking profile picture while setting it is one of the standard features of android mobile application. 

Screenshots of other apps having similar feature:
![Screenshot_20191213-135528_Android System](https://user-images.githubusercontent.com/666752/70785776-3727e600-1db1-11ea-85ba-bd17288a111b.jpg)

**Comment by akkywadhwa** [comment]
@luckyman20 Can I start working on this issue?

**Comment by akkywadhwa** [comment]
@shiv07tiwari What are your thoughts on this? Can I start working on this?

**Comment by ReCodee** [comment]
@devansh-299 @luckyman20  is this issue relevant? can I work on this issue?

**Comment by devansh-299** [comment]
Seems relevant to me. But as far as I know, we still do not have the back-end integration to save the user's image, so at the moment all you can do is add `intent` for the camera

**Comment by ReCodee** [comment]
Thanks, then I'll just add intent for the camera.
