### ISSUE TITLE
bug: Wrong error message while sending money using Mobile Number

### ISSUE THREAD

**Issue by rachittt** [openMF/mobile-wallet#607]
**Summary:**
If you try to transfer money using Mobile Number, a Snackbar appears with a wrong error message.

**Steps to reproduce:**
Payments -> Send -> Mobile Number -> Add an amount -> Type the mobile number -> Submit

**Expected behavior:**

An error message saying "Error finding Mobile Number" should be displayed.

**Observed behavior:**

An error message saying "Error finding Virtual Payment Address" is displayed.

**Device and Android version:**
Mi A2
Android 9 Pie

**Screenshots:**
![WhatsApp Image 2019-12-16 at 21 30 16](https://user-images.githubusercontent.com/44428198/70921976-4d50d300-204b-11ea-95ce-07d1d77569bf.jpeg)

**Comment by mayankwadhwani** [comment]
Is the issue still open? I'll like to take this up

**Comment by luckyman20** [comment]
@mayankwadhwani There is already a PR for it.
