### ISSUE TITLE
add travis CI commands in Readme

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#618]
**Summary:**

In Readme we don't have commands for Travic CI like spotless, check, debug which would be helpful when new contributors get stuck when Travis CI fails. 
I think we should have some Travis CI commands which helps contributors fix those errors when Travis CI doesn't work

**Comment by laxyapahuja** [comment]
I think the easier alternative is to add a guide on how to run a Gradle Build Check locally.
The guide can have commands like ```./gradlew check``` and can suggest ways in which a contributor can find errors.

**Comment by Bhavnaharitsa** [comment]
Yes, that's what I meant🙂

**Comment by Bhavnaharitsa** [comment]
@luckyman20 Sir, we can close this issue
