### ISSUE TITLE
feat: search option on merchants

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#630]
**Summary:**
There are too many merchants and no search option for them. When a user wants to search for a merchant, he/she has to scroll down all the way.

**Steps to reproduce:**
1. Go to merchants fragment
2. See the merchants
There is no search option

**Comment by shiv07tiwari** [comment]
@Bhavnaharitsa This is already added in https://github.com/openMF/mobile-wallet/pull/556.
