### ISSUE TITLE
Bug: Adding non-integers as Mobile Number

### ISSUE THREAD

**Issue by rachittt** [openMF/mobile-wallet#632]
**Summary:**

The app let's you add Non integers in the Mobile Number `editText`. Which is not required in an `editText` concerning Mobile Number.

**Steps to reproduce:**

Payments -> Send -> Mobile Number -> Add non-integers

**Expected behavior:**

The editText should not allow adding non-integer values.

**Observed behavior:**

The app allows adding things like decimal points.

**Device and Android version:**

Mi A2
Android 9.0 Pie 

**Screenshots:**

![WhatsApp Image 2019-12-31 at 15 05 01](https://user-images.githubusercontent.com/44428198/71617472-44323b00-2be1-11ea-999e-258cbd778abe.jpeg)

**Comment by laxyapahuja** [comment]
@luckyman20 this can be closed now.
