### ISSUE TITLE
Latest added cards are not shown first

### ISSUE THREAD

**Issue by refactor-droidyy** [openMF/mobile-wallet#645]
**Summary:**

While adding a card the latest card is shown at the top in the list.

**Steps to reproduce:**

Launch the app.
Navigate to finance section
Navigate to cards section.
Add cards 

**Expected behavior:**

The list of cards should contains latest and newly added cards at the top.

**Observed behavior:**

Currently the list contains previously added cards at the top. 

**Device and Android version:**

Device Redmi 4A
Android Version Nougat 7.0

**Comment by luckyman20** [comment]
@refactor-droidyy This thing can be handled by backend.
