### ISSUE TITLE
feat: Adding Scroll at Login Screen

### ISSUE THREAD

**Issue by 991rajat** [openMF/mobile-wallet#650]
**Scroll at Login Screen**
The devices with screen size less than 5inch require to click out of the keyboard to enter credentials. Users cannot scroll down.

**Device and Android version:**
Android 7.1.2
Device Moto E2

**Screenshots:**

![GIF-200115_222206](https://user-images.githubusercontent.com/38184186/72454084-363a0800-37e6-11ea-88f5-a4884b241679.gif)

**Would you like to work on this issue?**

**Comment by 991rajat** [comment]
I would Like to work on this issue.

**Comment by OussEmaDevCode** [comment]
@991rajat The user can just click on the next button next to the space bar
