### ISSUE TITLE
fix: UI and Input Limit in Mobile Number section in Payment

### ISSUE THREAD

**Issue by 991rajat** [openMF/mobile-wallet#651]
**UI and Input Limit in Mobile Number section in Payment**

**Fixes**
Limit to the length of the mobile number must not exceed 10 digits.
Mobile No should be on the left-hand side.
**Improvements Suggested:**
Adding Ruppe symbol in Amount Input Layout.

**Device and Android version:**
Device Moto E2
Android .1.2

**Screenshots:**
![Screenshot_20200115-231509](https://user-images.githubusercontent.com/38184186/72458040-d9425000-37ed-11ea-9795-882307fbc670.png)

**Would you like to work on this issue?**

**Comment by 991rajat** [comment]
I would like to work on this issue.

**Comment by OussEmaDevCode** [comment]
The app doesn't only handle Rupees, it handles a big number of other currencies depending on the account, so instead of "Adding Ruppe symbol in Amount Input Layout" in the issue message, it should be "Adding currency symbol in Amount Input Layout"

**Comment by 991rajat** [comment]
OK @OussEmaDevCode  and what about the limit on the mobile number is it required?

**Comment by OussEmaDevCode** [comment]
The International Telecommunication Union sets the maximum length to 15 digits for telephone numbers except from that the app uses OTP verification for phone numbers so it'll be useless to implement that.

**Comment by 991rajat** [comment]
So fixing UI is only left out.

**Comment by OussEmaDevCode** [comment]
Well, I believe there are still problems with the UI you just have to find the right one !!

**Comment by 991rajat** [comment]
Yes, Mobile No should appear on left and the hint mobile number is not well balanced.

**Comment by Bhavnaharitsa** [comment]
@OussEmaDevCode @991rajat The focus is not on UI anyway

**Comment by Bhavnaharitsa** [comment]
> The International Telecommunication Union sets the maximum length to 15 digits for telephone numbers except from that the app uses OTP verification for phone numbers so it'll be useless to implement that.

We could always add a country code and alter the length according to the country code

**Comment by 991rajat** [comment]
Yes @Bhavnaharitsa, since a person belongs to a country will transfer funds to the person residing on the same country altering length for every country is a bit hectic and not so feasible. What we could do is to add an upper limit to a mobile number (a range of length) before the person hits enter he could know he entered a wrong number @OussEmaDevCode

**Comment by rachittt** [comment]
@991rajat @OussEmaDevCode hey, I am not quite sure but I remember having a word with a project maintainer where I was told that the currency symbol which we are going to use for Mifos Pay is going to be USD and/or Rupees.

**Comment by rachittt** [comment]
also, the issue of input limit has been fixed in #629.

**Comment by 991rajat** [comment]
@rachittt  What about the UI Mobile No should appear on left and the hint mobile number is not well balanced.

**Comment by rachittt** [comment]
> @rachittt What about the UI Mobile No should appear on left and the hint mobile number is not well balanced.

It has been solved in #384. Though, the maintainers have not reviewed it yet.
