### ISSUE TITLE
Add limit and counter for card number

### ISSUE THREAD

**Issue by refactor-droidyy** [openMF/mobile-wallet#652]
**Summary:**

While adding a new card ,the card number does'nt have limit like CVV number has.

**Steps to reproduce:**

Navigate to Finance section 
Try to add card.

**Expected behavior:**

Usuallly the card number can vary from 16 to 19 digit so the maximum length should be set as the same .Also there should be a counter that keep how much digit of card are entered.

**Observed behavior:**

Curretly the user can enter card number of any length.

**Device and Android version:**

Android Device  - Redmi 4A.

**Comment by luckyman20** [comment]
We already have an utility class for validation of card number. We have just disabled it for testing purposes.
