### ISSUE TITLE
Fix : Limiting OTP length to 6 or 8 during registration.

### ISSUE THREAD

**Issue by jatinsachdevame** [openMF/mobile-wallet#656]
**Summary:** The length of OTP is not limited during registration. So a user can enter any number of digits. It should be limited to max length of 6 or 8.

**Expected behavior:**
![Screenshot_20200119-142748_Mifos Pay](https://user-images.githubusercontent.com/22510309/72678016-12b5dc80-3ac8-11ea-8601-7a917330e085.jpg)

**Observed behavior:**

![Screenshot_20200119-140653_Mifos Pay](https://user-images.githubusercontent.com/22510309/72677976-bd79cb00-3ac7-11ea-91e9-de0d7bdc54b9.jpg)

**Comment by jatinsachdevame** [comment]
I would like to work on this issue.

**Comment by luckyman20** [comment]
@jatinsachdevame Go ahead. Make sure you tested this on `dev` branch.

**Comment by luckyman20** [comment]
Fixed in #662
