### ISSUE TITLE
Expedite Input Type for Change Passcode

### ISSUE THREAD

**Issue by drish1001** [openMF/mobile-wallet#66]
**Summary:**

Expediting input type for ```Change Passcode```

**Steps to reproduce:**

1. Go to ```Profile```
2. Click on ```Change Passcode```

**Expected behavior:**

On clicking Text field for ```Change Passcode``` Numeric keyboard will appear.

**Observed behavior:**

On clicking Text field for ```Change Passcode``` Alphanumeric keyboard will appear. (Where passcode can only be a numeric value.)

**Device and Android version:**

Redmi Note 5 Pro (WHYRED)
MIUI Global 9.6
Android Oreo 8.1.0

**Screenshots:**
![ezgif com-resize 2](https://user-images.githubusercontent.com/36307309/47567565-86f8e300-d94c-11e8-9e17-87afeb3969f9.gif)

**Comment by drish1001** [comment]
May I please work on this issue?

**Comment by ankurs287** [comment]
@drish1001 The appropriate way to change the passcode is to direct the user to mifos-passcode setup again as done while first login.

**Comment by manddy** [comment]
@drish1001  are you working on this ?

**Comment by drish1001** [comment]
Yes, I'm sorry wasn't able to update about my work. I will be doing that
soon.

**Comment by ankurs287** [comment]
@drish1001 You are required to re-direct the user to `mifos-passcode` setup (One when user sees after logging in)

**Comment by PraneethVankayala** [comment]
@drish1001 still you are working on this issue?

**Comment by luckyman20** [comment]
This issue is resolved now.
