### ISSUE TITLE
fix: Add screen shots of the entire app in Readme.md file

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#661]
**Summary:**
The Readme of the app still misses a lot of screen shots of the app. 
We can show many of our fragments.
I want to add the rest of the pages in the screenshot section of Readme

**Comment by luckyman20** [comment]
Don't add in Readme, instead make a new page and provide a link in Readme.

**Comment by Bhavnaharitsa** [comment]
Okay!
