### ISSUE TITLE
Cannot find Symbol

### ISSUE THREAD

**Issue by sreyans01** [openMF/mobile-wallet#664]
**Summary:**

Cannot find symbol class NumberParseException , PhoneNumberUtil , Phonenumber
in org/mifos/mobilewallet/mifospay/payments/ui/RequestFragment.java.

**Steps to reproduce:**

Try to build the project after opening the above fragment.

**Observed behavior:**

The gradle build ended with 3 errors, when I was going to install the app on my device Lenovo Vibe K5 plus.

**Comment by Bhavnaharitsa** [comment]
Are you on the dev branch?

**Comment by luckyman20** [comment]
@sreyans01 Please make sure you are testing on dev branch.

**Comment by sreyans01** [comment]
Sorry , I forgot to use git stash before changing the branch.Now, it worked after stashing and changing the branch.
