### ISSUE TITLE
feat: Need to add email validator in edit profile

### ISSUE THREAD

**Issue by 991rajat** [openMF/mobile-wallet#665]
**Need to add email validator in edit profile:**

**Steps to reproduce:**
In Edit Profile

**Screenshots:**
![Screenshot_20200122-215631](https://user-images.githubusercontent.com/38184186/72912760-1fedf800-3d62-11ea-8054-8aee7bb0eeed.png)
**Would you like to work on this issue?**
Yes

**Comment by jatinsachdevame** [comment]
A PR #598 is already submitted for the same and is yet to be reviewed. Make sure to test issues in PRs and issues as well.

**Comment by 991rajat** [comment]
Yep sure @jatinsachdevame
