### ISSUE TITLE
Blank screen while loading transactions history

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#668]
**Summary:**

Loading transaction history takes a decent amount of time on slow internet connections, till the data is loaded some sort of loading screen should be displayed. Currently a blank screen is shown which should not be there

**Steps to reproduce:**

* Open the app
* See that loading transaction history on HomeFragment takes some time

**Expected behavior:**

A loading screen should have been displayed till the loading data is being completed

**Observed behavior:**

Currently blank screen is being shown 

**Device and Android version:**

Xiaomi PocoF1
Andorid9
Stock Rom

**Comment by devansh-299** [comment]
@shiv07tiwari @luckyman20 can I work on this issue?

**Comment by shiv07tiwari** [comment]
@devansh-299 can you please attach a screenshot of the blank screen

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 can you please attach a screenshot of the blank screen

![GIF-200126_152055](https://user-images.githubusercontent.com/46667021/73133513-b61a6a80-404f-11ea-9246-a890d3d2ee14.gif)

@shiv07tiwari I was planning to use https://github.com/sharish/ShimmerRecyclerView library , is this a good idea

**Comment by shiv07tiwari** [comment]
I think adding a simple loading icon would work. We should avoid using external libraries.

**Comment by devansh-299** [comment]
> I think adding a simple loading icon would work. We should avoid using external libraries.

Ok thanks , working on it
