### ISSUE TITLE
SplashScreen

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#669]
**Summary:**

Currently a blank white screen is shown during the cold start. A splash screen can be added

**Steps to reproduce:**

* Open the app
* See the blank screen appearing before the passcode screen

**Observed behavior:**

A blank white screen is being shown

**Device**

Xiaomi PocoF1
Android 9
Stock rom

**Comment by devansh-299** [comment]
@shiv07tiwari @luckyman20 can I work on this issue?

**Comment by Bhavnaharitsa** [comment]
The point of focus is not UI, but anyway please ask the mentors

**Comment by rachittt** [comment]
adding a simple animated splash screen looks like a good option to me.

**Comment by devansh-299** [comment]
@Bhavnaharitsa @rachittt thank you for your opinions . Just waiting for the mentors of this repository for their views

**Comment by laxyapahuja** [comment]
I think we all should work on a single Mifos splash screen that can be used for every Mifos app. That way, all Mifos' app will have the same splash screen which will give identity to the brand.

**Comment by devansh-299** [comment]
> 
> 
> I think we all should work on a single Mifos splash screen that can be used for every Mifos app. That way, all Mifos' app will have the same splash screen which will give identity to the brand.

Nice idea ! lets see what the mentors have to say

**Comment by luckyman20** [comment]
@laxyapahuja That is not possible since now we have different UIs and theme of every app. I think there is already a issue on splash screen (maybe closed) please check that.

**Comment by devansh-299** [comment]
Duplicate of #354 (closed)
So should I work on it ?

**Comment by Bhavnaharitsa** [comment]
@devansh-299 Are you still on this? Because, I see there is a inactivity. If else, I would like to work on it.
