### ISSUE TITLE
fix : App crashes when pausing EditProfile Activity in dev branch.

### ISSUE THREAD

**Issue by jatinsachdevame** [openMF/mobile-wallet#670]
**Summary:** In Edit Profile Activity (of dev branch), when user clicks on change password and change passcode button or simply press back or home button, app crashes due to dialogBox.dismiss() in onPuase() method.

This issue is in dev branch as it is using our class dialogbox. Master branch works fine since it is using inner class.
When we create DialogBox dialogBox = new DialogBox(); object in edit profile activity. It creates the object of Alert Dialog in DialogBox class.
and when we click on change password/passcode button, we are checking whether dialogBox is null or not. It is not null, but since we didn't created a dialog hence the object alertDialog in DialogBox class is null. Therefore it is crashing the app on calling dialogBox.dismiss(). In background it is calling dismiss() method on null alertDialog object.

**Steps to reproduce:** Install dev branch app and click on change password or change passcode button, or back or home button while in Edit Profile Activity.

**Device and Android version:** Every device.

**Comment by jatinsachdevame** [comment]
I want to resolve this issue.

**Comment by Bhavnaharitsa** [comment]
@jatinsachdevame Could you share the logs at the point when app crashes?

**Comment by jatinsachdevame** [comment]
> @jatinsachdevame Could you share the logs at the point when app crashes?

Here you go @Bhavnaharitsa 
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AlertDialog.dismiss()' on a null object reference
        at org.mifos.mobilewallet.mifospay.utils.DialogBox.dismiss(DialogBox.java:45)
        at org.mifos.mobilewallet.mifospay.editprofile.ui.EditProfileActivity.onPause(EditProfileActivity.java:439)`
