### ISSUE TITLE
fix : Disabling save button in change password activity till password and confirm password doesn't match.

### ISSUE THREAD

**Issue by jatinsachdevame** [openMF/mobile-wallet#672]
**Summary:** Disabling save button in change password activity till password and confirm password doesn't match.

**Expected behavior:**
![ss2](https://user-images.githubusercontent.com/22510309/73121404-ae9b8880-3f9f-11ea-91e3-ef0d98524a20.jpg)

**Observed behavior:**
![ss1](https://user-images.githubusercontent.com/22510309/73121409-bfe49500-3f9f-11ea-9c08-40aa1e56b037.jpg)

**Comment by jatinsachdevame** [comment]
I want to work on this issue @luckyman20 @shiv07tiwari

**Comment by Bhavnaharitsa** [comment]
Also a probable duplicate of #643

**Comment by jatinsachdevame** [comment]
Hey @Bhavnaharitsa , I think you referenced on the wrong issue.

**Comment by Bhavnaharitsa** [comment]
@jatinsachdevame Oops..I'm sorry!
I got confused

**Comment by jatinsachdevame** [comment]
That's all right.

**Comment by luckyman20** [comment]
Go ahead.
