### ISSUE TITLE
fix: add scroll bar in home activity under transaction history

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#674]
**Summary:**

There is no scroll bar in Transaction history as the list goes on and on, it is important to have a scroll bar.

![Screenshot_20200126-114305_Mifos Pay (1)](https://user-images.githubusercontent.com/37215508/73131812-be66ab80-4037-11ea-80b1-e0fbc0af38ac.jpg)

**Comment by luckyman20** [comment]
Solved in #676
