### ISSUE TITLE
fix: no input type in edit profile email, username etc.

### ISSUE THREAD

**Issue by 991rajat** [openMF/mobile-wallet#675]
**There is no input type in the email, username, VPA.**

**Steps to reproduce:**
Layout > activity_edit_profile

**Suggestions**
Need to add input type for good UX.
This will also add a minor check on the UI side.

**Screenshots:**

![Screenshot (14)](https://user-images.githubusercontent.com/38184186/73131871-8d3aab00-4038-11ea-833f-1b777d396fe9.png)

**Would you like to work on this issue?**

**Comment by 991rajat** [comment]
YES

**Comment by laxyapahuja** [comment]
can I work on this? @luckyman20
