### ISSUE TITLE
Feature: Adding option to set maximum transaction limit

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#685]
**Summary:**

Currently user can send any amount of money (if he/she has that much amount of money) . For digital transactions, allowing transferring of large amounts is generally not suggested.

**Steps to reproduce:**

* Go to payments ->Send
* See there's no limit on entering amount

**Expected behavior:**

An upperbound must be there for any transaction made

**Observed behavior:**

Currently there's no upperlimit

**Device and Android version:**

Xiaomi PocoF1
Android 9
Stock Rom

**Comment by devansh-299** [comment]
@shiv07tiwari @luckyman20  what are your view about this ?

**Comment by luckyman20** [comment]
@devansh-299 This can be altered at the time of release. We are in `test` mode as of now.
