### ISSUE TITLE
Incorrect Passcode display in UI

### ISSUE THREAD

**Issue by PraneethVankayala** [openMF/mobile-wallet#69]
**Summary:**

When we open the app it must display incorrect passcode when we type the incorrect passcode

**Steps to reproduce:**

1. Open the app
2. A display appears to enter passcode

**Expected behavior:**

To show incorrect passcode when we entered incorrectly

**Observed behavior:**

When the incorrect passcode is entered nothing is displayed

**Device and Android version:**

Device-Xiaomi Redmi Note 4 (Mido)
Android Version-7(Nougat)

**Screenshots:**
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/40353347/47576926-48225780-d963-11e8-8de3-dc344bee7c80.gif)

**Comment by PraneethVankayala** [comment]
May I work on this issue? please

**Comment by codepoet2017390** [comment]
@luckyman20  please close this issue. It has been solved
