### ISSUE TITLE
bug: useless toast messages in FAQs

### ISSUE THREAD

**Issue by jddeep** [openMF/mobile-wallet#693]
**Summary:**

bug: useless toast messages in FAQs.
Toast message is shown on clicking the next question about the previous question has been collapsed whereas in reality that question's answer still remains open.

**Steps to reproduce:**

Open App -> FAQ

**Expected behavior:**

Prevent those meaningless toast messages.

**Observed behavior:**

**Device and Android version:**

Android 9

**Screenshots:**

<img src="https://user-images.githubusercontent.com/43133646/73358541-d7d05780-42c4-11ea-9094-acfac494bd3d.png" width=300/>

**Comment by jddeep** [comment]
@luckyman20 @shiv07tiwari I would like to work on this. Thoughts?

**Comment by rachittt** [comment]
solved in #622
