### ISSUE TITLE
bug: mobile length in mobile verification

### ISSUE THREAD

**Issue by 991rajat** [openMF/mobile-wallet#697]
**Summary:**
Mobile No can be of variable length. Max Limit must be increased to at least 15.

**Steps to reproduce:**

Mobile Verification Activity

**Screenshots:**
![Screenshot (20)](https://user-images.githubusercontent.com/38184186/73717346-8c440080-473f-11ea-9db2-f60534244e3d.png)
**Would you Like to work on this issue?**
YES

**Comment by rachittt** [comment]
@991rajat as far as I know, the countries in which our app is going to work need only 10 characters.
