### ISSUE TITLE
Adding transition effect to UI for Home Activity

### ISSUE THREAD

**Issue by drish1001** [openMF/mobile-wallet#70]
**Summary:**

Transition effect between the ```Home```, ```Profile``` and ```Transfer```

**Steps to reproduce:**

Go to ```Home```

**Expected behavior:**

On swiping left or right new activity should appear. If current activity is ```Home``` on sliding left, ```Tranfer``` activity should be displayed.

**Observed behavior:**

On sliding, doesn't switch to new activity.

**Device and Android version:**

Redmi Note 5 Pro (WHYRED)
MIUI Global 9.6
Android Oreo 8.1.0

**Gif:**

![ezgif com-resize 4](https://user-images.githubusercontent.com/36307309/47612416-ee737780-da9f-11e8-9e9f-37d2cdf7ca5a.gif)

**Comment by drish1001** [comment]
May I please work on this feature?

**Comment by luckyman20** [comment]
This has been implemented by @letelete already.
