### ISSUE TITLE
api problem

### ISSUE THREAD

**Issue by khalidabuhayea** [openMF/mobile-wallet#704]
api return timeout
https://demo.openmf.org/fineract-provider/api/v1/self/authentication?username=ggg&password=rrrr

**Comment by Bhavnaharitsa** [comment]
Could you specify and elaborate the issue more?

**Comment by khalidabuhayea** [comment]
@Bhavnaharitsa  the api not working !

**Comment by Bhavnaharitsa** [comment]
Okay!

**Comment by khalidabuhayea** [comment]
what is the problem ?

**Comment by khalidabuhayea** [comment]
what is the problem?

**Comment by Bhavnaharitsa** [comment]
@khalidabuhayea whose problem?

**Comment by khalidabuhayea** [comment]
why there is no response from the api ?
https://demo.openmf.org/fineract-provider/api/v1/self/authentication?username=ggg&password=rrrr

**Comment by refactor-droidyy** [comment]
@khalidabuhayea there is change in current demo URL just change the API_ENDPOINT and API_ENDPOINT_SELF to "demo.mifos.io" in  .\mobile-wallet\core\src\main\java\org\mifos\mobilewallet\core\data\fineract\api\BaseURL
