### ISSUE TITLE
fix: senseless names for ids in activity_login

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#706]
**Summary:**
<TextView
            android:id="@+id/textView2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="0dp"
            android:layout_marginLeft="0dp"
            android:layout_marginEnd="@dimen/marginBetweenWords"
            android:layout_marginRight="@dimen/marginBetweenWords"
            android:text="@string/don_t_have_an_account"
            android:textColor="@color/colorTextSecondary" />

       <TextView
            android:id="@+id/textView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/create_one"
            android:textColor="@color/colorAccent" />

These views have senseless ids and ids could be changed according to it's purpose.

**Comment by haran2248** [comment]
Is this issue valid?Can i work on this issue?

**Comment by devansh-299** [comment]
> Is this issue valid?Can i work on this issue?

Yes, go ahead. Also please do not limit this to `activity_login` only and do this task for all the ids for which this issue applies.
