### ISSUE TITLE
fix: no scroll bar is transaction history

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#712]
**Summary:**

When there are many transaction histories, it is good to have scroll bars so that the user will know when the history will end.

**Comment by deepak-prajapatii** [comment]
@Bhavnaharitsa can i work on this issue?

**Comment by rutvik-panchal** [comment]
We can close this issue, It's already solved #720

**Comment by Prashant830** [comment]
it's solved.
@devansh-299  please close it.
