### ISSUE TITLE
Mismatch alignment in input field for Mobile and Amount.

### ISSUE THREAD

**Issue by refactor-droidyy** [openMF/mobile-wallet#714]
**Summary:**

Currently the the alignment for input text in Send Activity for Amount and Moble Number inputs are different.

**Steps to reproduce:**

Launch the app.
Navigate to Payment Section to Send Section.
Switch to mobile select transfer method as mobile.

**Expected behavior:**

Alignment should be same for both the input fields.

**Observed behavior:**

Mismatch alignment inside the input text field for mobile number and Amount.

**Device and Android version:**

Android Device - Redmi 4A
Android Version - Nougout 7.0.1

**Screenshots:**

![Screenshot_2020-02-07-23-15-08-049_org mifos mobilewallet mifospay](https://user-images.githubusercontent.com/44283521/74052466-ec68ca00-49ff-11ea-9614-01e2bcf0dd6d.png)

**Comment by refactor-droidyy** [comment]
@luckyman20 can i work on this ?

**Comment by rachittt** [comment]
@refactor-droidyy It has been solved in #384. Though, the maintainers have not reviewed it yet.

**Comment by Grandolf49** [comment]
@refactor-droidyy Please close this issue as it has already been solved
