### ISSUE TITLE
feat : Add mifos logo in passcode activity

### ISSUE THREAD

**Issue by indracs97** [openMF/mobile-wallet#723]
**Summary:**

Add mifos logo in passcode activity

**Steps to reproduce:**

**Expected behavior:**

**Observed behavior:**

**Device and Android version:**

Motorola one vision 
Android Q ( version 10)

**Screenshots:**
Before
![Screenshot_20200217-122518](https://user-images.githubusercontent.com/20751314/74630520-c4f0ca80-5180-11ea-96ca-8d04971afeae.png)
After
![Screenshot_20200217-122808](https://user-images.githubusercontent.com/20751314/74630626-f8cbf000-5180-11ea-98bf-653074412011.png)

**Comment by luckyman20** [comment]
Reason mentioned in #724
