### ISSUE TITLE
Specific transaction layout

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#752]
**Summary:**

Currently the specific transaction layout looks cluttered and unclear because of divider between an elements of an item(transaction) in recyclerview

**Steps to  Reproduce:**
* Go to Payments -> History Tab
* Tap on any transaction -> Bottom sheet appears
* Tap on sender/receiver image
* Specific Transaction History Fragment opens
* Observer the issue

**Expected behavior:**

This dividing line should be removed as its function should be to distinguish between different transactions

**Screenshots:**

![WhatsApp Image 2020-02-24 at 8 28 45 PM](https://user-images.githubusercontent.com/46667021/75162918-51ccf280-5744-11ea-8e4f-2109983e8f6f.jpeg)

**Comment by luckyman20** [comment]
@devansh-299 Please provide exact steps to reproduce the bug.

**Comment by devansh-299** [comment]
> @devansh-299 Please provide exact steps to reproduce the bug.

Sir, I have updated the Issue statement
