### ISSUE TITLE
TextInputLayout in set amount dialog box

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#756]
**Summary:**

The Set Amount alert dialog box uses `EditText` while at all the other places `TextInputLayout` has been used. This breaks the consistency in the app user interface

**Steps to reproduce:**

*Go to Payments
* Tap on Show code
* Tap on Set Amount 

**Expected behavior:**

`TextInputLayout` should have been used to maintain consistency in app's user interface

**Screenshots:**

![WhatsApp Image 2020-02-24 at 9 25 57 PM](https://user-images.githubusercontent.com/46667021/75168079-54334a80-574c-11ea-9535-cba8d6737819.jpeg)

**Comment by valkyr13** [comment]
@devansh-299 can i work on this?

**Comment by devansh-299** [comment]
> @devansh-299 can i work on this?

yes, please go ahead

**Comment by haran2248** [comment]
Can i work on this issue?

**Comment by valkyr13** [comment]
Go ahead

**Comment by devansh-299** [comment]
Already solved
