### ISSUE TITLE
No empty field validation in MerchantTransferActivity

### ISSUE THREAD

**Issue by dubeyaayush07** [openMF/mobile-wallet#757]
**Summary:**
MerchantTransferActivity does not validate for empty amount field

**Comment by dubeyaayush07** [comment]
I would like to work on this

**Comment by luckyman20** [comment]
@dubeyaayush07 Please mention steps to reproduce.

**Comment by dubeyaayush07** [comment]
@luckyman20 
Steps to Reproduce
Go to Merchant Transfer Activity do not enter anything in the amount field click submit the app crashes because null value is allowed

**Comment by luckyman20** [comment]
How to reach to MerchantTransferActivity? Detailed description is needed.

**Comment by dubeyaayush07** [comment]
![Screenrecorder-2020-03-17-16-37](https://user-images.githubusercontent.com/30518564/76850779-14084900-686e-11ea-8871-0d09ddce0f91.gif)
@luckyman20

**Comment by luckyman20** [comment]
@dubeyaayush07 I am not able to load the merchants only. On which branch and server you are testing this?

**Comment by dubeyaayush07** [comment]
@luckyman20  I am testing on the dev branch I removed KYC fragment from view layout to test this, view layout loads two fragments at once and when fetch fails in the KYC fragment it redirects to the HomeFragment that is why you are not able to access the merchant fragment. I am currently working on fixing this problem in another issue.
