### ISSUE TITLE
Back Button not visible in View Receipt

### ISSUE THREAD

**Issue by anubhav11march** [openMF/mobile-wallet#761]
**Summary:**

The back button is invisible in the view receipt activity.

**Steps to reproduce:**

Go to View Receipt in Transactions History
![WhatsApp Image 2020-02-26 at 7 20 12 PM](https://user-images.githubusercontent.com/42939575/75350894-41944f00-58cd-11ea-8b91-d8ca0e3112c1.jpeg)

**Expected behavior:**

The back button should be visible to the user.

**Device and Android version:**

Huawei Honor 9 Lite  
Android 9.1 (Pie)

**Comment by anubhav11march** [comment]
I am working on this issue.

**Comment by refactor-droidyy** [comment]
@anubhav11march this issue is solved https://github.com/openMF/mobile-wallet/pull/708
 just waiting for maintainers to review .

**Comment by haran2248** [comment]
@refactor-droidyy @devansh-299  can I take up the issue?

**Comment by Prashant830** [comment]
this issue was solved.
@devansh-299  please close it .

**Comment by devansh-299** [comment]
> this issue was solved. @devansh-299 please close it .

Closing this issue as the mentioned problem has already been solved
