### ISSUE TITLE
Feature Request: Add FAQ Section

### ISSUE THREAD

**Issue by luckyman20** [openMF/mobile-wallet#77]
**Summary:**

As of now, there is no FAQ section which would explain about the features of the app or organisation using it.

**Steps to reproduce:**

No steps to reproduce as feature doesn't exists.

**Expected behavior:**

There would be a FAQ section which would clarify about app's features. The FAQ section will be added under settings option in Profile Fragment. Create a button to launch an activity which would display FAQ. Add Dummy questions as of now.

**Observed behavior:**

There wasn't any FAQ section.

**Device and Android version:**

Android Marshmallow Pixel 2 Android Emulator

**Comment by MigDinny** [comment]
Where is supposed to be added the FAQ button? What do you mean by "under settings option"?

I would suggest to pick a question mark icon and put it next to the pencil, on its left. That button would launch the activity. What do you think?

**Comment by ankurs287** [comment]
@MigDinny Yes. You could do that. But don't put all the three options there. Instead create a menu button which shows three options: 1. Edit Profile, 2. Settings, 3. FAQ

**Comment by luckyman20** [comment]
Has been solved in PR #104
