### ISSUE TITLE
fix: back arrow in QRActivity not seen

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#773]
**Summary:**

Due to the change of back arrow color in signup or register activity, the QR code back arrow has also changed. 
We need to add a black arrow for such activities

**Comment by refactor-droidyy** [comment]
@already solved in #708

**Comment by Bhavnaharitsa** [comment]
@refactor-droidyy Oh, sorry! Seems like a long untouched pr

**Comment by Bhavnaharitsa** [comment]
@refactor-droidyy Please get your pr merged. This seems rather important

**Comment by rachittt** [comment]
@Bhavnaharitsa Please avoid making repetitive PRs. Will have to close it for now.
