### ISSUE TITLE
Bottom Navigation bar moves up with keyboard

### ISSUE THREAD

**Issue by dubeyaayush07** [openMF/mobile-wallet#774]
**Summary:**

When inputting values by using keyboard the bottom navigation bar moves up cluttering the UI. I have observed this behaviour does not happen always for example when the server is not responding the navbar stays down but still it's behaviour is finicky.

<img src="https://user-images.githubusercontent.com/30518564/75516324-369f0300-5a22-11ea-9a4b-573ec2994614.jpg" height="60%" width="60%">

**Comment by dubeyaayush07** [comment]
I would like to work on this

**Comment by HaripriyaB** [comment]
I would like to work on this

**Comment by dubeyaayush07** [comment]
There is already a PR for this issue

**Comment by HaripriyaB** [comment]
oh okay
