### ISSUE TITLE
feat: Introduction slides granting permissions from user

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#780]
**Summary:**

Every app has some introduction slides, which makes the app not only aesthetically good but also, gives the user a rough idea about what the app exactly is.
We need to have such introduction slides as well, which would display only during the first time of app installment.

**Comment by Bhavnaharitsa** [comment]
@naman14 @shiv07tiwari @luckyman20 Thoughts please?

**Comment by valkyr13** [comment]
Can I work on this?

**Comment by luckyman20** [comment]
As of now this addition is unnecessary since we are almost unclear about the features we are going to have at the time of release. Also, this would add to the app size too and considering utility of the app it is almost understandable what primary features we have.
