### ISSUE TITLE
Feat: add an option to share transaction receipt deeplink

### ISSUE THREAD

**Issue by dubeyaayush07** [openMF/mobile-wallet#786]
**Summary:**
Currently clicking the receipt link just copies it to the clipboard I think it will be better if we give the user option to share this link (which will include copying it to the clipboard).

**Comment by dubeyaayush07** [comment]
I would like to work on this

**Comment by garvit984** [comment]
@dubeyaayush07 My intentions are not to share the link but to open in browser.
