### ISSUE TITLE
Set Amount Dialog 's Reset Button Behaviour in ShowQr Activity

### ISSUE THREAD

**Issue by refactor-droidyy** [openMF/mobile-wallet#802]
**Summary:**

Set Amount Dialog 's Reset Button Behaviour in ShowQr Activity is like Cancel option.

**Steps to reproduce:**

How can we reproduce again the issue?

Launch the app.
Navigate to Payment->Request->Show OR.

**Expected behaviour:**

The Neutral Button Should be renamed as Cancel Button and Toast should not be displayed "Reset Amount Successfully".

**Observed behaviour:**
The Dialog option Reset Button performs the action of the cancel button.

**Device and Android version:**

Android Version - 9, Pie.
Android Device - Realme 3 Pro

**Screenshots:**
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/44283521/76170501-7eebbd00-61a8-11ea-85c8-d9d536475eec.gif)

**Comment by luckyman20** [comment]
Closing this. Reason mentioned in #803
