### ISSUE TITLE
ProgressBar for transaction details fetching process

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#806]
**Summary:**

Under some conditions, users can experience noticeable time lag b/w when the  transaction details are successfully fetched and the time when they press on a transaction inside `History` Fragment
During this we can display progress bar to notify the user that app is actually fetching the details
Also currently there's no provision for notifying the user if the fetching process somehow got failed

**Steps to reproduce:**

* Go to History Fragment
* Tap on any transaction
* Notice the above highlighted issue

**Device and Android version:**
Xiaomi PocoF1
Android 9
Stock rom

**ScreenRecording:**

(For the second transaction, the fetching process actually failed but the user wasn't notified)

![GIF-200310_132419](https://user-images.githubusercontent.com/46667021/76291784-ce7ad780-62d3-11ea-9f90-367bff5c09d7.gif)

**Comment by asraman9792** [comment]
sir is this issue open can i help ?

**Comment by devansh-299** [comment]
> sir is this issue open can i help ?
@asraman9792 I have already addressed this issue in #809
