### ISSUE TITLE
SpecificTransactionHistory - no progressbar and no error state view

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#808]
**Summary:**

While the app is fetching the specific transactions from the servers, a blank screen is shown which affects the user experience. Also currently there's no code to handle the case when any error occurs while fetching the specific transactions

**Steps to reproduce:**

* Go to transactions -> History
* Tap on any transaction and then tap again to see specific transactions
* Notice the issue mentioned above
* For error state try switching off data then open specific transaction activity
* See that blank screen is shown

**Expected behavior:**

A progress bar etc should have been there to notify that the application is in process of fetching the data and like other fragments a view dedicated to error handling should have been there

**Observed behavior:**

Blank screen is shown for both the cases

**Device and Android version:**

Xiaomi Poco F1
Android 9
Stock rom

**Screen Recording:**
![GIF-200310_143254](https://user-images.githubusercontent.com/46667021/76296980-19e5b380-62dd-11ea-8dbd-a901ad486e54.gif)

**Comment by asraman9792** [comment]
sir is this issue open ?

**Comment by devansh-299** [comment]
> sir is this issue open ?

I have already addressed this issue in #809
