### ISSUE TITLE
feat: scroll to bottom arrow in history fragment

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#812]
**Summary:**

We need to have a scroll to bottom down arrow in transaction history fragment as it will help the users to check their bottom most chats

**Comment by dubeyaayush07** [comment]
Possible duplicate #791

**Comment by Bhavnaharitsa** [comment]
@dubeyaayush07 I meant the history of transactions in home page and the fragment.. 
To whichever the page the other issue is implementing, I shall implement the other one

**Comment by harchani-ritik** [comment]
@Bhavnaharitsa can I work on this?

**Comment by refactor-droidyy** [comment]
@Bhavnaharitsa the same fragments is inflated on both the activity I guess
