### ISSUE TITLE
No intent for Opening Receipt Link in Receipt

### ISSUE THREAD

**Issue by garvit984** [openMF/mobile-wallet#813]
**Summary:**

On clicking the receipt link in the receipt, it does not open the webpage. Only Copy feature works.

**Steps to reproduce:**

1. Select Payments
2. Select History
3. Click on any transaction
4.View Receipt
5. Click on Receipt link
**Expected behavior:**
It should have opened the webpage for receipt
**Observed behavior:**
But it does nothing on clicking.

**Device and Android version:**
Redmi 7A Android 9
**Screenshots:**
![ezgif-3-0b7dce33494b](https://user-images.githubusercontent.com/54365596/76629779-d8ffd000-6564-11ea-8b2a-b09d6273b385.gif)

**Comment by garvit984** [comment]
I'll be working on it.
@naman14

**Comment by dubeyaayush07** [comment]
duplicate #786 please check before creating a new issue

**Comment by garvit984** [comment]
@dubeyaayush07 it is not a duplicate of #786 .There ,your intentions were to share it but here mine are to open in web browser.
