### ISSUE TITLE
fix: no state shown in signup activity

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#818]
**Summary:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37215508/76694021-6b05f680-6693-11ea-898e-a57ea98b2102.gif)

There is no state shown on clicking state in signup activity and it does not accept state even after we type our state or place. 
The states should be shown or else the user should be given an option to atleast type their own state.

**Comment by dubeyaayush07** [comment]
Working fine for me also hyderabad and madurai are not states
<img src="https://user-images.githubusercontent.com/30518564/76736471-dc75a000-678c-11ea-9ddd-eea33a546432.jpg" height="60%" width="60%">

**Comment by Bhavnaharitsa** [comment]
@dubeyaayush07 Yes, I tried with states
 Didnt work
Let me see anyway

**Comment by Bhavnaharitsa** [comment]
> Working fine for me
> <img alt="" width="60%" height="60%" src="https://user-images.githubusercontent.com/30518564/76736471-dc75a000-678c-11ea-9ddd-eea33a546432.jpg">

@dubeyaayush07 Somehow, I am not able to reproduce what you can. I have run and tested the app twice or even thrice. Might be, the API is not getting called. 
Are the end points in your end `demo.mifos.io`? If at all, that has something to do with this

**Comment by dubeyaayush07** [comment]
> > Working fine for me
> > <img alt="" width="60%" height="60%" src="https://user-images.githubusercontent.com/30518564/76736471-dc75a000-678c-11ea-9ddd-eea33a546432.jpg">
> 
> @dubeyaayush07 Somehow, I am not able to reproduce what you can. I have run and tested the app twice or even thrice. Might be, the API is not getting called.
> Are the end points in your end `demo.mifos.io`? If at all, that has something to do with this

Yes, I am using demo.mifos.io as my endpoint still if it is not working for you it is worth investigating maybe we can ask someone else to verify  @jawidMuhammadi @devansh-299

**Comment by Bhavnaharitsa** [comment]
@dubeyaayush07 Cool, thank you

**Comment by devansh-299** [comment]
> > > Working fine for me
> > > <img alt="" width="60%" height="60%" src="https://user-images.githubusercontent.com/30518564/76736471-dc75a000-678c-11ea-9ddd-eea33a546432.jpg">
> > 
> > 
> > @dubeyaayush07 Somehow, I am not able to reproduce what you can. I have run and tested the app twice or even thrice. Might be, the API is not getting called.
> > Are the end points in your end `demo.mifos.io`? If at all, that has something to do with this
> 
> @Bhavnaharitsa Yes, I am using demo.mifos.io as my endpoint still if it is not working for you it is worth investigating maybe we can ask someone else to verify @jawidMuhammadi @devansh-299

@dubeyaayush07 @Bhavnaharitsa its working fine for me too

**Comment by Bhavnaharitsa** [comment]
> > > > Working fine for me
> > > > <img alt="" width="60%" height="60%" src="https://user-images.githubusercontent.com/30518564/76736471-dc75a000-678c-11ea-9ddd-eea33a546432.jpg">
> > > 
> > > 
> > > @dubeyaayush07 Somehow, I am not able to reproduce what you can. I have run and tested the app twice or even thrice. Might be, the API is not getting called.
> > > Are the end points in your end `demo.mifos.io`? If at all, that has something to do with this
> > 
> > 
> > @Bhavnaharitsa Yes, I am using demo.mifos.io as my endpoint still if it is not working for you it is worth investigating maybe we can ask someone else to verify @jawidMuhammadi @devansh-299
> 
> @dubeyaayush07 @Bhavnaharitsa its working fine for me too

Okay, must be some error on my end. Thank you :)
