### ISSUE TITLE
Fix: Change Constants to strings

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#824]
**Summary:**
We have many Constants in our app which are linked to views which might cause issues when we migrate. 
We need to convert them into strings.xml

**Comment by AntonAsmirko** [comment]
Can I work on this issue?

**Comment by Bhavnaharitsa** [comment]
@AntonAsmirko Im sorry, but I'm already working on it. Please find out other issues :)

**Comment by devansh-299** [comment]
There's another issue pointing out the same problem... hence closing this issue
