### ISSUE TITLE
Redesign: Use TextInputLayout instead of EditText in MobileVerification Activity

### ISSUE THREAD

**Issue by ArnavGohil** [openMF/mobile-wallet#825]
In activity_mobile_verification , EditText is used for Mobile Number and OTP instead of TextInputLayout .

**Comment by ArnavGohil** [comment]
@luckyman20  Can I work on this issue ?

**Comment by utsavmajhi** [comment]
I m solving this issue

**Comment by sashank27** [comment]
In my opinion, it is better to use `EditText` in this case than `TextInputLayout`, according to UX. The user already knows that this activity is used for input mobile number, so just a small hint for the input area would be enough.
Also, `TextInputLayout` basically has 2 elements, `TextInputLayout` and `TextInputEditText`, so using it in the minimal sense would prevent excess elements in the parent layout, and improves performance.

**Comment by haran2248** [comment]
Is this issue still relevant?Can i work on this issue?
@ArnavGohil @sashank27 ?

**Comment by haran2248** [comment]
I have made a PR for this issue,pls let me know if this is what you had in mind ,else pls let me what are the other changes to be done.There are no bugs or errors in my PR. './gradlew' runs perfectly in git bash

**Comment by haran2248** [comment]
Why was this issue closed?@ArnavGohil

**Comment by ArnavGohil** [comment]
Check @sashank27's comment - 

> In my opinion, it is better to use `EditText` in this case than `TextInputLayout`, according to UX. The user already knows that this activity is used for input mobile number, so just a small hint for the input area would be enough.
> Also, `TextInputLayout` basically has 2 elements, `TextInputLayout` and `TextInputEditText`, so using it in the minimal sense would prevent excess elements in the parent layout, and improves performance.

**Comment by ArnavGohil** [comment]
> In my opinion, it is better to use `EditText` in this case than `TextInputLayout`, according to UX. The user already knows that this activity is used for input mobile number, so just a small hint for the input area would be enough.
> Also, `TextInputLayout` basically has 2 elements, `TextInputLayout` and `TextInputEditText`, so using it in the minimal sense would prevent excess elements in the parent layout, and improves performance.
