### ISSUE TITLE
Bug: User's profile picture isn't rounded when profile image's changed

### ISSUE THREAD

**Issue by letelete** [openMF/mobile-wallet#83]
**Summary:**

User's profile image should be always rounded.

**Steps to reproduce:**

Dashboard > Profile > Edit Profile > Change profile picture

**Expected behavior:**

Rounded profile image

**Observed behavior:**

The image is a rectangle shape.

**Device and Android version:**

Huawei p10, Android 8.0

**Screenshots:**

![44](https://user-images.githubusercontent.com/18665370/48284421-a705c780-e45f-11e8-9a7c-5d595321e6e4.PNG)

**Comment by ankurs287** [comment]
@letelete Do you want to work on this issue?

**Comment by letelete** [comment]
As soon as I finish the current GCI task I can handle this one.
