### ISSUE TITLE
fix: no intent to the receipt of transacton when viewed from HomeFragment

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#830]
**Summary:**

In HistoryFragment, we can view the receipt and download it too on clicking on the history. but, in Home page we cannot. We need to have that feature too in Home page

**Comment by dubeyaayush07** [comment]
possible duplicate #746

**Comment by Bhavnaharitsa** [comment]
@dubeyaayush07 Oh, thank you! Didn't notice
