### ISSUE TITLE
Fix: Hide add cards when cards are not fetched  

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#834]
**Summary:**

When the existing cards are not fetched, I think we can hide the add card option because the user might not be sure what card he/she already has and might want to see the existing cards before adding a card.

**Comment by AntonAsmirko** [comment]
Can I work on this issue?

**Comment by Bhavnaharitsa** [comment]
@AntonAsmirko Im sorry, but I'm already working on it. Please find out other issues :)
