### ISSUE TITLE
Disable bottom sheet dragging while transfer process is going on

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#844]
**Summary:**

While the transfer the process is going on the customer can drag the bottom sheet and interrupt the process. 

**Steps to reproduce:**

* Go to Payments -> Send tab
* Send money
* Observe that while the transfer process is going on the user can swipe down.

**Expected behavior:**

While the transaction process is going on, the user shouldn't be allowed to drag the bottom sheet

**Observed behavior:**

User can currently drag down the bottom sheet while transfer process is going on

**Device and Android version:**

Xiaomi Poco F1
Android 9
Stock Rom

**Screen Recording:**

![GIF-200322_162710](https://user-images.githubusercontent.com/46667021/77247873-337ee780-6c5b-11ea-9f2d-e8e141b50f23.gif)

**Comment by utsavmajhi** [comment]
Can i work on this?

**Comment by devansh-299** [comment]
> Can i work on this?

I am already working on this

**Comment by utsavmajhi** [comment]
ok
