### ISSUE TITLE
UI glitch in Payment Fragment

### ISSUE THREAD

**Issue by refactor-droidyy** [openMF/mobile-wallet#848]
**Summary:**

The Tabs in Tab layout in Payment Fragment are of creating a Bad UI letting space at the right side of the screen.

**Steps to reproduce:**

On Launching the app navigate to the Payment section.

**Expected behaviour:**

There should be no blank space on the right side in the Tab layout in  Payment Fragment.

**Observed behaviour:**

There is extra space on the right side of the Tab Layout in Payment Fragment.

**Device and Android version:**

Android Version - Android 10
Android Device - POCO X2

**Screenshots:**

![Screenshot_2020-03-22-22-58-26-803_org mifos mobilewallet mifospay](https://user-images.githubusercontent.com/44283521/77256704-e0765600-6c95-11ea-9601-88232d18f633.jpg)

**Comment by rutvik-panchal** [comment]
@devansh-299 @luckyman20 Can i work on this issue?
