### ISSUE TITLE
No login session save if user Skip setting the Passcode

### ISSUE THREAD

**Issue by refactor-droidyy** [openMF/mobile-wallet#850]
**Summary:**

When a user tries to login and skips Setting the Passcode the user session is not saved when the app is closed.

**Steps to reproduce:**

Login to get to the Setting Passcode Activity now press the Skip button instead of setting the passcode. Close the app and restart.

**Expected behaviour:**

The User login Session should be restored.

**Observed behaviour:**

The user has to login again.

**Device and Android version:**

Android Version - Android 10
Android Device - POCO X2

**Screenshots:**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/44283521/77259902-76b47700-6caa-11ea-9a32-6f9e018862b8.gif)

**Comment by ankurs287** [comment]
Hi @refactor-droidyy , that is the whole purpose of asking the user to set up a pass-code. For reference, check out how GPay works.

**Comment by refactor-droidyy** [comment]
@ankurs287 yes you are correct but in Gpay the user is allowed to enter the Main screen if he sets a passcode successfully there is no skip button. However, we can do is that hide the skip button. What is your view regarding this?

**Comment by ankurs287** [comment]
@refactor-droidyy I do not think it is necessary. In many other major banking apps (Ex: YONO SBI), accessing features via passcode is optional after they have logged in successfully using their original credentials. 
Reason: Some users may not feel that it is as secure as logging in everytime with their username and password. I also feel a 4-digit passcode is not safe as one can withdraw/ send money to anyone without having to enter username and password.
Perhaps @naman14 @shiv07tiwari could give more reasoning on this.
