### ISSUE TITLE
Exapndable List View in Faq Activity are not align with the child elements

### ISSUE THREAD

**Issue by refactor-droidyy** [openMF/mobile-wallet#851]
**Summary:**

In Faq Activity, the Expandable ListView is not aligned with the child view text.

**Steps to reproduce:**

Navigate to FAQ section clicking on the overlay menu icon.expand the list by clicking on down arrow. 

**Expected behaviour:**

The child view after the expanding of ListView should be the same align to each other.

**Observed behaviour:**

Currently, the child views text that shows the answer is not aligned to the text of the ListView.

**Device and Android version:**

Android Version - Android 10
Android Device - POCO X2

**Screenshots:**

![Screenshot_2020-03-23-12-37-08-333_org mifos mobilewallet mifospay](https://user-images.githubusercontent.com/44283521/77291242-e0ad3a80-6d03-11ea-867f-f695c9c41e7f.jpg)

**Comment by luckyman20** [comment]
@refactor-droidyy To me, current margins look perfect. I don't see any reason to align the answers with questions. Thank you for your contributions :)
