### ISSUE TITLE
Fix: Show error or toast when account number is not enough

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#857]
**Summary:**
In SetupUpiPIN, the account number of debit card accepts any number of digits even 1 digit. We should give a toast when the user doesnt enter sufficient amount of digits which is usually 16 or even 15 in case of Amex.

**Comment by Bhavnaharitsa** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37215508/77497722-035e6100-6e74-11ea-8b92-a4ccaf40a760.gif)

**Comment by shobhit24** [comment]
I am on it

**Comment by Bhavnaharitsa** [comment]
@shobhit24 Sorry, I'm working on it! :))

**Comment by shobhit24** [comment]
We should check the length of debit card number in between 12-19, as debit card number count ranges from 12 to 19.

**Comment by shobhit24** [comment]
@Bhavnaharitsa , please have a look at it
