### ISSUE TITLE
No session for login. App asks for login whenever opened.

### ISSUE THREAD

**Issue by HaripriyaB** [openMF/mobile-wallet#862]
**Summary:** 
When user closes the app and reopens the session is closed and asks to login again.
**Steps to reproduce:**
1.open app and login using test credentials: username: mifospay01 pwd: Password1
2. close the app
3. reopen. U can find that the session is closed and app asks for login again.

**Expected behavior:**
Open home page instead of login page.
**Device and Android version:**
Android 9
Oppo A9 2020

Recording:

![screenrecorder-mifosissue](https://user-images.githubusercontent.com/34762451/77840175-e1314f80-71a1-11ea-94c3-553ad280841e.gif)

**Comment by devansh-299** [comment]
@HaripriyaB this is not a bug but actually a feature that the developers wanted to include to ensure maximum security.

**Comment by HaripriyaB** [comment]
oh...so there is no need for a fix?

**Comment by devansh-299** [comment]
> oh...so there is no need for a fix?

yeah, according to me there's no need to work on this
