### ISSUE TITLE
Incorporate the official Mifos Pay logo into the app

### ISSUE THREAD

**Issue by dubeyaayush07** [openMF/mobile-wallet#870]
**Summary:**

The official [logo](https://drive.google.com/drive/folders/1-TJ-pB3h6CvKWcR0LBcKbrypWpDnNKdo) for Mifos Pay has been designed and approved. We should start implementing this logo in the app.

**Comment by dubeyaayush07** [comment]
I would like to work on this

**Comment by refactor-droidyy** [comment]
@dubeyaayush07 The official logo looks great. Apart from the login and passcode layout where else you find putting the official logo beneficial?

**Comment by dubeyaayush07** [comment]
> @dubeyaayush07 The official logo looks great. Apart from the login and passcode layout where else you find putting the official logo beneficial?

@refactor-droidyy I am thinking we can use it as the app icon also

**Comment by refactor-droidyy** [comment]
@dubeyaayush07 Great :+1: . It would be great if the receipt has the Mifos Pay logo I mean it will really look good.

**Comment by dubeyaayush07** [comment]
@refactor-droidyy Yeah you are right, thanks

**Comment by rachittt** [comment]
@dubeyaayush07 implement it on the app icon for now. We can wait for the project maintainers to comment regarding other use cases.

**Comment by Bhavnaharitsa** [comment]
@dubeyaayush07 @rachittt If the logo is finalized, then I would like to implement Splash screen. What say?

**Comment by dubeyaayush07** [comment]
> @dubeyaayush07 @rachittt If the logo is finalized, then I would like to implement Splash screen. What say?

@Bhavnaharitsa Seems like a nice idea, do ask the maintainers first
