### ISSUE TITLE
Adds Cards: Toast message not required

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#872]
**Summary:**

Pressing the add card button without giving the complete details shows "Your card has expired" toast message. There's no need for this toast message

**Steps to reproduce:**

* Go to Finance -> Cards Tab
* Tap on Add Cards 
* Enter incomplete details and click on ADD button

**Expected behavior:**

Toast message shouldn't be displayed

**Device and Android version:**

Xiaomi PocoF1
Android 10
Stock rom
**Screen Recording:**

![GIF-200403_163835](https://user-images.githubusercontent.com/46667021/78354633-d9badd80-75c9-11ea-8950-736033178275.gif)

**Comment by dubeyaayush07** [comment]
@devansh-299 It is for the expiry date, as the date is set to the current date by default.The the toast is displayed when the user tries to add the card without modifying the default date. Although I agree the toast seems a bit out of place.

**Comment by devansh-299** [comment]
> @devansh-299 It is for the expiry date, the date is set to the current date by default. The the toast is displayed when the user tries to add the card without modifying the default date. Although I agree the toast seems a bit out of place.

Yes, I also realised this after looking at the code. Thanks
