### ISSUE TITLE
feat: Dark mode support

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#875]
**Feature Description:**

These days, most of the applications are providing an option to switch to dark mode to the users. Mifos Pay is currently based on light theme and users should be provided with an option to switch to dark mode instead.

**Comment by devansh-299** [comment]
@shiv07tiwari @naman14 can I work on implementing this feature?

**Comment by Bhavnaharitsa** [comment]
@devansh-299 @shiv07tiwari @rachittt @luckyman20 Is this still a valid issue? Though I think it is trivial at this stage, please voice your opinions. And if we are proceeding with working on it, @devansh-299 Can I take this up? :)

**Comment by mrudultora** [comment]
@devansh-299  @Bhavnaharitsa  Is anyone working on it ? May I take this one ?

**Comment by deepak-prajapatii** [comment]
@Bhavnaharitsa @devansh-299 @mrudultora @siebrand Can I work on this issue?

**Comment by devansh-299** [comment]
@deepak-prajapatii @mrudultora this issue has already been solved by #1012, we are not merging this pull request right now as adding multi-theme support requires migrating to AndroidX which will make all the open PRs outdated.

**Comment by deepak-prajapatii** [comment]
> @deepak-prajapatii @mrudultora this issue has already been solved by #1012, we are not merging this pull request right now as adding multi-theme support requires migrating to AndroidX which will make all the open PRs outdated.

Ok
