### ISSUE TITLE
fix: Change the screenshots with new logo in it

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#888]
**Summary:**

The Screenshots.md file has the entire screenshots of the app but the logo is of the previous one. Since we have changed the logo, I think it would be better if we update the Readme as well.

**Comment by dubeyaayush07** [comment]
I think we should wait a little bit as the logo is not fully integrated yet (login, passcode, receipt, splash).

**Comment by Bhavnaharitsa** [comment]
@dubeyaayush07 Yes, we can wait :)

**Comment by rchtgpt** [comment]
@Bhavnaharitsa you can work on this issue now. For splash screen GIF, refer #913

**Comment by Bhavnaharitsa** [comment]
@rachittt Thanks, will update soon :)

**Comment by haran2248** [comment]
@Bhavnaharitsa @dotrachit Can i work on this issue?

**Comment by Bhavnaharitsa** [comment]
Go ahead :)

**Comment by devansh-299** [comment]
@Bhavnaharitsa in `README.md` we are already using the updated logo. Can you please explain the issue?

**Comment by Bhavnaharitsa** [comment]
@devansh-299 Oh Snap!! I didn't realise it. Anyways, please check if we need the circular logo else we can close the issue. 
Thanks for clarifying, @devansh-299

**Comment by haran2248** [comment]
The updated logo is circular in shape i guess

**Comment by devansh-299** [comment]
@Bhavnaharitsa @haran2248 please look at [this thread](https://github.com/openMF/mobile-wallet/pull/879#issuecomment-611618120). I think we can close this issue

**Comment by devansh-299** [comment]
Closing the issue as this issue is not relevant anymore
