### ISSUE TITLE
Edit Profile Photo Header Should Not Be Persistant

### ISSUE THREAD

**Issue by ethan627hsu** [openMF/mobile-wallet#89]
**Summary:**

When editing the user profile, the user photo persists when scrolling downward

**Steps to reproduce:**

Go to the profile section and select the edit icon in the top right. Inflate the "change password" or "change passcode" and start scrolling, you will then see the profile picture persist, instead of scrolling away.

**Expected behavior:**

The profile picture should match the scroll behavior, and not stick out which confuses the UI. 

**Observed behavior:**

The profile picture awkwardly persists past other attributes.

**Device and Android version:**

Google Pixel, Android 9.0 Pie

**Screenshots:**
![image](https://user-images.githubusercontent.com/24931732/48309930-6fb71980-e538-11e8-90e3-9c29050d6ba3.png)

**Comment by letelete** [comment]
I agree. It really got me confused on my first time playing with app.
