### ISSUE TITLE
Keyboard hides VPA EditText View while typing

### ISSUE THREAD

**Issue by shobhit24** [openMF/mobile-wallet#897]
**Summary:**
In the SendFragment, while entering the Virtual Payment Address the keyboard hides the view field.

**Expected behavior:**
It should be scrollable if the keyboard hides any EditText view

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/48084596/79493512-3644e080-803f-11ea-9f0b-d30b0fb4770d.gif)

**Comment by HaripriyaB** [comment]
Duplicate https://github.com/openMF/mobile-wallet/issues/774#issue-572555999

**Comment by HaripriyaB** [comment]
And this issue has already been resolved.

**Comment by shobhit24** [comment]
@HaripriyaB oh okay
I'm closing this issue.
