### ISSUE TITLE
Set maxlength for credit card number and change the label "Credit Card number" to "Debit/Credit Card number"

### ISSUE THREAD

**Issue by shobhit24** [openMF/mobile-wallet#899]
**Summary:**

In Add Card feature: The label "Credit Card number" must be changed to "Debit/Credit Card number" and,
 We should set a maximum length for a user to enter "Debit/Credit Card number" i.e. 19.

**Screenshots:**

![credit_card](https://user-images.githubusercontent.com/48084596/79629700-4822a280-8169-11ea-9d2c-c83adfb29da9.gif)

**Comment by refactor-droidyy** [comment]
@shobhit24 please refer to this #652 .

**Comment by shobhit24** [comment]
> @shobhit24 please refer to this #652 .

Oh, Okay.
And what do you think about label name ?
