### ISSUE TITLE
chore: Convert ValidateUtil class to Kotlin Object

### ISSUE THREAD

**Issue by s-ayush2903** [openMF/mobile-wallet#903]
**Summary:**
Currently, the ValidateUtil class is written in java, it should be translated to kotlin instead which makes the code much more legible and cleaner.

**Steps to reproduce:**
Since it is a chore issue so it can directly be seen in the codebase at 
`mobile-wallet/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils`

**Expected behavior:**
It should be written in kotlin instead

**Observed behavior:**
The concerned class is written in java

**Device and Android version:**
NA

**Screenshots:**
NA

**Comment by s-ayush2903** [comment]
I'm seeking permission to work on this issue as soon as the verdict of #902 gets declared

**Comment by luckyman20** [comment]
@s-ayush2903 You can work on this issue now.
