### ISSUE TITLE
Delete landscape layouts

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#907]
**Summary:**

Since the application is fixed to be used in Portrait orientation, there's no use of having separate landscape friendly layouts. Hence we can get rid of:
* `mobile-wallet/mifospay/src/main/res/layout-land/activity_login.xml` 
* `mobile-wallet/mifospay/src/main/res/layout-land/scrollable_tab_layout.xml`

**Comment by Bhavnaharitsa** [comment]
@devansh-299 Are you working on it?
If not, I'm ready to take up :)

**Comment by devansh-299** [comment]
@Bhavnaharitsa you can work on it
