### ISSUE TITLE
Use updated MifosPay logo in transaction receipts

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#908]
**Summary:**

Since the new MifosPay logo has been finalized, we can use the new MifosPay logo instead of the Mifos logo. 

**Steps to reproduce:**

* Go to Payments -> History tab
* Tap on any transaction to view its details
* Select ViewReceipt and new Mifos logo being used in the receipt

**Expected behavior:**

<img src="https://user-images.githubusercontent.com/46667021/82127828-25b98e80-97d4-11ea-9e5e-23ea4fb3c902.jpeg" width="360" height="640">

**Comment by s-ayush2903** [comment]
I think, we can have the same tweak at the login screen as well

**Comment by devansh-299** [comment]
> I think, we can have the same tweak at the login screen as well

@s-ayush2903 after discussion we dropped this idea as the current implementation looks much more better. Read [this](https://github.com/openMF/mobile-wallet/pull/886) thread
