### ISSUE TITLE
Bug: GoogleSignIn Failure Causes Stacking

### ISSUE THREAD

**Issue by s-ayush2903** [openMF/mobile-wallet#917]
**Summary:**
Whenever the google signIn fails, an intent is generated that takes from **LoginActivity to LoginActivity itself** . If google signin is Deliberately made to fail multiple times then it leads to the piling up of the stacks which have the same LoginActivity as their all of their entries which ends up in useless consumption of resources
 
**Steps to reproduce:**
* Turn off the internet connection
* Follow the flow for logging in using googleSignIn
* (It fails automatically, and LoginActivity is put on stack)
* Now keep repeating the second step, stacking will take place
* In order to check the backstack, now click back button, by this, we are sent back to the LoginActivity itself and the presence of stack can be seen.  

**Expected behavior:**
Nothing like the piling up of the stack should have taken place

**Observed behavior:**
Multiple entries(instances) of LoginActivity

**Device and Android version:**
Oppo A83 and 7.1.1

**Screenshots:**

![2020-05-19-03-28-02](https://user-images.githubusercontent.com/56556919/82264734-1fb5e000-9983-11ea-8e85-12549dfd912e.gif)

**Comment by s-ayush2903** [comment]
I would like to fix this issue

**Comment by rachittt** [comment]
@s-ayush2903 go ahead
