### ISSUE TITLE
chore: Convert Utils Class to Kotlin Object

### ISSUE THREAD

**Issue by s-ayush2903** [openMF/mobile-wallet#922]
Summary:
Currently, the Utils class is written in java, it should be translated to kotlin instead which makes the code much more legible and cleaner.

Steps to reproduce:
Since it is a chore issue so it can directly be seen in the codebase at
`mobile-wallet/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils`

Expected behavior:
It should be written in kotlin instead

Observed behavior:
The concerned class is written in java

Device and Android version:
NA

Screenshots:
NA

**Comment by s-ayush2903** [comment]
Looking for approval of issue/views of collaborators and peers. 
I would love to fix the same if it turns out to be a valid issue.

**Comment by s-ayush2903** [comment]
@luckyman20 @rachittt @shiv07tiwari Please look into the issue and state whether it is good enough to fix

**Comment by luckyman20** [comment]
@s-ayush2903 you can go ahead.
