### ISSUE TITLE
KYC fragment - user taken back to home fragment in case of fetching kyc details failure

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#949]
**Summary:**

Currently, whenever there's an error in fetching Kyc level details, a toast message - "Please try again" is shown taking him/her back to the home fragment. Since we are using `ViewPager` and loading 2 fragments at a time, this means any time there's a problem in fetching KYC details, the user won't be able to use `MerchantFragment` also. This is not desired, instead of taking user back to home fragment, this should have been handled by showing a dedicated error screen as done in other fragments.

**Code Snippets:**

<img src="https://user-images.githubusercontent.com/46667021/82560968-164d9300-9b90-11ea-98ff-6105f2d4d6da.png" width="800" height="400">

**Expected behavior:**

Instead of taking user back to home screen, this should have been handled by showing a error message as done in other fragments

**Observed behavior:**

User is taken back to home screen incase of any failure in fetching Kyc details

**Comment by devansh-299** [comment]
@shiv07tiwari @luckyman20 can I work on this issue?

**Comment by luckyman20** [comment]
@devansh-299 Go ahead.
