### ISSUE TITLE
LoginActivity - mifosSavingsProductId parameter not used

### ISSUE THREAD

**Issue by devansh-299** [openMF/mobile-wallet#953]
**Summary:**

While creating a new user, the parameter `mifosSavingsProductId` in `LoginActivity` is not bundled and passed to `MobileVerficationActivity` as it should have been to be used later for creating a new client. As a result of this, the default value of 0 is being used in place which causes error while creating a client.

<img src="https://user-images.githubusercontent.com/46667021/82731011-8b040700-9d21-11ea-8991-9717033fc99c.jpeg" width="150" height="300">

**Code:**

![ss](https://user-images.githubusercontent.com/46667021/82731073-ea621700-9d21-11ea-8b66-1e5e1a3e77b5.png)

**Comment by devptyagi** [comment]
If this is available, I'd like to work on it.

**Comment by devansh-299** [comment]
Solved by #967
