### ISSUE TITLE
fix: Change the logo to new logo in LoginActivity

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#954]
## Summary:

The LoginActivity has the older logo of the app. While the logo is updated now, I think it should be updated in the entire app among which the LoginActivity is missing its logo. 

## Expected design:
![Group 19@2x](https://user-images.githubusercontent.com/44428198/82738213-a7b93280-9d53-11ea-8a32-150a84c38f5d.jpg)

## Link for asset (logo-outline):
https://drive.google.com/open?id=1y53mJmoZ8lc0YiR9gNtF0V8zZ5muu6mH

**Comment by Bhavnaharitsa** [comment]
@rachittt I would not like to work on the issue. As we are giving tags, this could be a first-time contributor issue :). Please update it if you feel it is right

**Comment by rachittt** [comment]
I am going to post two designs below. Kindly react to the design which you think is better for our app.

**Comment by rachittt** [comment]
![WhatsApp Image 2020-05-23 at 10 58 59 PM](https://user-images.githubusercontent.com/44428198/82738186-7fc9cf00-9d53-11ea-9478-fc0851e618b6.jpeg)

**Comment by rachittt** [comment]
![Group 19@2x](https://user-images.githubusercontent.com/44428198/82738213-a7b93280-9d53-11ea-8a32-150a84c38f5d.jpg)

**Comment by Bhavnaharitsa** [comment]
@rachittt Is anybody working on this? Or else I can take up the issue and make a pr asap
