### ISSUE TITLE
fix: Dependency upgradation

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#955]
**Summary:**
The build.gradle file has older dependency versions. It needs to be updated to the current version. 
![image](https://user-images.githubusercontent.com/37215508/82778427-058e6d00-9e6f-11ea-9c6a-8b64b5fde513.png)

I would work on it :)

**Comment by s-ayush2903** [comment]
As far as i  know, we have renovate for the same :-)

**Comment by Bhavnaharitsa** [comment]
> As far as i  know, we have renovate for the same :-)
> …

Could you show me where? I am not able to find out :)

**Comment by rchtgpt** [comment]
we have renovate bot for all the dependency upgradations.
