### ISSUE TITLE
Screenshot.md file is not mobile friendly

### ISSUE THREAD

**Issue by rchtgpt** [openMF/mobile-wallet#965]
**Summary:**

the grids that we have used in `Screenshots.md` are not the best way to go about it IMO because we need to make it responsive.

**Steps to reproduce:**

open [this link](https://github.com/OpenMF/mobile-wallet/blob/dev/Screenshot.md) on a mobile device.

**Expected behavior:**

Screenshots should be clearly visible even on phone.

**Comment by Bhavnaharitsa** [comment]
@rachittt I got the point here. I strongly feel it is because the dimensions are hardcoded which was the whole point to use this method is to not hard code. However, we can fix it by centering the images and removing the hardcoded dimensions. I'm sure it'll work :)
I would like to take up the issue
