### ISSUE TITLE
Bad keyboard behavior during "new passcode" flow

### ISSUE THREAD

**Issue by ethan627hsu** [openMF/mobile-wallet#98]
**Summary:**

When adding a new passcode, the EditTexts allow the user to type in letters (for a only number password), and an infinite amount of characters (for a 4 digit passcode). 

**Steps to reproduce:**

Visit the profile section and go to the editor by pressing the edit icon in the top right. In the editor, try updating the passcode. The EditTexts should have the behavior described in the summary.

**Expected behavior:**

The EditTexts should only allow valid 4-digit number passcodes

**Observed behavior:**

The EditTexts allow the user to type in letters (for a only number password), and an infinite amount of characters (for a 4 digit passcode)

**Device and Android version:**

Google Pixel, Android 9.0 Pie

**Screenshots:**

![image](https://user-images.githubusercontent.com/24931732/48317533-ad538b00-e5a8-11e8-8478-6d03197e9f4c.png)

**Comment by ankurs287** [comment]
@ethan627hsu Thanks for your effort. But to change the passcode, we'll be directing user to mifos-passcode library. If you want to work on the task to change passcode, please visit:-https://github.com/openMF/mifos-passcode

**Comment by ankurs287** [comment]
@ethan627hsu Sure. I will.

**Comment by luckyman20** [comment]
@ethan627hsu It has been already reported by @drish1001
